### ISSUE TITLE
[BUG] when update module, manager crash

### ISSUE THREAD

**Issue by steven7851** [LSPosed/LSPosed#110]
**什么情况/What happened?**
when update module, manager crash

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**

**版本信息/Versions**

Android: 8.0.0

Magisk: 21.4 (21400)

Riru: 23.4

LSPosed: 5149, manager 5197

**相关日志/Related Logs**
```
Build version: v0.5.4.0 
Build date: 1981-01-01 01:01:02 
Current date: 2021-02-09 22:48:43 
Device: Sony G8142 
 
Stack trace:  
android.app.RemoteServiceException: Bad notification posted from package io.github.lsposed.manager: Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=io.github.lsposed.manager id=0x7f080086) visible user=0 )
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:251)
	at android.app.ActivityThread.main(ActivityThread.java:6563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```

**Comment by tehcneko** [comment]
@steven7851 这是 MIUI 的问题

**Comment by steven7851** [comment]
这只手机是 sony，是 UI 问题吗，那就没办法了
