### ISSUE TITLE
[bug] lsposed shortcut make launcher crash

### ISSUE THREAD

**Issue by vvb2060** [LSPosed/LSPosed#1134]
@yujincheng08 @canyie latest build LSPosed-v1.5.4-6043-release.zip seems to brake the shortcut of lsposed on the launcher if you try to tap and hold the lsposed shortcut the launcher crashes.tapping the launcher works and enters lsposed gui but cant seems to remove shortcut even after disabling lsposed on magisk manager and restarting phone

_Originally posted by @kevin01523 in https://github.com/LSPosed/LSPosed/issues/238#issuecomment-922255526_

**Comment by kevin01523** [comment]
Here some logs i hope it doesn't contain sensitive information
[LSPosed_2021-09-18T18_32_44.309.zip](https://github.com/LSPosed/LSPosed/files/7189771/LSPosed_2021-09-18T18_32_44.309.zip)
[LSPosed_2021-09-18T18_47_38.562.zip](https://github.com/LSPosed/LSPosed/files/7189772/LSPosed_2021-09-18T18_47_38.562.zip)
For some reason gms broke too but i fixed it

**Comment by yujincheng08** [comment]
similar issue reported by another user:
```
#######RuntimeEnvironmentInformation#######
crash time=2021-09-17 10:13:43.650
model=MI 9
android version=11(30)
brand=Xiaomi
manufacturer=Xiaomi
board=cepheus
hardware=qcom
device=cepheus
version name=11
supported ABIs=arm64-v8a & armeabi-v7a & armeabi
display=RQ3A.210805.001.A1 release-keys
#######ForceCloseCrashLog#######
FATAL EXCEPTION: main
Process: com.android.launcher3, PID: 17382
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getPackageName()' on a null object reference
 at com.android.launcher3.popup.SystemShortcut.lambda$static$2(SystemShortcut.java:201)
 at com.android.launcher3.popup.-$$Lambda$SystemShortcut$SF62XObPiBhToXNBsVZ02HUcZiE.getShortcut(Unknown Source:0)
 at com.android.launcher3.popup.PopupContainerWithArrow.lambda$showForIcon$1(PopupContainerWithArrow.java:223)
 at com.android.launcher3.popup.-$$Lambda$PopupContainerWithArrow$gxuNFAQq8rhK6zCD0jD2zH3Xl9c.apply(Unknown Source:6)
 at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:203)
 at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
 at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
 at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
 at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
 at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:475)
 at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
 at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:236)
 at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:517)
 at com.android.launcher3.popup.PopupContainerWithArrow.showForIcon(PopupContainerWithArrow.java:225)
 at com.android.launcher3.Workspace.beginDragShared(Workspace.java:1507)
 at com.android.launcher3.Workspace.beginDragShared(Workspace.java:1451)
 at com.android.launcher3.Workspace.startDrag(Workspace.java:1440)
 at com.android.launcher3.touch.ItemLongClickListener.beginDrag(ItemLongClickListener.java:77)
 at com.android.launcher3.touch.ItemLongClickListener.onWorkspaceItemLongClick(ItemLongClickListener.java:58)
 at com.android.launcher3.touch.ItemLongClickListener.lambda$n_ku6Bnp7SQn-CFIT2R46R_RyW8(Unknown Source:0)
 at com.android.launcher3.touch.-$$Lambda$ItemLongClickListener$n_ku6Bnp7SQn-CFIT2R46R_RyW8.onLongClick(Unknown Source:0)
 at android.view.View.performLongClickInternal(View.java:7528)
 at android.view.View.performLongClick(View.java:7486)
 at android.widget.TextView.performLongClick(TextView.java:12478)
 at android.view.View.performLongClick(View.java:7504)
 at android.view.View$CheckForLongPress.run(View.java:28263)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:223)
 at android.app.ActivityThread.main(ActivityThread.java:7669)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by kevin01523** [comment]
Testing on 6044 still the same

**Comment by yujincheng08** [comment]
I cannot reproduce it so I cannot fix it in short.

**Comment by kevin01523** [comment]
I think it depends on the launcher if the built in launcher a.k.a shady launcher it crashes if i hold the lsposed logo but in pixel launcher it doesn't crash.
Only my guess is. it has to do with the options that pop out when you hold the shortcut icon where lsposed shortcut doesn't give any info thats why it crashes the launcher.

**Comment by etmatrix** [comment]
I have a similar issue on Android x86 8.1-r6 I installed on vm VirtualBox [here](https://gofile.io/d/E6isu5) you can download the disk and config.
The shortcur is created but when I try to tap I got this:

```
09-19 04:46:19.833  3075  3075 I LSPosed-Bridge: Crash unexpectedly: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.shell/com.android.shell.BugreportWarningActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
09-19 04:46:19.833  3075  3075 I LSPosed-Bridge: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
09-19 04:46:19.833  3075  3075 I LSPosed-Bridge: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
09-19 04:46:19.833  3075  3075 I LSPosed-Bridge: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
09-19 04:46:19.833  3075  3075 I LSPosed-Bridge: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
09-19 04:46:19.833  3075  3075 I LSPosed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-19 04:46:19.833  3075  3075 I LSPosed-Bridge: 	at android.os.Looper.loop(Looper.java:164)
09-19 04:46:19.833  3075  3075 I LSPosed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
09-19 04:46:19.833  3075  3075 I LSPosed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
09-19 04:46:19.833  3075  3075 I LSPosed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:463)
09-19 04:46:19.833  3075  3075 I LSPosed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
09-19 04:46:19.833  3075  3075 I LSPosed-Bridge: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
09-19 04:46:19.833  3075  3075 I LSPosed-Bridge: 	at com.android.shell.BugreportWarningActivity.onCreate(BugreportWarningActivity.java:54)
09-19 04:46:19.833  3075  3075 I LSPosed-Bridge: 	at android.app.Activity.performCreate(Activity.java:7019)
09-19 04:46:19.833  3075  3075 I LSPosed-Bridge: 	at android.app.Activity.performCreate(Activity.java:7010)
09-19 04:46:19.833  3075  3075 I LSPosed-Bridge: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
09-19 04:46:19.833  3075  3075 I LSPosed-Bridge: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
09-19 04:46:19.833  3075  3075 I LSPosed-Bridge: 	... 9 more
09-19 04:46:19.833  3075  3075 E AndroidRuntime: FATAL EXCEPTION: main
09-19 04:46:19.833  3075  3075 E AndroidRuntime: Process: com.android.shell, PID: 3075
09-19 04:46:19.833  3075  3075 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.shell/com.android.shell.BugreportWarningActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
09-19 04:46:19.833  3075  3075 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
09-19 04:46:19.833  3075  3075 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
09-19 04:46:19.833  3075  3075 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
09-19 04:46:19.833  3075  3075 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
09-19 04:46:19.833  3075  3075 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-19 04:46:19.833  3075  3075 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
09-19 04:46:19.833  3075  3075 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
09-19 04:46:19.833  3075  3075 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-19 04:46:19.833  3075  3075 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:463)
09-19 04:46:19.833  3075  3075 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
09-19 04:46:19.833  3075  3075 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
09-19 04:46:19.833  3075  3075 E AndroidRuntime: 	at com.android.shell.BugreportWarningActivity.onCreate(BugreportWarningActivity.java:54)
09-19 04:46:19.833  3075  3075 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7019)
09-19 04:46:19.833  3075  3075 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7010)
09-19 04:46:19.833  3075  3075 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
09-19 04:46:19.833  3075  3075 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
09-19 04:46:19.833  3075  3075 E AndroidRuntime: 	... 9 more
09-19 04:46:19.834  1333  1387 W ActivityManager:   Force finishing activity com.android.shell/.BugreportWarningActivity
09-19 04:46:19.836  1333  1349 I ActivityManager: Showing crash dialog for package com.android.shell u0
```

The shortcut of magisk manager when is hidden works.
With different launcher as Nova Launcher the shortcur is not created.

**Comment by kevin01523** [comment]
@etmatrix afaik the shortcut shouldn't exist in any launcher for it to prompt to add a shortcut on a new launcher so you have to set it as default 1st and restart the emulator

**Comment by etmatrix** [comment]
I tested on Android x86 9.0-r2 and works: add, tap and long press.

**Comment by kevin01523** [comment]
Still broken on 6056 same error
