### ISSUE TITLE
[Bug] cannot open manager

### ISSUE THREAD

**Issue by kevin01523** [LSPosed/LSPosed#1151]
### Steps to reproduce/复现步骤

Install lsposed 6053 from latest actions on master
Restart and add shortcut to launcher
Tap launcher 

### Expected behaviour/预期行为

Normally opens lsposed manager

### Actual behaviour/实际行为

Manager wont open
And shell crashes

### Xposed Module List/Xposed 模块列表

```shell
Hideapplist
Xprivacylua
Lucky patcher
Disable flag secure 2.0
Kpn opener
...
```

### Magisk Module List/Magisk 模块列表

```shell
Riru lsposed
Riru unshare
Riru safetynet patch 2.1.0
Magisk props config
Busybox module
Advanced charging controller
Disable screenshot and camera sounds
Riru momohider
```

### LSPosed version/LSPosed 版本

6053

### Android version/安卓版本

10

### Magisk version/Magisk 版本

23.0001 Canary

### Riru version/Riru 版本

26.1.2r505

### CI Version/CI 版本

- [X] I am using latest CI version of LSPosed/我正在使用最新 CI 版本

### Logs/日志

[log.zip](https://github.com/LSPosed/LSPosed/files/7201826/log.zip)

```
[ 2021-09-21T16:47:29.016        0:   709:   863 I/LSPosed         ] verifyInstallerSignature: true
[ 2021-09-21T16:47:29.021        0:   709:   863 E/LSPosedService  ] failed to open manager apk
java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.ContextImpl android.app.ActivityThread.getSystemContext()' on a null object reference
	at y0.a(Unknown Source:27)
	at r1.i(Unknown Source:64)
	at Y0.onTransact(Unknown Source:28)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
[ 2021-09-21T16:47:29.031     2000:  8811:  8811 I/LSPosed         ] Loading modules for com.android.shell/2000
[ 2021-09-21T16:47:29.126     2000:  8811:  8811 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.shell/com.android.shell.BugreportWarningActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
	at com.android.shell.BugreportWarningActivity.onCreate(BugreportWarningActivity.java:54)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 11 more
[ 2021-09-21T16:47:29.126     2000:  8811:  8811 E/AndroidRuntime  ] FATAL EXCEPTION: main
Process: com.android.shell, PID: 8811
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.shell/com.android.shell.BugreportWarningActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
	at com.android.shell.BugreportWarningActivity.onCreate(BugreportWarningActivity.java:54)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 11 more
[ 2021-09-21T16:47:44.457        0:   624:  7488 D/Magisk          ] su: return code=[0]
[ 2021-09-21T16:47:50.338        0:   709:   863 I/LSPosed         ] verifyInstallerSignature: true
[ 2021-09-21T16:47:50.339        0:   709:   863 E/LSPosedService  ] failed to open manager apk
java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.ContextImpl android.app.ActivityThread.getSystemContext()' on a null object reference
	at y0.a(Unknown Source:27)
	at r1.i(Unknown Source:64)
	at Y0.onTransact(Unknown Source:28)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
[ 2021-09-21T16:47:50.353     2000:  9627:  9627 I/LSPosed         ] Loading modules for com.android.shell/2000
[ 2021-09-21T16:47:50.432     2000:  9627:  9627 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.shell/com.android.shell.BugreportWarningActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
	at com.android.shell.BugreportWarningActivity.onCreate(BugreportWarningActivity.java:54)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 11 more
[ 2021-09-21T16:47:50.432     2000:  9627:  9627 E/AndroidRuntime  ] FATAL EXCEPTION: main
Process: com.android.shell, PID: 9627
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.shell/com.android.shell.BugreportWarningActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
	at com.android.shell.BugreportWarningActivity.onCreate(BugreportWarningActivity.java:54)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 11 more
[ 2021-09-21T16:47:53.329        0:   709:   863 I/LSPosed         ] verifyInstallerSignature: true
[ 2021-09-21T16:47:53.329        0:   709:   863 E/LSPosedService  ] failed to open manager apk
java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.ContextImpl android.app.ActivityThread.getSystemContext()' on a null object reference
	at y0.a(Unknown Source:27)
	at r1.i(Unknown Source:64)
	at Y0.onTransact(Unknown Source:28)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
[ 2021-09-21T16:47:53.342     2000:  9748:  9748 I/LSPosed         ] Loading modules for com.android.shell/2000
[ 2021-09-21T16:47:53.421     2000:  9748:  9748 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.shell/com.android.shell.BugreportWarningActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
	at com.android.shell.BugreportWarningActivity.onCreate(BugreportWarningActivity.java:54)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 11 more
[ 2021-09-21T16:47:53.421     2000:  9748:  9748 E/AndroidRuntime  ] FATAL EXCEPTION: main
Process: com.android.shell, PID: 9748
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.shell/com.android.shell.BugreportWarningActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
	at com.android.shell.BugreportWarningActivity.onCreate(BugreportWarningActivity.java:54)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 11 more
```

**Comment by kevin01523** [comment]
Lsposed 6054

[log 6054.zip](https://github.com/LSPosed/LSPosed/files/7202008/log.6054.zip)


```
[ 2021-09-21T17:15:34.737        0:   709:   873 I/LSPosed         ] verifyInstallerSignature: true
[ 2021-09-21T17:15:34.738        0:   709:   873 E/LSPosedService  ] failed to open manager apk
java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.ContextImpl android.app.ActivityThread.getSystemContext()' on a null object reference
	at y0.a(Unknown Source:27)
	at r1.i(Unknown Source:64)
	at Y0.onTransact(Unknown Source:28)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
[ 2021-09-21T17:15:34.754     2000:  5412:  5412 I/LSPosed         ] Loading modules for com.android.shell/2000
[ 2021-09-21T17:15:34.837     2000:  5412:  5412 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.shell/com.android.shell.BugreportWarningActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
	at com.android.shell.BugreportWarningActivity.onCreate(BugreportWarningActivity.java:54)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 11 more
[ 2021-09-21T17:15:34.837     2000:  5412:  5412 E/AndroidRuntime  ] FATAL EXCEPTION: main
Process: com.android.shell, PID: 5412
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.shell/com.android.shell.BugreportWarningActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
	at com.android.shell.BugreportWarningActivity.onCreate(BugreportWarningActivity.java:54)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 11 more
```

**Comment by 2Y2s1mple** [comment]
Same with @kevin01523

---------------------
LSPManagerService#createOrUpdateShortcut 
-> ShortcutInfo.Builder.setIntent(LSPManagerService.getManagerIntent())
-> PackageService.getLaunchIntentForPackage("com.android.shell");

aquired intent cmp = {com.android.shell/com.android.shell.BugreportWarningActivity}

com.android.shell.BugreportWarningActivity#onCreate

```java
    public void onCreate(Bundle bundle) {
        super.onCreate(bundle);
        this.mSendIntent = = (Intent)this.getIntent().getParcelableExtra("android.intent.extra.INTENT");
        this.mSendIntent.hasExtra("android.intent.extra.STREAM");  // crash here
```

ps: have no idea launch BugreportWarningActivity for what

**Comment by yujincheng08** [comment]
Fixed.

**Comment by kevin01523** [comment]
https://github.com/LSPosed/LSPosed/commit/fe05768189c3cfcf71783feecbc277399d660fbb
Just adding this for reference
