### ISSUE TITLE
[Bug] 创建快捷方式错误

### ISSUE THREAD

**Issue by gaoyuoppa** [LSPosed/LSPosed#1207]
### Steps to reproduce/复现步骤

1，打开LSP，在推荐使用寄生管理器弹窗上点击创建快捷方式，
2，返回桌面
3，打开横屏应用（某游戏）
4，重新打开LSP 提示报错，且无 新创建的快捷方式

### Expected behaviour/预期行为

无法创建快捷方式，根据KUAN帖子下面的方式操作结果报错了，正常应该创建了快捷方式。

### Actual behaviour/实际行为

崩溃了

### Xposed Module List/Xposed 模块列表

```shell
隐藏ROOT
xposed edge pro
zuper
隐藏应用列表
对话框取消beta
```

### Magisk Module List/Magisk 模块列表

```shell
无障碍服务守护
riru
riru- hide my applist 
riru-lsposed
媒体音量级别调节
安卓跟手驱动（未启用）
开启SELINUX
自动神仙救砖
```

### LSPosed version/LSPosed 版本

6094

### Android version/安卓版本

安卓11

### Magisk version/Magisk 版本

alpha 23001

### Riru version/Riru 版本

26.1.2

### CI Version/CI 版本

- [X] I am using latest CI version of LSPosed/我正在使用最新 CI 版本

### Logs/日志

Build version: 1.6.0 (6094) 
Current date: 2021-10-02T00:35:19.534 
Device: Nubia NX669J 
Fingerprint: nubia/NX669J/NX669J:11/RKQ1.201105.002/nubia.20210311.220146:user/release-keys 
 
SDK: 30 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.WindowInsets.getSystemWindowInsetBottom()' on a null object reference
 at s3.run(Unknown Source:14)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:262)
 at android.app.ActivityThread.main(ActivityThread.java:8810)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

**Comment by etmatrix** [comment]
(For Chinese speakers) 本项目只接受英语标题的issue。如果您不懂英语，请使用翻译工具

Google translate tell me => Error creating shortcut 
Is it correct?
