### ISSUE TITLE
[Bug] fakelocation 1.2.681.1701 doesnt work with LSPosed

### ISSUE THREAD

**Issue by MurkyWang** [LSPosed/LSPosed#1402]
### Steps to reproduce/复现步骤

install fakelocation 1.2.681.1701
enable it inside LSPosed
run fakelocation

### Expected behaviour/预期行为

it should be working

### Actual behaviour/实际行为

but it keeps saying i need to reboot no matter how many times i do that.
![屏幕截图 2021-11-13 145314](https://user-images.githubusercontent.com/54443955/141609258-701530b8-999e-4b6b-b3c2-b7ea3910bc03.png)

### Xposed Module List/Xposed 模块列表

```shell
com.rong.xposed.fakelocation
com.variable.apkhook
```

### Magisk Module List/Magisk 模块列表

```shell
LSPosed-v1.6.3-6212-zygisk
```

### LSPosed version/LSPosed 版本

v1.6.3-6212-zygisk

### Android version/安卓版本

WSA Android 11

### Magisk version/Magisk 版本

canary 23014

### Riru version/Riru 版本

None

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed.zip](https://github.com/LSPosed/LSPosed/files/7531549/LSPosed.zip)

**Comment by yujincheng08** [comment]
```
[ 2021-11-13T11:45:29.320    10064:  5779:  5779 E/LSPosed-Bridge  ] java.lang.NoSuchMethodError: android.location.LocationManager#requestLocationUpdates(android.location.LocationRequest,android.location.LocationListener,android.os.Looper,android.app.PendingIntent)#exact
	at de.robv.android.xposed.XposedHelpers.findMethodExact(Unknown Source:79)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:27)
	at com.rong.xposed.fakelocation.x.b.b$l.a(Unknown Source:36)
	at com.rong.xposed.fakelocation.x.b.b.a(Unknown Source:116)
	at com.rong.xposed.fakelocation.x.b.e.a(Unknown Source:17)
	at com.rong.xposed.fakelocation.XFakeLocation.c(Unknown Source:4)
	at com.rong.xposed.fakelocation.XFakeLocation.handleLoadPackage(Unknown Source:52)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:28)
	at D1.afterHookedMethod(Unknown Source:111)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1214)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2663)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2655)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6602)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

I don't think the problem is from our side.
