### ISSUE TITLE
[BUG] Unable to connect to LsposedBridge

### ISSUE THREAD

**Issue by L-Ryland** [LSPosed/LSPosed#156]
**什么情况/What happened?**
Lsposed Manager Interface shows my sandhook variant is already activated, but none of the modules is working at all. 

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**
Riru - Core  v23.5
Riru - Enhanced mode for Storage Isolation  v23.6
Riru - LSposed v0.5.4.1

**版本信息/Versions**

Android: 11

Magisk: 21.4

Riru: 23.5

LSPosed:

**相关日志/Related Logs**

```
LSPosed Log
--------- beginning of information
Manufacturer: samsung
Brand: samsung
Device: beyond2q
Product: beyond2qltechn
Model: SM-G9750
Fingerprint: samsung/beyond2qltezc/beyond2q:11/RP1A.200720.012/G9750ZCU4EUA9:user/release-keys
ROM description: beyond2qltezc-user 11 RP1A.200720.012 G9750ZCU4EUA9 release-keys
Architecture: arm64-v8a
Android build: RP1A.200720.012
Android version: 11
Android sdk: 30
LSPosed version: v0.5.4.1
LSPosed api: 93
Riru version: v23.5 (55)
Riru api: 10
Magisk: 21.4 (21400)
2021-02-21 11:11:43.043 8006-8006/? LSPosedBridge: hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@bd4ddcf]
2021-02-21 19:18:21.021 13784-13784/com.tencent.mm LSPosedBridge: java.lang.NoSuchMethodError: com.tencent.tinker.loader.app.TinkerApplication#onBaseContextAttached(android.content.Context)#exact
	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:364)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:205)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:280)
	at com.fkzhang.xposed.hook.ﾞˉ.ˎʼ(Unknown Source:406)
	at com.fkzhang.xposed.hook.ﾞˉ.ﾞˈ(Unknown Source:0)
	at com.fkzhang.wechatxposed.XposedInit.handleLoadPackage(Unknown Source:17)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:57)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:81)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:137)
	at io.github.lsposed.lspd._hooker.impl.LoadedApkGetCL.afterHookedMethod(LoadedApkGetCL.java:86)
	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:88)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:394)
	at SandHookerNew_d80f73e34da17c301b40feab7995d5a6a0b56621.hook(Unknown Source:46)
	at android.app.LoadedApk.getResources(LoadedApk.java:1234)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2788)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2780)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7263)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:183)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:380)
	at SandHookerNew_42b8453bf7df105343083f1377c32094be493c49.hook(Unknown Source:51)
	at android.app.ActivityThread.access$1500(ActivityThread.java:301)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2118)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

2021-02-21 19:18:22.022 14070-14070/com.tencent.mm:push LSPosedBridge: java.lang.NoSuchMethodError: com.tencent.tinker.loader.app.TinkerApplication#onBaseContextAttached(android.content.Context)#exact
	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:364)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:205)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:280)
	at com.fkzhang.xposed.hook.ﾞˉ.ˎʼ(Unknown Source:406)
	at com.fkzhang.xposed.hook.ﾞˉ.ﾞˈ(Unknown Source:0)
	at com.fkzhang.wechatxposed.XposedInit.handleLoadPackage(Unknown Source:17)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:57)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:81)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:137)
	at io.github.lsposed.lspd._hooker.impl.LoadedApkGetCL.afterHookedMethod(LoadedApkGetCL.java:86)
	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:88)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:394)
	at SandHookerNew_d80f73e34da17c301b40feab7995d5a6a0b56621.hook(Unknown Source:46)
	at android.app.LoadedApk.getResources(LoadedApk.java:1234)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2788)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2780)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7263)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:183)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:380)
	at SandHookerNew_42b8453bf7df105343083f1377c32094be493c49.hook(Unknown Source:51)
	at android.app.ActivityThread.access$1500(ActivityThread.java:301)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2118)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

2021-02-21 19:18:23.023 14220-14220/com.tencent.mm:appbrand0 LSPosedBridge: java.lang.NoSuchMethodError: com.tencent.tinker.loader.app.TinkerApplication#onBaseContextAttached(android.content.Context)#exact
	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:364)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:205)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:280)
	at com.fkzhang.xposed.hook.ﾞˉ.ˎʼ(Unknown Source:406)
	at com.fkzhang.xposed.hook.ﾞˉ.ﾞˈ(Unknown Source:0)
	at com.fkzhang.wechatxposed.XposedInit.handleLoadPackage(Unknown Source:17)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:57)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:81)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:137)
	at io.github.lsposed.lspd._hooker.impl.LoadedApkGetCL.afterHookedMethod(LoadedApkGetCL.java:86)
	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:88)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:394)
	at SandHookerNew_d80f73e34da17c301b40feab7995d5a6a0b56621.hook(Unknown Source:46)
	at android.app.LoadedApk.getResources(LoadedApk.java:1234)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2788)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2780)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7263)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:183)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:380)
	at SandHookerNew_42b8453bf7df105343083f1377c32094be493c49.hook(Unknown Source:51)
	at android.app.ActivityThread.access$1500(ActivityThread.java:301)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2118)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

2021-02-21 19:18:23.023 14241-14241/com.tencent.mm:appbrand1 LSPosedBridge: java.lang.NoSuchMethodError: com.tencent.tinker.loader.app.TinkerApplication#onBaseContextAttached(android.content.Context)#exact
	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:364)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:205)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:280)
	at com.fkzhang.xposed.hook.ﾞˉ.ˎʼ(Unknown Source:406)
	at com.fkzhang.xposed.hook.ﾞˉ.ﾞˈ(Unknown Source:0)
	at com.fkzhang.wechatxposed.XposedInit.handleLoadPackage(Unknown Source:17)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:57)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:81)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:137)
	at io.github.lsposed.lspd._hooker.impl.LoadedApkGetCL.afterHookedMethod(LoadedApkGetCL.java:86)
	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:88)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:394)
	at SandHookerNew_d80f73e34da17c301b40feab7995d5a6a0b56621.hook(Unknown Source:46)
	at android.app.LoadedApk.getResources(LoadedApk.java:1234)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2788)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2780)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7263)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:183)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:380)
	at SandHookerNew_42b8453bf7df105343083f1377c32094be493c49.hook(Unknown Source:51)
	at android.app.ActivityThread.access$1500(ActivityThread.java:301)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2118)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

2021-02-21 19:18:26.026 14549-14549/com.tencent.mm:tools LSPosedBridge: java.lang.NoSuchMethodError: com.tencent.tinker.loader.app.TinkerApplication#onBaseContextAttached(android.content.Context)#exact
	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:364)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:205)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:280)
	at com.fkzhang.xposed.hook.ﾞˉ.ˎʼ(Unknown Source:406)
	at com.fkzhang.xposed.hook.ﾞˉ.ﾞˈ(Unknown Source:0)
	at com.fkzhang.wechatxposed.XposedInit.handleLoadPackage(Unknown Source:17)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:57)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:81)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:137)
	at io.github.lsposed.lspd._hooker.impl.LoadedApkGetCL.afterHookedMethod(LoadedApkGetCL.java:86)
	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:88)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:394)
	at SandHookerNew_d80f73e34da17c301b40feab7995d5a6a0b56621.hook(Unknown Source:46)
	at android.app.LoadedApk.getResources(LoadedApk.java:1234)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2788)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2780)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7263)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:183)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:380)
	at SandHookerNew_42b8453bf7df105343083f1377c32094be493c49.hook(Unknown Source:51)
	at android.app.ActivityThread.access$1500(ActivityThread.java:301)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2118)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

2021-02-21 19:18:28.028 14784-14784/com.tencent.mm:toolsmp LSPosedBridge: java.lang.NoSuchMethodError: com.tencent.tinker.loader.app.TinkerApplication#onBaseContextAttached(android.content.Context)#exact
	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:364)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:205)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:280)
	at com.fkzhang.xposed.hook.ﾞˉ.ˎʼ(Unknown Source:406)
	at com.fkzhang.xposed.hook.ﾞˉ.ﾞˈ(Unknown Source:0)
	at com.fkzhang.wechatxposed.XposedInit.handleLoadPackage(Unknown Source:17)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:57)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:81)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:137)
	at io.github.lsposed.lspd._hooker.impl.LoadedApkGetCL.afterHookedMethod(LoadedApkGetCL.java:86)
	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:88)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:394)
	at SandHookerNew_d80f73e34da17c301b40feab7995d5a6a0b56621.hook(Unknown Source:46)
	at android.app.LoadedApk.getResources(LoadedApk.java:1234)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2788)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2780)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7263)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:183)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:380)
	at SandHookerNew_42b8453bf7df105343083f1377c32094be493c49.hook(Unknown Source:51)
	at android.app.ActivityThread.access$1500(ActivityThread.java:301)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2118)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```

**Comment by yujincheng08** [comment]
module sepcified.

**Comment by L-Ryland** [comment]
![Screenshot_20210221-194734_LSPosed](https://user-images.githubusercontent.com/41134883/108624112-aa30f000-747d-11eb-9cda-d5fe7b6142a3.jpg)

**Comment by yujincheng08** [comment]
2.17 是旧版 wx
