### ISSUE TITLE
[Feature Request] 提供隐藏底栏图标的数字角标的选项

### ISSUE THREAD

**Issue by Lehmaning** [LSPosed/LSPosed#1668]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

新版 (v1.5.3) 增加的角标真的是非常碍眼，如果使用了 Shizuku 自动安装模块更新，那个数字显示得还不准……

### Describe the solution you'd like/描述你想要的解决方案

希望能提供隐藏底栏图标的数字角标的设置选项，最好能默认开启……希望 LSPosed 能保持一如既往简约的 UI 设计。

### Additional context/其他信息

![IMG_20220211_111425](https://user-images.githubusercontent.com/60032845/153532443-634340a9-2023-40e4-9582-7018e1f1cf62.jpg)

**Comment by vvb2060** [comment]
我们监听应用更新广播，为什么会不准？

**Comment by Lehmaning** [comment]
> 我们监听应用更新广播，为什么会不准？

确实会不准……装的一个模块 Fuck Location，已经更新到最新版 1.2.7 了，那个红色的角标还是没去掉，仍然显示可更新。（应该和那个模块有关系）
日志是这样的：
```
[ 2022-02-13T09:11:40.595     1000:  2053:  3435 E/LSPosed-Bridge  ] java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.hiddenapibypass.HiddenApiBypass.invoke(Unknown Source:102)
	at fuck.location.xposed.helpers.ConfigGateway.universalAPICaller(ConfigGateway.kt:245)
	at fuck.location.xposed.helpers.ConfigGateway.inWhitelist(ConfigGateway.kt:256)
	at fuck.location.xposed.location.WLANHooker$hookWifiManager$2$1$4$1.invoke(WLANHooker.kt:62)
	at fuck.location.xposed.location.WLANHooker$hookWifiManager$2$1$4$1.invoke(WLANHooker.kt:58)
	at com.github.kyuubiran.ezxhelper.utils.XposedHookUtilFactory.afterHookedMethod(HookUtils.kt:361)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.getConnectionInfo(Unknown Source:14)
	at android.net.wifi.WifiManager.getConnectionInfo(WifiManager.java:2903)
	at android.net.NetworkIdentity.buildNetworkIdentity(Unknown Source:109)
	at com.android.server.net.NetworkPolicyManagerService.updateNetworkRulesNL(Unknown Source:84)
	at com.android.server.net.NetworkPolicyManagerService$9.onReceive(Unknown Source:7)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(Unknown Source:116)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:250)
	at android.os.HandlerThread.run(Unknown Source:28)
Caused by: java.lang.SecurityException: Only shell can call it
	at com.android.server.am.ActivityManagerService.setProcessMemoryTrimLevel(Unknown Source:143)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.setProcessMemoryTrimLevel(Unknown Source:25)
	at android.app.ActivityManager.setProcessMemoryTrimLevel(Unknown Source:4)
	... 19 more
```
