### ISSUE TITLE
MANAGER CRASHED log

### ISSUE THREAD

**Issue by 1234261** [LSPosed/LSPosed#169]
#It's crashed when I open it.The following is the relative log.
　　Build version: v0.5.4.1 (5250) 
Current date: 2021-02-23 07:06:27 
Device: Xiaomi Redmi K30 5G 
 
SDK: 30 
 
Stack trace:  
c.e.b.v: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at c.e.b.i.b(:13)
	at d.a.a.a.d.d$a.d(:5)
	at i.n0.g.e$a.run(:13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at c.e.b.c0.a.o(:6)
	at c.e.b.a0.z.a.a(:4)
	at c.e.b.i.b(:8)
	... 5 more

**Comment by Proanx** [comment]
Build version: v0.5.4.1 (5250) 
Current date: 2021-02-23 07:21:04 
Device: Xiaomi Redmi K30 Pro 
 
SDK: 30 
 
Stack trace:  
c.e.b.v: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at c.e.b.i.b(:13)
	at d.a.a.a.d.d$a.d(:5)
	at i.n0.g.e$a.run(:13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at c.e.b.c0.a.o(:6)
	at c.e.b.a0.z.a.a(:4)
	at c.e.b.i.b(:8)
	... 5 more

**Comment by aviraxp** [comment]
@Proanx 同

**Comment by Ravenightwing** [comment]
Same problem this morning
device xiaomi 10

**Comment by icespite** [comment]
Build version: v0.5.4.1 (5250) 
Current date: 2021-02-23 07:46:01 
Device: Xiaomi Redmi K30 Pro 
 
SDK: 30 
 
Stack trace:  
c.e.b.v: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at c.e.b.i.b(:13)
	at d.a.a.a.d.d$a.d(:5)
	at i.n0.g.e$a.run(:13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at c.e.b.c0.a.o(:6)
	at c.e.b.a0.z.a.a(:4)
	at c.e.b.i.b(:8)
	... 5 more

**Comment by inkhog** [comment]
oh, I didnt see this post and opened a new issue. Same with you.
```
Build version: v0.5.4.1 (5250) 
Current date: 2021-02-23 07:38:44 
Device: Xiaomi M2002J9E 
 
SDK: 29 
 
Stack trace:  
c.e.b.v: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at c.e.b.i.b(:13)
	at d.a.a.a.d.d$a.d(:5)
	at i.n0.g.e$a.run(:13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at c.e.b.c0.a.o(:6)
	at c.e.b.a0.z.a.a(:4)
	at c.e.b.i.b(:8)
	... 5 more
```

**Comment by xiaocenter** [comment]
禁止manager联网即可，应该是商店地址出错了
