### ISSUE TITLE
[Bug] error shown in logcat E/LoadedApk: Unable to instantiate appComponentFactory

### ISSUE THREAD

**Issue by test01wrk** [LSPosed/LSPosed#1843]
### Steps to reproduce/复现步骤

1. Write a hook module for MIUI updater app(Xiaomi 11, MIUI 12.5.16 stable), and enable the module in LSPosed manager
```
public class Hook implements IXposedHookLoadPackage {
    @Override
    public void handleLoadPackage(XC_LoadPackage.LoadPackageParam lpparam) throws Throwable {
        if (lpparam != null && "com.android.updater".equals(lpparam.packageName)) {
            try {
                XposedHelpers.findAndHookMethod("com.android.updater.UpdateSettingActivity", lpparam.classLoader,
                        "onCreate", Bundle.class,
                        new XC_MethodHook() {
                            @Override
                            protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                                XposedBridge.log("[UpdaterHook] beforeHookedMethod called");
                            }
                        });
            } catch (Exception e) {
                // ignore
                XposedBridge.log("[UpdaterHook] error: " + e.getMessage());
            }
        }
    }
}

```
2. when the updater app started, an error log shown in logcat
```
2022-04-13 19:17:42.533 14919-14919/? E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/data/app/~~qfw3rN9GtpRNmthqehol7Q==/com.android.updater-VTzcdabBUUiDuKRpIbE_cQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~qfw3rN9GtpRNmthqehol7Q==/com.android.updater-VTzcdabBUUiDuKRpIbE_cQ==/lib/arm64, /data/app/~~qfw3rN9GtpRNmthqehol7Q==/com.android.updater-VTzcdabBUUiDuKRpIbE_cQ==/base.apk!/lib/arm64-v8a, /system/priv-app/RtMiCloudSDK/RtMiCloudSDK.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:262)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:907)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:960)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
        at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:103)
        at LSPHooker_.getClassLoader(Unknown Source:8)
        at android.app.LoadedApk.getResources(LoadedApk.java:1192)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2671)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2663)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6716)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
        at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:103)
        at LSPHooker_.handleBindApplication(Unknown Source:11)
        at android.app.ActivityThread.access$1400(ActivityThread.java:246)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1946)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:7892)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```
3. when the module is disabled,  there's no such error log, something's wrong

Similar to [this issue](https://github.com/taichi-framework/TaiChi/issues/1151)

### Expected behaviour/预期行为

no error log in logcat

### Actual behaviour/实际行为

error shown in logcat

### Xposed Module List/Xposed 模块列表

```shell
N/A
```

### Magisk Module List/Magisk 模块列表

```shell
N/A
```

### LSPosed version/LSPosed 版本

1.8.1(6499)

### Android version/Android 版本

11

### Magisk version/Magisk 版本

24.3

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

2022-04-13 19:17:42.533 14919-14919/? E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/data/app/~~qfw3rN9GtpRNmthqehol7Q==/com.android.updater-VTzcdabBUUiDuKRpIbE_cQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~qfw3rN9GtpRNmthqehol7Q==/com.android.updater-VTzcdabBUUiDuKRpIbE_cQ==/lib/arm64, /data/app/~~qfw3rN9GtpRNmthqehol7Q==/com.android.updater-VTzcdabBUUiDuKRpIbE_cQ==/base.apk!/lib/arm64-v8a, /system/priv-app/RtMiCloudSDK/RtMiCloudSDK.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:262)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:907)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:960)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
        at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:103)
        at LSPHooker_.getClassLoader(Unknown Source:8)
        at android.app.LoadedApk.getResources(LoadedApk.java:1192)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2671)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2663)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6716)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
        at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:103)
        at LSPHooker_.handleBindApplication(Unknown Source:11)
        at android.app.ActivityThread.access$1400(ActivityThread.java:246)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1946)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:7892)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by yujincheng08** [comment]
send `/data/app/~~qfw3rN9GtpRNmthqehol7Q==/com.android.updater-VTzcdabBUUiDuKRpIbE_cQ==/base.apk`

**Comment by test01wrk** [comment]
[updater.apk.zip](https://github.com/LSPosed/LSPosed/files/8486690/updater.apk.zip)


> send `/data/app/~~qfw3rN9GtpRNmthqehol7Q==/com.android.updater-VTzcdabBUUiDuKRpIbE_cQ==/base.apk`

**Comment by yujincheng08** [comment]
![image](https://user-images.githubusercontent.com/5022927/163326147-a5d6f780-968d-4198-b06a-150e89b61c19.png)
This is not an fatal error. It's just a log and it won't crash the app.

**Comment by yujincheng08** [comment]
Oh wait, this is because we create the loadedapk ourselves and it may corrupt the default one. Maybe we should take further look at it.
