### ISSUE TITLE
Module loads multiple times in its own process

### ISSUE THREAD

**Issue by yujincheng08** [LSPosed/LSPosed#1844]
```java
    @Override
    public void handleLoadPackage(XC_LoadPackage.LoadPackageParam lpparam) {
        Log.d(TAG, "handleLoadPackage: XC_LoadPackage.LoadPackageParam -> pkgName:" + lpparam.packageName + ", procName:" + lpparam.processName + ", isFirstApp:" + lpparam.isFirstApplication);
        Log.d(TAG, "handleLoadPackage: ", new Throwable("?"));
    }
```

```
2022-04-14 14:02:39.460 4447-4447/android.playground D/MainHook: handleLoadPackage: XC_LoadPackage.LoadPackageParam -> pkgName:android.playground, procName:android.playground, isFirstApp:true
2022-04-14 14:02:39.462 4447-4447/android.playground D/MainHook: handleLoadPackage: 
    java.lang.Throwable: ?
        at android.playground.MainHook.handleLoadPackage(MainHook.java:19)
        at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
        at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
        at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
        at H.afterHookedMethod(Unknown Source:104)
        at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:132)
        at LSPHooker_.getClassLoader(Unknown Source:8)
        at android.app.LoadedApk.getResources(LoadedApk.java:956)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2282)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
        at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:103)
        at LSPHooker_.handleBindApplication(Unknown Source:11)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
2022-04-14 14:02:39.463 4447-4447/android.playground D/MainHook: handleLoadPackage: XC_LoadPackage.LoadPackageParam -> pkgName:android.playground, procName:android.playground, isFirstApp:true
2022-04-14 14:02:39.465 4447-4447/android.playground D/MainHook: handleLoadPackage: 
    java.lang.Throwable: ?
        at android.playground.MainHook.handleLoadPackage(MainHook.java:19)
        at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
        at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
        at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
        at H.afterHookedMethod(Unknown Source:104)
        at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:132)
        at LSPHooker_.getClassLoader(Unknown Source:8)
        at android.app.LoadedApk.getResources(LoadedApk.java:956)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2282)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
        at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:103)
        at LSPHooker_.handleBindApplication(Unknown Source:11)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

_Originally posted by @ryuunoakaihitomi in https://github.com/LSPosed/LSPosed/discussions/1841#discussioncomment-2564558_

**Comment by yujincheng08** [comment]
@ryuunoakaihitomi can you try this build and send the verbose log?
[LSPosed-v1.8.1-6510-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8486838/LSPosed-v1.8.1-6510-zygisk-debug.zip)

**Comment by ryuunoakaihitomi** [comment]
[LSPosed_2022-04-14T14_47_36.420.zip](https://github.com/LSPosed/LSPosed/files/8486878/LSPosed_2022-04-14T14_47_36.420.zip)

**Comment by yujincheng08** [comment]
```
[ 2022-04-14T14:45:38.908    10200:  6383:  6383 I/LSPosed-Bridge  ] Loading module android.playground from /data/app/android.playground-8_QC8eCYZ6XyTmXuTB7iJA==/base.apk
[ 2022-04-14T14:45:38.924    10200:  6383:  6383 I/LSPosed-Bridge  ]   Loading class android.playground.MainHook
[ 2022-04-14T14:45:38.928    10200:  6383:  6383 I/LSPosed-Bridge  ] Loading module android.playground from /data/app/android.playground-8_QC8eCYZ6XyTmXuTB7iJA==/base.apk
[ 2022-04-14T14:45:38.931    10200:  6383:  6383 I/LSPosed-Bridge  ]   Loading class android.playground.MainHook
```

Why your module is loaded twice???

**Comment by yujincheng08** [comment]
The problem seems to lies here:
```
[ 2022-04-14T14:43:48.800        0:  1019:  1734 D/LSPosedService  ] android.playground/10200
[ 2022-04-14T14:43:48.800        0:  1019:  1734 D/LSPosedService  ] 	android.playground
[ 2022-04-14T14:43:48.800        0:  1019:  1734 D/LSPosedService  ] 	android.playground
```

**Comment by yujincheng08** [comment]
Try this:
[LSPosed-v1.8.1-6510-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8487036/LSPosed-v1.8.1-6510-zygisk-debug.zip)

**Comment by ryuunoakaihitomi** [comment]
[LSPosed_2022-04-14T15_26_29.479.zip](https://github.com/LSPosed/LSPosed/files/8487149/LSPosed_2022-04-14T15_26_29.479.zip)

**Comment by yujincheng08** [comment]
does isFirstApplication work as expected now?

**Comment by ryuunoakaihitomi** [comment]
Yes.
