### ISSUE TITLE
[Bug] Error when adding hook to a layout repeatedly

### ISSUE THREAD

**Issue by PeanutMelonSeedBigAlmond** [LSPosed/LSPosed#1849]
### Steps to reproduce/复现步骤

1. There are multiple child views in the same layout that I want to add event listener via hook. 

    - Target layout: 

        ![image](https://user-images.githubusercontent.com/25266280/163597958-29eccc57-f51b-4f8a-9cfc-3a2f0028db06.png)

    - Code: 

        ![image](https://user-images.githubusercontent.com/25266280/163598067-c820cd73-fee2-4d14-83d1-8972256aea26.png)

2. Error log

    <details>
        <summary> Log </summary>
        <pre><code>[ 2022-04-16T00:24:13.252    10410: 29082: 29082 E/LSPosed-Bridge  ] java.lang.ClassCastException: com.example.xposed.MainHook$Hooker cannot be cast to java.lang.Comparable
	at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:320)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:188)
	at java.util.Arrays.sort(Arrays.java:1239)
	at de.robv.android.xposed.XposedBridge$CopyOnWriteSortedSet.add(Unknown Source:30)
	at android.content.res.XResources.hookLayoutInternal(Unknown Source:40)
	at android.content.res.XResources.hookLayout(Unknown Source:6)
	at android.content.res.XResources.hookLayout(Unknown Source:6)
	at com.example.xposed.MainHook.handleInitPackageResources(MainHook.kt:21)
	at de.robv.android.xposed.IXposedHookInitPackageResources$Wrapper.handleInitPackageResources(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_InitPackageResources.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at de.robv.android.xposed.XposedInit.cloneToXResources(Unknown Source:2)
	at de.robv.android.xposed.XposedInit.b(Unknown Source:0)
	at de.robv.android.xposed.XposedInit$2.afterHookedMethod(Unknown Source:34)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:132)
	at LSPHooker_.createResources(Unknown Source:20)
	at android.app.ResourcesManager.getResources(ResourcesManager.java:938)
	at android.app.LoadedApk.getResources(LoadedApk.java:1211)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2663)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2655)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6604)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:103)
	at LSPHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1300(ActivityThread.java:238)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
        </code></pre>
    </details>

### Expected behaviour/预期行为

no error log in logcat

### Actual behaviour/实际行为

error shown in logcat

### Xposed Module List/Xposed 模块列表

```shell
Test module
```

### Magisk Module List/Magisk 模块列表

```shell
Lsposed
```

### LSPosed version/LSPosed 版本

1.8.1 (6499) - Zygisk

### Android version/Android 版本

11

### Magisk version/Magisk 版本

24.3

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

```
[ 2022-04-16T00:24:13.252    10410: 29082: 29082 E/LSPosed-Bridge  ] java.lang.ClassCastException: com.example.xposed.MainHook$Hooker cannot be cast to java.lang.Comparable
	at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:320)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:188)
	at java.util.Arrays.sort(Arrays.java:1239)
	at de.robv.android.xposed.XposedBridge$CopyOnWriteSortedSet.add(Unknown Source:30)
	at android.content.res.XResources.hookLayoutInternal(Unknown Source:40)
	at android.content.res.XResources.hookLayout(Unknown Source:6)
	at android.content.res.XResources.hookLayout(Unknown Source:6)
	at com.example.xposed.MainHook.handleInitPackageResources(MainHook.kt:21)
	at de.robv.android.xposed.IXposedHookInitPackageResources$Wrapper.handleInitPackageResources(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_InitPackageResources.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at de.robv.android.xposed.XposedInit.cloneToXResources(Unknown Source:2)
	at de.robv.android.xposed.XposedInit.b(Unknown Source:0)
	at de.robv.android.xposed.XposedInit$2.afterHookedMethod(Unknown Source:34)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:132)
	at LSPHooker_.createResources(Unknown Source:20)
	at android.app.ResourcesManager.getResources(ResourcesManager.java:938)
	at android.app.LoadedApk.getResources(LoadedApk.java:1211)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2663)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2655)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6604)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:103)
	at LSPHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1300(ActivityThread.java:238)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by yujincheng08** [comment]
Try:
[LSPosed-v1.8.1-6511-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8497438/LSPosed-v1.8.1-6511-zygisk-debug.zip)

**Comment by PeanutMelonSeedBigAlmond** [comment]
> Try: [LSPosed-v1.8.1-6511-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8497438/LSPosed-v1.8.1-6511-zygisk-debug.zip)

No problem, it works.
