### ISSUE TITLE
[Bug] ANR

### ISSUE THREAD

**Issue by W-quan** [LSPosed/LSPosed#1931]
### Steps to reproduce/复现步骤

Open a mini program or webview of WeChat.

### Expected behaviour/预期行为

Open success

### Actual behaviour/实际行为

ANR

### Xposed Module List/Xposed 模块列表

```shell
null
```

### Magisk Module List/Magisk 模块列表

```shell
see log.
```

### LSPosed version/LSPosed 版本

1.8.3

### Android version/Android 版本

9

### Magisk version/Magisk 版本

23.0

### Riru version/Riru 版本

26.1.4.r522.8b379cedb5

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

***
[LSPosed_2022-05-11T15:31:55.999.zip](https://github.com/LSPosed/LSPosed/files/8667667/LSPosed_2022-05-11T15.31.55.999.zip)

"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x79945450 self=0x72eb214c00
  | sysTid=13572 nice=0 cgrp=default sched=0/0 handle=0x73711a2548
  | state=S schedstat=( 6917806366 3245692989 38108 ) utm=244 stm=447 core=0 HZ=100
  | stack=0x7fdb992000-0x7fdb994000 stackSize=8MB
  | held mutexes=
  kernel: (couldn't read /proc/self/task/13572/stack)
  native: #00 pc 000000000001f3ec  /system/lib64/libc.so (syscall+28)
  native: #01 pc 00000000000d8788  /system/lib64/libart.so (offset ab000) (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+148)
  native: #02 pc 000000000036c5a0  /system/lib64/libart.so (offset 2e8000) (art::JNI::NewStringUTF(_JNIEnv*, char const*)+460)
  native: #03 pc 0000000000020410  /system/lib64/libopenjdk.so (Java_java_io_UnixFileSystem_list0+372)
  at java.io.UnixFileSystem.list0(Native method)
  at java.io.UnixFileSystem.list(UnixFileSystem.java:303)
  at java.io.File.list(File.java:1131)
  at java.io.File.listFiles(File.java:1216)
  at ˋـ.ˏᵢ.ﹳﹶ(:-1)
  at ˋـ.ˏᵢ.ﹳﹶ(:-1)
  at ˋـ.ˏᵢ.ﹳﹶ(:-1)
  ... repeated 2 times
  at ˋـ.ˏᵢ.ʻ(:-1)
  at ˆᵎ.ⁱי.ﹳʻ(:-1)
  at ˆᵎ.ⁱי.ـᵢ(:-1)
  at ˆᵎ.ˉˎ.<init>(:-1)
  at ˆᵎ.ˋᐧ.יˎ(:-1)
  at ˆᵎ.ˋᐧ.ᵎי(:-1)
  at ˆᵎ.ˋᐧ$ﹳʻ.afterHookedMethod(:-1)
  at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(unavailable:-1)
  at LSPHooker_.attachBaseContext(LSP:-1)
  at android.app.Application.attach(Application.java:215)
  at android.app.Instrumentation.newApplication(Instrumentation.java:1122)
  at android.app.LoadedApk.makeApplication(LoadedApk.java:1065)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5988)
  at android.app.ActivityThread.access$1200(ActivityThread.java:202)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1680)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:207)
  at android.app.ActivityThread.main(ActivityThread.java:6878)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

***

**Comment by yujincheng08** [comment]
Not our problem

**Comment by W-quan** [comment]
My system offer occur ANR recently in many APPS.   I'm not sure whose problem, because i had upgrade Riru and LSPosed.
