### ISSUE TITLE
[Bug] SystemUI crash

### ISSUE THREAD

**Issue by Alexey71** [LSPosed/LSPosed#1940]
### Steps to reproduce/复现步骤

1. Install new module or update module
2. Click on notification

### Expected behaviour/预期行为

Open LSPosed

### Actual behaviour/实际行为

SystemUI restart or crash

### Xposed Module List/Xposed 模块列表

```shell
Lucky Patcher
```

### Magisk Module List/Magisk 模块列表

```shell
Zygisk - LSPosed
safetynet-fix
```

### LSPosed version/LSPosed 版本

1.8.3 (6552)

### Android version/Android 版本

Oxygen OS 11

### Magisk version/Magisk 版本

24.3 (24300)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[verbose_2022-05-14T12_03_39.223.log](https://github.com/LSPosed/LSPosed/files/8692719/verbose_2022-05-14T12_03_39.223.log)

[verbose_2022-05-14T13_10_12.231.log](https://github.com/LSPosed/LSPosed/files/8692716/verbose_2022-05-14T13_10_12.231.log)

https://user-images.githubusercontent.com/10572914/168421685-07ab9ef9-0a45-435a-a51d-9e4069086359.mp4

**Comment by yujincheng08** [comment]
I dont think you are using the debug version. And your log does not contain crash of SystemUI.

**Comment by Alexey71** [comment]
@yujincheng08 
[verbose_2022-05-14T17_56_53.208.log](https://github.com/LSPosed/LSPosed/files/8693199/verbose_2022-05-14T17_56_53.208.log)
```
Process: com.android.systemui, PID: 13429
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.UserHandle.getIdentifier()' on a null object reference
	at com.android.systemui.statusbar.phone.StatusBarNotificationActivityStarter.handleNotificationClickAfterPanelCollapsed(StatusBarNotificationActivityStarter.java:415)
	at com.android.systemui.statusbar.phone.StatusBarNotificationActivityStarter.lambda$handleNotificationClickAfterKeyguardDismissed$1(StatusBarNotificationActivityStarter.java:375)
	at com.android.systemui.statusbar.phone.StatusBarNotificationActivityStarter.lambda$handleNotificationClickAfterKeyguardDismissed$1$StatusBarNotificationActivityStarter(Unknown Source:0)
	at com.android.systemui.statusbar.phone.-$$Lambda$StatusBarNotificationActivityStarter$7mfSGy2G6exE-3cGRoA3iww8GIU.run(Unknown Source:16)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by yujincheng08** [comment]
OK. The same issue of #1872

**Comment by yujincheng08** [comment]
Wait, it's impossible...

The only place that uses `getIdentifier` is here:
![image](https://user-images.githubusercontent.com/5022927/168441599-4b21025e-32e8-4064-8af8-b69308c4216f.png)
And `getCreatorUserHandle` is NonNull:
![image](https://user-images.githubusercontent.com/5022927/168441608-bdd4796f-5328-4a80-823b-ce1d1f11b2c3.png)
