### ISSUE TITLE
[Bug] MediaTek - add shortcut NotFoundException

### ISSUE THREAD

**Issue by Stillhard** [LSPosed/LSPosed#1953]
### Steps to reproduce/复现步骤

Normal boot/reboot

### Expected behaviour/预期行为

No error

### Actual behaviour/实际行为

[ 2022-05-19T14:30:44.123        0:   658:   969 E/LSPosedService  ] add shortcut
android.content.res.Resources$NotFoundException: Drawable org.lsposed.daemon:drawable/ic_launcher with resource ID #0x7f020000
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
	at android.content.ContextWrapper.getPackageName(ContextWrapper.java:152)
	at com.mediatek.res.AsyncDrawableCache.skipPreload(AsyncDrawableCache.java:150)
	at com.mediatek.res.AsyncDrawableCache.putCacheList(AsyncDrawableCache.java:232)
	at com.mediatek.res.ResOptExtImpl.putCacheList(ResOptExtImpl.java:69)
	at android.content.res.ResourcesImpl.cacheDrawable(ResourcesImpl.java:782)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:719)
	at android.content.res.Resources.loadDrawable(Resources.java:993)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:983)
	at android.content.res.Resources.getDrawable(Resources.java:922)
	at org.lsposed.lspd.service.LSPManagerService.getIcon(LSPManagerService.java:166)
	at org.lsposed.lspd.service.LSPManagerService.getManagerIcon(LSPManagerService.java:177)
	at org.lsposed.lspd.service.LSPManagerService.createOrUpdateShortcutInternal(LSPManagerService.java:373)
	at org.lsposed.lspd.service.LSPManagerService.lambda$createOrUpdateShortcut$2(LSPManagerService.java:347)
	at org.lsposed.lspd.service.LSPManagerService$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:268)
	at android.os.HandlerThread.run(HandlerThread.java:67)
[ 2022-05-19T14:30:44.243        0:   658:   969 D/LSPosedService  ] Auto add shortcut=true

### Xposed Module List/Xposed 模块列表

```shell
None
```

### Magisk Module List/Magisk 模块列表

```shell
- f2fs_tune
- riru_lsposed
- riru_momohider
- riru-core
- safetynet-fix
```

### LSPosed version/LSPosed 版本

6560

### Android version/Android 版本

11

### Magisk version/Magisk 版本

23014

### Riru version/Riru 版本

524

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-05-19T14_31_14.481.zip](https://github.com/LSPosed/LSPosed/files/8726894/LSPosed_2022-05-19T14_31_14.481.zip)

**Comment by vvb2060** [comment]
Upload /system/framework/mediatek-framework.jar

**Comment by Stillhard** [comment]
> Upload /system/framework/mediatek-framework.jar
Here you go:
[mediatek-framework.zip](https://github.com/LSPosed/LSPosed/files/8726959/mediatek-framework.zip)

**Comment by vvb2060** [comment]
Upload system/etc/resource_preloading_black_list.txt

**Comment by Stillhard** [comment]
> Upload system/etc/resource_preloading_black_list.txt

Here you go:
[resource_preloading_black_list.txt](https://github.com/LSPosed/LSPosed/files/8727232/resource_preloading_black_list.txt)

**Comment by vvb2060** [comment]
Now we know that MTK has 3 versions of the code.

version 1: Checked if context == null
```java
    void putCacheList(long key, Drawable dr, int origResId, Context context) {
        if (isEnableFeature()) {
            Drawable.ConstantState boostCache = sDrawableCache.get(Long.valueOf(key));
            if (boostCache == null && context != null && needCacheDrawable(dr)) {
                sDrawableCache.put(Long.valueOf(key), dr.getConstantState());
                if (isDEBUG) {
                    Log.d(TAG, "putCacheList, key:" + key + ", origResId:" + origResId);
                }
                storeDrawableId(origResId, context);
            }
        }
    }

    private void storeDrawableId(int origResId, Context context) {
        SharedPreferences prefs;
        if (context == null) {
            Log.w(TAG, "storeDrawableId got the context is null, id:" + origResId + " cannot save");
        } else if (isUserUnlocked(context) && (prefs = context.getSharedPreferences(sPerfName, 0)) != null && !prefs.contains(String.valueOf(origResId))) {
            SharedPreferences.Editor editor = prefs.edit();
            editor.putInt(String.valueOf(origResId), origResId);
            editor.commit();
            if (isDEBUG) {
                Log.d(TAG, "storeDrawableId, id:" + origResId);
            }
        }
    }


```

version 2: Add processName check but forget to check the context
```java
    void putCacheList(long key, Drawable dr, int origResId, Context context) {
        Drawable.ConstantState boostCache;
        if (isEnableFeature() && !context.getApplicationInfo().processName.equals(CustomProperties.MODULE_SYSTEM) && !context.getApplicationInfo().isSystemApp()) {
            synchronized (lock) {
                boostCache = sDrawableCache.get(Long.valueOf(key));
            }
            if (boostCache == null && context != null && needCacheDrawable(dr)) {
                if (isPreloaded) {
                    synchronized (lock) {
                        sDrawableCache.put(Long.valueOf(key), dr.getConstantState());
                    }
                    if (isDEBUG) {
                        Log.d(TAG, "putCacheList, put cache, size:" + sDrawableCache.size());
                    }
                }
                if (isDEBUG) {
                    Log.d(TAG, "putCacheList, key:" + key + ", origResId:" + origResId);
                }
                storeDrawableId(origResId, context);
            }
        }
    }

```

version 3: Add context check again
```java
    // Read from system/etc/resource_preloading_black_list.txt
    private static ArrayMap<String, Integer> sPreloadList = new ArrayMap<>();


    boolean skipPreload(Context context) {
        return context == null || sPreloadList.containsKey(context.getPackageName());
    }


    void putCacheList(long key, Drawable dr, int origResId, Context context) {
        Drawable.ConstantState boostCache;
        if (!isEnableFeature() || skipPreload(context)) {
            return;
        }
        if (context == null || (!context.getApplicationInfo().processName.equals(CustomProperties.MODULE_SYSTEM) && !context.getApplicationInfo().isSystemApp())) {
            synchronized (lock) {
                boostCache = sDrawableCache.get(Long.valueOf(key));
            }
            if (boostCache == null && context != null && needCacheDrawable(dr)) {
                if (isPreloaded) {
                    synchronized (lock) {
                        sDrawableCache.put(Long.valueOf(key), dr.getConstantState());
                    }
                    if (isDEBUG) {
                        Log.d(TAG, "putCacheList, put cache, size:" + sDrawableCache.size());
                    }
                }
                if (isDEBUG) {
                    Log.d(TAG, "putCacheList, key:" + key + ", origResId:" + origResId);
                }
                storeDrawableId(origResId, context);
            }
        }
    }

```

**Comment by vvb2060** [comment]
#1951 fixed version 2, but crashed the others.
