### ISSUE TITLE
[Bug] Some conflict with installed app

### ISSUE THREAD

**Issue by techIndia-hacker** [LSPosed/LSPosed#2015]
### Steps to reproduce/复现步骤

Install rar app and lucky patcher. Enable lucky patcher in lsposed and tick rar app.

Then error love appear in lsposed and also the hook doesn't work

### Expected behaviour/预期行为

Play Store emulation should work

### Actual behaviour/实际行为

Play Store emulation not working 

### Xposed Module List/Xposed 模块列表

```shell
Lucky patcher, gravity box R.
```

### Magisk Module List/Magisk 模块列表

```shell
Lsposed,
```

### LSPosed version/LSPosed 版本

6552

### Android version/Android 版本

11

### Magisk version/Magisk 版本

25.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-06-30T10_56_38.668.zip](https://github.com/LSPosed/LSPosed/files/9016640/LSPosed_2022-06-30T10_56_38.668.zip)

**Comment by techIndia-hacker** [comment]
[ 2022-06-28T00:01:23.203    10250:  2971:  2971 E/LSPosed-Bridge  ] java.lang.IllegalArgumentException: Unknown component: ComponentInfo{ru.ygzdkrbh.hlkzunaqa/com.google.android.finsky.billing.iab.InAppBillingService}
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2377)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.content.pm.IPackageManager$Stub$Proxy.getComponentEnabledSetting(IPackageManager.java:6845)
	at android.app.ApplicationPackageManager.getComponentEnabledSetting(ApplicationPackageManager.java:2795)
	at com.xposed.XSupport.Ê»(XSupport.java:1418)
	at com.xposed.XSupport$40.beforeHookedMethod(XSupport.java:221)
	at XMCDohnoU.pQxRHvaLjtNA.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.bindService(Unknown Source:21)
	at com.android.billingclient.api.b.f(com.android.billingclient:billing@@4.0.0:24)
	at com.rarlab.rar.RarPurchase.init(RarPurchase.java:8)
	at com.rarlab.rar.MainActivity.onCreate(MainActivity.java:12)
	at android.app.Activity.performCreate(Activity.java:8006)
	at android.app.Activity.performCreate(Activity.java:7990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3584)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.PackageManagerService.getComponentEnabledSetting(PackageManagerService.java:22065)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3236)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4513)
	at android.os.Binder.execTransactInternal(Binder.java:1165)
	at android.os.Binder.execTransact(Binder.java:1134)

[ 2022-06-28T00:01:23.205    10250:  2971:  2971 E/LSPosed-Bridge  ] java.lang.IllegalArgumentException: Unknown component: ComponentInfo{ru.ygzdkrbh.hlkzunaqa/com.google.android.finsky.billing.iab.InAppBillingService}
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2377)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.content.pm.IPackageManager$Stub$Proxy.getComponentEnabledSetting(IPackageManager.java:6845)
	at android.app.ApplicationPackageManager.getComponentEnabledSetting(ApplicationPackageManager.java:2795)
	at com.xposed.XSupport.Ê»(XSupport.java:1418)
	at com.xposed.XSupport$40.beforeHookedMethod(XSupport.java:221)
	at XMCDohnoU.pQxRHvaLjtNA.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.bindService(Unknown Source:21)
	at com.android.billingclient.api.b.f(com.android.billingclient:billing@@4.0.0:24)
	at com.rarlab.rar.RarPurchase.init(RarPurchase.java:8)
	at com.rarlab.rar.MainActivity.onCreate(MainActivity.java:12)
	at android.app.Activity.performCreate(Activity.java:8006)
	at android.app.Activity.performCreate(Activity.java:7990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3584)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by yujincheng08** [comment]
It's not our issue.

**Comment by techIndia-hacker** [comment]
Is this a lsposed bug or of lucky patcher?

**Comment by yujincheng08** [comment]
It's not a LSPosed bug.

**Comment by techIndia-hacker** [comment]
Ok thanks

**Comment by techIndia-hacker** [comment]
But have u at least read the module logs that I copied

**Comment by yujincheng08** [comment]
yes

**Comment by techIndia-hacker** [comment]
Ok...
