### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ACGTime** [LSPosed/LSPosed#2041]
### Steps to reproduce/复现步骤

无法激活或未安装Lsposed

### Expected behaviour/预期行为

Lsposed（非寄生）管理器出现未知错误/闪退

### Actual behaviour/实际行为

Lsposed（非寄生）管理器出现未知错误/闪退

### Xposed Module List/Xposed 模块列表

```shell
无
```

### Magisk Module List/Magisk 模块列表

```shell
riru26.1.6r527
riru-Enhanced mode for Storage lsolation
ruri1.8.3
```

### LSPosed version/LSPosed 版本

6552

### Android version/Android 版本

Oxygen OS 9.0.3

### Magisk version/Magisk 版本

23.0

### Riru version/Riru 版本

v26.1.6.r527

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Build version: 1.6.5 (6272) 
Current date: 2022-07-20T03:54:04.252 
Device: OnePlus ONEPLUS A5010 
Fingerprint: OnePlus/OnePlus5T/OnePlus5T:9/PKQ1.180716.001/1901182129:user/release-keys 
 
SDK: 28 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.lsposed.manager/org.lsposed.manager.ui.activity.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3037)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6863)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at S1.A(Unknown Source:35)
	at S1.m(Unknown Source:0)
	at z1.setContentView(Unknown Source:4)
	at org.lsposed.manager.ui.activity.MainActivity.onCreate(Unknown Source:5)
	at android.app.Activity.performCreate(Activity.java:7149)
	at android.app.Activity.performCreate(Activity.java:7140)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3017)
	... 11 more

**Comment by yujincheng08** [comment]
Not debug ver
