### ISSUE TITLE
[Bug] Zygisk crashed when hooking `android.content.Intent`

### ISSUE THREAD

**Issue by lz233** [LSPosed/LSPosed#2070]
### Steps to reproduce/复现步骤

just write some code which hooks Intent.

check it [here](https://github.com/lz233/Tarnhelm/blob/c8cd4f1cd8de795b31ff3bab2eb37373f86ce207/app/src/main/java/cn/ac/lz233/tarnhelm/xposed/module/Android.kt#L91).

```kotlin
Intent::class.java.hookBeforeAllMethods("createChooser") { param ->
                LogUtil._d("createChooser")
                val target = param.args[1] as Intent
                if (!(ModuleBridgeHelper.isBridgeAvailable && ModuleBridgeHelper.isBridgeActive())) {
                    startModuleAppProcess()
                    ModuleBridgeHelper.bindBridgeService()
                }
                ModuleBridgeHelper.bridge?.let {
                    target.putExtra(Intent.EXTRA_SUBJECT, it.doTarnhelms(target.getStringExtra(Intent.EXTRA_SUBJECT)))
                    target.putExtra(Intent.EXTRA_TEXT, it.doTarnhelms(target.getStringExtra(Intent.EXTRA_TEXT)))
                    param.args[1] = target
                }
            }
```

### Expected behaviour/预期行为

The hooker would be work well, and magisk too.

### Actual behaviour/实际行为

Zygisk crashed and LSPosed not working.

<img width="552" alt="image" src="https://user-images.githubusercontent.com/32504382/184365921-36d6f07a-5539-4f14-935f-de84ad6f7134.png">

### Xposed Module List/Xposed 模块列表

```shell
Mi Translator + (moe.lz233.mitranslator)
Tarnhelm (cn.ac.lz233.tarnhelm) (where the problem occurs)
```

### Magisk Module List/Magisk 模块列表

```shell
Zygisk - LSPosed
```

### LSPosed version/LSPosed 版本

1.8.3 (6596)

### Android version/Android 版本

8.1

### Magisk version/Magisk 版本

25.2 (25200)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[magisk_log_2022-08-12T21.30.49.log](https://github.com/LSPosed/LSPosed/files/9316742/magisk_log_2022-08-12T21.30.49.log)
[bugreport-Mitranslator-O11019-2022-08-12-21-47-54.zip](https://github.com/LSPosed/LSPosed/files/9316745/bugreport-Mitranslator-O11019-2022-08-12-21-47-54.zip)

**Comment by yujincheng08** [comment]
```
08-12 21:26:42.144  1000   826   826 E AndroidRuntime: kotlin.UninitializedPropertyAccessException: lateinit property context has not been initialized
08-12 21:26:42.144  1000   826   826 E AndroidRuntime: 	at cn.ac.lz233.tarnhelm.App$Companion.getContext(App.kt:20)
08-12 21:26:42.144  1000   826   826 E AndroidRuntime: 	at cn.ac.lz233.tarnhelm.util.LogUtil.toast$lambda-0(LogUtil.kt:17)
08-12 21:26:42.144  1000   826   826 E AndroidRuntime: 	at cn.ac.lz233.tarnhelm.util.LogUtil.$r8$lambda$wTlSU7pIS16oqKWMo0vKo43l2A0(Unknown Source:0)
08-12 21:26:42.144  1000   826   826 E AndroidRuntime: 	at cn.ac.lz233.tarnhelm.util.LogUtil$$ExternalSyntheticLambda0.run(Unknown Source:2)
08-12 21:26:42.144  1000   826   826 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
08-12 21:26:42.144  1000   826   826 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-12 21:26:42.144  1000   826   826 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
08-12 21:26:42.144  1000   826   826 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:439)
08-12 21:26:42.144  1000   826   826 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:280)
08-12 21:26:42.144  1000   826   826 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-12 21:26:42.144  1000   826   826 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
08-12 21:26:42.144  1000   826   826 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)
```
