### ISSUE TITLE
[Bug][SDK 33] Classloader fails to load the class completely

### ISSUE THREAD

**Issue by siavash79** [LSPosed/LSPosed#2088]
### Steps to reproduce/复现步骤

1. Try a normal hook to a method from an open-source app (using hookAllMethods for example)
2. The unhook collection returned has size of 0
(Same issue is applicable to callMethod as well)

Example code:

```
Class<?> BrightnessControllerClass = findClass("com.android.systemui.settings.brightness.BrightnessController", lpparam.classLoader);
hookAllConstructors(BrightnessControllerClass ,  new XC_MethodHook() {
                @Override
                protected void afterHookedMethod(MethodHookParam param) throws Throwable {
            callMethod(mBrightnessController, "checkRestrictionAndSetEnabled"); //Lsposed error: NoSuchMethod
           }
});
```

### Expected behaviour/预期行为

Classloader is expected to load the class completely with all the methods and fields defined in the original class

For the example below:

https://cs.android.com/android/platform/superproject/+/master:frameworks/base/packages/SystemUI/src/com/android/systemui/tuner/TunerServiceImpl.java?q=TunerServiceImpl

### Actual behaviour/实际行为

```
W/System.err: java.lang.NoSuchMethodError: com.android.systemui.tuner.TunerServiceImpl#addTunable(com.android.systemui.qs.QuickQSPanel,java.lang.String)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at de.robv.android.xposed.XposedHelpers.lambda$findMethodBestMatch$5(XposedHelpers.java:565)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at de.robv.android.xposed.XposedHelpers$$ExternalSyntheticLambda8.get(Unknown Source:2)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at java.util.Optional.orElseThrow(Optional.java:404)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:565)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:575)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1454)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at sh.siava.AOSPMods.systemui.BrightnessSlider.makeQQSBrightness(BrightnessSlider.java:108)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at sh.siava.AOSPMods.systemui.BrightnessSlider.dataCollected(BrightnessSlider.java:63)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at sh.siava.AOSPMods.systemui.BrightnessSlider.access$100(BrightnessSlider.java:30)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at sh.siava.AOSPMods.systemui.BrightnessSlider$4.afterHookedMethod(BrightnessSlider.java:185)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:484)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at LSPHooker_.constructor(Unknown Source:66)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at com.android.systemui.qs.QSPanelController_Factory.get(QSPanelController_Factory.java:145)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at dagger.internal.DoubleCheck.get(DoubleCheck.java:13)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at com.google.android.systemui.dagger.DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleSysUIComponentImpl$QSFragmentComponentImpl.getQSPanelController(DaggerSysUIGoogleGlobalRootComponent.java:2)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at com.android.systemui.qs.QSFragment.onViewCreated(QSFragment.java:6)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1313)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3009)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at android.app.FragmentController.dispatchStart(FragmentController.java:196)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at com.android.systemui.fragments.FragmentHostManager.createFragmentHost(FragmentHostManager.java:48)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at com.android.systemui.fragments.FragmentHostManager.reloadFragments(FragmentHostManager.java:37)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at com.android.systemui.screenshot.ScreenshotController$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:144)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:942)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at android.os.Looper.loopOnce(Looper.java:201)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at android.os.Looper.loop(Looper.java:288)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7898)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
2022-08-23 15:16:34.619 11037-11037/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Xposed Module List/Xposed 模块列表

```shell
com.android.systemui:fgservices/10206
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPrefs
		sh.siava.AOSPMods.AOSPMods
		sh.siava.AOSPMods.ResourceManager
com.google.android.apps.nexuslauncher/10192
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPrefs
		sh.siava.AOSPMods.AOSPMods
		sh.siava.AOSPMods.ResourceManager
com.android.phone/1001
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPrefs
		sh.siava.AOSPMods.AOSPMods
		sh.siava.AOSPMods.ResourceManager
com.android.systemui:tuner/10206
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPrefs
		sh.siava.AOSPMods.AOSPMods
		sh.siava.AOSPMods.ResourceManager
com.android.systemui:sweetsweetdesserts/10206
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPrefs
		sh.siava.AOSPMods.AOSPMods
		sh.siava.AOSPMods.ResourceManager
com.android.systemui/10206
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPrefs
		sh.siava.AOSPMods.AOSPMods
		sh.siava.AOSPMods.ResourceManager
com.google.android.packageinstaller/10061
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPrefs
		sh.siava.AOSPMods.AOSPMods
		sh.siava.AOSPMods.ResourceManager
com.android.systemui:screenshot/10206
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPrefs
		sh.siava.AOSPMods.AOSPMods
		sh.siava.AOSPMods.ResourceManager
sh.siava.AOSPMods/10398
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPrefs
		sh.siava.AOSPMods.AOSPMods
		sh.siava.AOSPMods.ResourceManager
```

### Magisk Module List/Magisk 模块列表

```shell
AOSPMods
Enablesoli
safetynet-fix
zygisk_lsposed
```

### LSPosed version/LSPosed 版本

LSPosed-v1.8.3-6599-zygisk-debug - Older builds have the same behavior

### Android version/Android 版本

13 SDK 33 - Pixel Stock

### Magisk version/Magisk 版本

25.2 (25200)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [x] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-08-23T13_49_11.979037.zip](https://github.com/LSPosed/LSPosed/files/9401859/LSPosed_2022-08-23T13_49_11.979037.zip)

**Comment by yujincheng08** [comment]
Classloader will load all methods. No one can load a class partially.

**Comment by siavash79** [comment]
@yujincheng08 
This is the source code:

https://cs.android.com/android/platform/superproject/+/master:frameworks/base/packages/SystemUI/src/com/android/systemui/settings/brightness/BrightnessController.java?q=BrightnessController

This is the dump from Lsposed classloader:

```
2022-08-23 16:50:44.481 20568-20568/? I/LSPosed-Bridge: ------------
2022-08-23 16:50:44.483 20568-20568/? I/LSPosed-Bridge: Class: com.android.systemui.settings.brightness.BrightnessController
2022-08-23 16:50:44.483 20568-20568/? I/LSPosed-Bridge: extends: java.lang.Object
2022-08-23 16:50:44.483 20568-20568/? I/LSPosed-Bridge: Methods:
2022-08-23 16:50:44.484 20568-20568/? I/LSPosed-Bridge: -$$Nest$mupdateSlider - void - 3
2022-08-23 16:50:44.484 20568-20568/? I/LSPosed-Bridge: 		com.android.systemui.settings.brightness.BrightnessController
2022-08-23 16:50:44.484 20568-20568/? I/LSPosed-Bridge: 		float
2022-08-23 16:50:44.484 20568-20568/? I/LSPosed-Bridge: 		boolean
2022-08-23 16:50:44.484 20568-20568/? I/LSPosed-Bridge: onChanged - void - 3
2022-08-23 16:50:44.484 20568-20568/? I/LSPosed-Bridge: 		int
2022-08-23 16:50:44.484 20568-20568/? I/LSPosed-Bridge: 		boolean
2022-08-23 16:50:44.484 20568-20568/? I/LSPosed-Bridge: 		boolean
2022-08-23 16:50:44.484 20568-20568/? I/LSPosed-Bridge: setMirror - void - 1
2022-08-23 16:50:44.484 20568-20568/? I/LSPosed-Bridge: 		com.android.systemui.statusbar.policy.BrightnessMirrorController
2022-08-23 16:50:44.484 20568-20568/? I/LSPosed-Bridge: Fields:
2022-08-23 16:50:44.484 20568-20568/? I/LSPosed-Bridge: 		mAutomatic-boolean
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mBackgroundHandler-android.os.Handler
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mBrightnessMax-float
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mBrightnessMin-float
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mBrightnessObserver-com.android.systemui.settings.brightness.BrightnessController$BrightnessObserver
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mContext-android.content.Context
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mControl-com.android.systemui.settings.brightness.ToggleSlider
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mControlValueInitialized-boolean
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mDisplayId-int
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mDisplayListener-com.android.systemui.settings.brightness.BrightnessController$1
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mDisplayManager-android.hardware.display.DisplayManager
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mExternalChange-boolean
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mHandler-com.android.systemui.settings.brightness.BrightnessController$7
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mIsVrModeEnabled-boolean
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mListening-boolean
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mMaximumBacklightForVr-float
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mMinimumBacklightForVr-float
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mSliderAnimator-android.animation.ValueAnimator
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mStartListeningRunnable-com.android.systemui.settings.brightness.BrightnessController$2
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mStopListeningRunnable-com.android.systemui.settings.brightness.BrightnessController$3
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mUpdateModeRunnable-com.android.systemui.settings.brightness.BrightnessController$4
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mUpdateSliderRunnable-com.android.systemui.settings.brightness.BrightnessController$5
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mUserTracker-com.android.systemui.settings.brightness.BrightnessController$8
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mVrManager-android.service.vr.IVrManager
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		mVrStateCallbacks-com.android.systemui.settings.brightness.BrightnessController$6
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		BRIGHTNESS_FOR_VR_FLOAT_URI-android.net.Uri
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: 		BRIGHTNESS_MODE_URI-android.net.Uri
2022-08-23 16:50:44.485 20568-20568/? I/LSPosed-Bridge: End dump
```

**Comment by siavash79** [comment]
I would like to request for the issue to be reopened and (at least) the logs are studied

**Comment by yujincheng08** [comment]
still not get ur point. all look good to me.

**Comment by siavash79** [comment]
Source code has these methods:
setBrightness
updateVrMode
updateSlider
animateSliderTo
checkRestrictionAndSetEnabled
onChanged
unregisterCallbacks
registerCallbacks
hideSlider
showSlider

at least 10 methods. Classloader dump shows 2 methods. In Android 12, all the methods are present

**Comment by yujincheng08** [comment]
I guess your points are that the modules' classloader cannot access hidden apis?

https://developer.android.com/guide/app-compatibility/restrictions-non-sdk-interfaces

Please check the disappeared methods are hidden apis or not.

**Comment by siavash79** [comment]
> I guess your points are that the modules' classloader cannot access hidden apis?
> 
> https://developer.android.com/guide/app-compatibility/restrictions-non-sdk-interfaces
> 
> Please check the disappeared methods are hidden apis or not.

I downloaded the list and checked. The answer is no: my disappeared methods are not included in the hidden api list

**Comment by siavash79** [comment]
@yujincheng08 I also discussed the same case in telegram group and one of the admins gave me a warning

**Comment by vvb2060** [comment]
SystemUI is an app, it will enable R8

**Comment by yujincheng08** [comment]
Then they are inlined. Dont rely on the source code. Dump its dex instead.

**Comment by siavash79** [comment]
R8: Can you please elaborate? I didn't have such problem in 12 with same classes and same hooks

**Comment by yujincheng08** [comment]
@siavash79 You should know what r8 is. It's not invertable.

**Comment by yujincheng08** [comment]
> Constructor can't get inlined

They can be

**Comment by siavash79** [comment]
Still: is it possible to please study my case? There might be a problem with reading the dex files

**Comment by vvb2060** [comment]
Android app developers should know R8, you should search, and learn to become an Android developer.

**Comment by canyie** [comment]
https://developer.android.com/studio/build/shrink-code

**Comment by yujincheng08** [comment]
![image](https://user-images.githubusercontent.com/5022927/186161971-530d5b08-2174-44c9-96b5-4c8ab29c7dad.png)

About telegram: you didn't provide codes so you deserve.
