### ISSUE TITLE
[Bug]  LSPosed Manager  Crashed BUG

### ISSUE THREAD

**Issue by smilencecc** [LSPosed/LSPosed#2124]
### Steps to reproduce/复现步骤

更新LSPosed框架之后出现错误

### Expected behaviour/预期行为

更新LSPosed框架之后正常启动

### Actual behaviour/实际行为

更新LSPosed框架之后出现错误

### Xposed Module List/Xposed 模块列表

```shell
AD快消
Atuo Skip
VCAM
要你命三千
微x
QX
```

### Magisk Module List/Magisk 模块列表

```shell
Zygisk-LSPosed
```

### LSPosed version/LSPosed 版本

5803

### Android version/Android 版本

8.1.0

### Magisk version/Magisk 版本

25200

### Riru version/Riru 版本

N/A 1.8.4

### Version requirement/版本要求

- [ ] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Build version: v1.4.7 (5803) 
Current date: 2022-09-15 13:03:53 
Device: Xiaomi Redmi 5 Plus 
Fingerprint: xiaomi/vince/vince:8.1.0/OPM1.171019.019/9.3.21:user/release-keys 
 
SDK: 27 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.lsposed.manager/org.lsposed.manager.ui.activity.MainActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x7f11002c
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
 at android.app.ActivityThread.-wrap11(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:176)
 at android.app.ActivityThread.main(ActivityThread.java:6651)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:54
![1](https://user-images.githubusercontent.com/77428601/190319446-71e63e11-3aac-4b35-aaae-ef5334e6b1a8.png)

**Comment by Howard20181** [comment]
Uninstall the manager and use the parasitic manager.

**Comment by smilencecc** [comment]
> 卸载管理器并使用寄生管理器。

谢谢   已经解决了
