### ISSUE TITLE
[Bug] Crashing after latest update

### ISSUE THREAD

**Issue by reloxx13** [LSPosed/LSPosed#2150]
### Steps to reproduce/复现步骤

Open lsposed

### Expected behaviour/预期行为

Opening

### Actual behaviour/实际行为

Crashing

### Xposed Module List/Xposed 模块列表

```shell
How do i know when it does not open?
```

### Magisk Module List/Magisk 模块列表

```shell
SafetyNetFix, lsposed
```

### LSPosed version/LSPosed 版本

1.8.4

### Android version/Android 版本

11

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Build version: v1.5.1 (5898) 
Current date: 2022-10-01 10:24:28 
Device: Xiaomi Mi 9T 
Fingerprint: Xiaomi/davinci/davinci:11/RKQ1.200826.002/V12.1.4.0.RFJMIXM:user/release-keys 
 
SDK: 30 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.lsposed.manager/org.lsposed.manager.ui.activity.MainActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x7f110029
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3501)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3661)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7876)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f110029
	at android.content.res.Resources.getText(Resources.java:459)
	at android.content.res.MiuiResources.getText(MiuiResources.java:97)
	at android.content.Context.getText(Context.java:641)
	at android.app.Activity.setTitle(Activity.java:6904)
	at by.onCreate(SourceFile:6)
	at Ll.onCreate(SourceFile:6)
	at g4.onCreate(Unknown Source:0)
	at org.lsposed.manager.ui.activity.MainActivity.onCreate(Unknown Source:12)
	at android.app.Activity.performCreate(Activity.java:8093)
	at android.app.Activity.performCreate(Activity.java:8067)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3474)
	... 11 more

**Comment by yujincheng08** [comment]
https://t.me/LSPosed/203

**Comment by reloxx13** [comment]
> https://t.me/LSPosed/203

Ill try reinstalling.

Add this info to the release note oon github releases page
