### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by StarryDreamm** [LSPosed/LSPosed#2152]
### Steps to reproduce/复现步骤

lsp版本从「1.8.3（6552）zygisk」更新至1.8.4
重启之后打开lsp管理器，出现manager crashed报错提示

### Expected behaviour/预期行为

打开LSP管理器，进入模块管理

### Actual behaviour/实际行为

打开lsp管理器，出现manager crashed报错提示

### Xposed Module List/Xposed 模块列表

```shell
对话框取消
微博助手
微x模块
闲鱼猪手小鸽子
要你命三千
油管助手
知了
Flyme助手
fuck coolapk
小菜豆
qnotified
QQ瘦身
QX模块
TMeo
TSBattery
XAutoDaily
XQ_Crystal
```

### Magisk Module List/Magisk 模块列表

```shell
FUCK-SHIT-FILE
Shamiko
systemless hosts
wifi boding
zygisk-lsposed
zygisk-指纹支付-微信
开机动画第二屏
控制中心莫兰迪色系
自助神仙救砖
```

### LSPosed version/LSPosed 版本

1.8.4(6609)

### Android version/Android 版本

11

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Build version: v1.4.7 (5803) 
Current date: 2022-10-02 19:03:11 
Device: Meizu 17 
Fingerprint: meizu/meizu_17_N_CN/meizu17:11/QKQ1.200223.002/1618923211:user/release-keys 
 
SDK: 30 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.lsposed.manager/org.lsposed.manager.ui.activity.MainActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x7f11002c
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3505)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3657)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2106)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7838)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f11002c
	at android.content.res.Resources.getText(Resources.java:454)
	at android.content.Context.getText(Context.java:644)
	at android.app.Activity.setTitle(Activity.java:6847)
	at by.onCreate(SourceFile:6)
	at Ll.onCreate(SourceFile:6)
	at g4.onCreate(Unknown Source:0)
	at org.lsposed.manager.ui.activity.MainActivity.onCreate(Unknown Source:12)
	at android.app.Activity.performCreate(Activity.java:8012)
	at android.app.Activity.performCreate(Activity.java:7996)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1317)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3478)
	... 11 more

**Comment by vvb2060** [comment]
卸载管理器app，重启设备后按照提示添加主屏幕快捷方式
