### ISSUE TITLE
[تعطل المدير] 

### ISSUE THREAD

**Issue by M5TF4** [LSPosed/LSPosed#2155]
### Steps to reproduce/复现步骤

الخروج عند محاولة تفعيل/تعديل الوحدة. 
![Screenshot_٢٠٢٢١٠٠٤-٠٩٢٣٢٣_Shell](https://user-images.githubusercontent.com/100369761/193749390-e42555fd-77d4-4c1f-b56b-78b012f9d233.jpg)
![Screenshot_٢٠٢٢١٠٠٤-٠٩٢٣٣٨_Shell](https://user-images.githubusercontent.com/100369761/193749396-4a735b4e-1e64-41f7-b3cb-d33ea92df379.jpg)
![Screenshot_٢٠٢٢١٠٠٤-٠٩٢٣٤٥_One UI Home](https://user-images.githubusercontent.com/100369761/193749399-1f867ecd-adc0-444a-869c-f333d46cf8e4.jpg)

### Expected behaviour/预期行为

الدخول الى اعدادات الوحدة. 

### Actual behaviour/实际行为

الخروج المفاجأة.

### Xposed Module List/Xposed 模块列表

```shell
I dont know what is this.
```

### Magisk Module List/Magisk 模块列表

```shell
I dont know what is this.
```

### LSPosed version/LSPosed 版本

1.8.4

### Android version/Android 版本

11

### Magisk version/Magisk 版本

25.2 (25200)

### Riru version/Riru 版本

No Riru... Zygisk

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Build version: 1.8.0 (٦٤٨٢) 
Current date: 2022-10-04T09:19:57.487 
Device: Samsung SM-A307FN 
Fingerprint: samsung/a30sxx/a30s:11/RP1A.200720.012/A307FNXXU2CUJ2:user/release-keys 
 
SDK: 30 
 
Stack trace:  
java.util.UnknownFormatConversionException: Conversion = 'End of String'
	at java.util.Formatter$FormatSpecifierParser.peek(Formatter.java:2642)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2603)
	at java.util.Formatter.parse(Formatter.java:2558)
	at java.util.Formatter.format(Formatter.java:2505)
	at java.util.Formatter.format(Formatter.java:2459)
	at java.lang.String.format(String.java:2911)
	at android.content.res.Resources.getString(Resources.java:630)
	at android.content.Context.getString(Context.java:665)
	at gu.l(SourceFile:4)
	at jv.m(SourceFile:2)
	at Yq.c(SourceFile:4)
	at E7.l(SourceFile:2)
	at Yq.m(Unknown Source:0)
	at Yq.c(SourceFile:4)
	at mr.j(SourceFile:91)
	at wk.c(SourceFile:3)
	at androidx.recyclerview.widget.LinearLayoutManager.g1(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.T0(SourceFile:2)
	at androidx.recyclerview.widget.LinearLayoutManager.j0(SourceFile:19)
	at androidx.recyclerview.widget.RecyclerView.w(Unknown Source:66)
	at androidx.recyclerview.widget.RecyclerView.u(SourceFile:6)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:2)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(Unknown Source:58)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at Ch.t(SourceFile:8)
	at gB.h(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:4)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(Unknown Source:61)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.s(SourceFile:15)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:4)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1227)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4260)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3695)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:744)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by M5TF4** [comment]
LSPosed It comes out suddenly.

في الثلاثاء، ٤ تشرين الأول ٢٠٢٢ ٩:٤٠ ص LoveSy ***@***.***>
كتب:
