### ISSUE TITLE
[Feature Request] Indication for updated XPosed module(s)

### ISSUE THREAD

**Issue by xerta555** [LSPosed/LSPosed#2156]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Hi

Adding an indication for module(s) in modules tab which have have been updated like in the Magisk Manager app would be great.

Actually, the LPosed app create a notification to notify the user that a module require a device restart.
But, if for any reason, the final user forget the notification that he have deleted or he have completly disable notifications on his device, adding a visual indication that a reboot is required to apply the new changes for a module(s) would be interesting.

It seems to me from memory, that the Xposed Installer application from rovo already had this functionality in some way. The Magisk manager already has this feature.

Thx in advance.
Have a good day.

### Describe the solution you'd like/描述你想要的解决方案

Add an update icon indication for each xposed module(s) which need a restart of the device.

**Comment by alwadi711** [comment]
Build version: 1.8.2 (٦٥١٩) 
Current date: 2022-10-05T13:00:58.136181 
Device: Samsung SM-G998B 
Fingerprint: samsung/p3sxxx/p3s:12/SP1A.210812.016/G998BXXU5CVGB:user/release-keys 
 
SDK: 31 
 
Stack trace:  
java.util.UnknownFormatConversionException: Conversion = 'End of String'
	at java.util.Formatter$FormatSpecifierParser.peek(Formatter.java:2647)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2608)
	at java.util.Formatter.parse(Formatter.java:2563)
	at java.util.Formatter.format(Formatter.java:2510)
	at java.util.Formatter.format(Formatter.java:2464)
	at java.lang.String.format(String.java:3644)
	at android.content.res.Resources.getString(Resources.java:627)
	at android.content.Context.getString(Context.java:726)
	at gu.l(SourceFile:4)
	at jv.m(SourceFile:2)
	at Yq.c(SourceFile:4)
	at E7.l(SourceFile:2)
	at Yq.m(Unknown Source:0)
	at Yq.c(SourceFile:4)
	at mr.j(SourceFile:91)
	at wk.c(SourceFile:3)
	at androidx.recyclerview.widget.LinearLayoutManager.g1(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.T0(SourceFile:2)
	at androidx.recyclerview.widget.LinearLayoutManager.j0(SourceFile:19)
	at androidx.recyclerview.widget.RecyclerView.w(Unknown Source:66)
	at androidx.recyclerview.widget.RecyclerView.u(SourceFile:6)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:2)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(Unknown Source:58)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at Ch.t(SourceFile:8)
	at gB.h(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:4)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(Unknown Source:61)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.s(SourceFile:15)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:4)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1331)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4609)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4031)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2919)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10491)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by WAL2007EED** [comment]
Build version: 1.8.4 (٦٦٠٩) 
Current date: 2022-11-11T20:21:05.538749 
Device: Samsung SM-G998B 
Fingerprint: samsung/p3sxxx/p3s:13/TP1A.220624.014/G998BXXU5DVJC:user/release-keys 
 
SDK: 33 
 
Stack trace:  
java.util.UnknownFormatConversionException: Conversion = 'End of String'
	at java.util.Formatter$FormatSpecifierParser.peek(Formatter.java:2647)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2608)
	at java.util.Formatter.parse(Formatter.java:2563)
	at java.util.Formatter.format(Formatter.java:2510)
	at java.util.Formatter.format(Formatter.java:2464)
	at java.lang.String.format(String.java:3644)
	at android.content.res.Resources.getString(Resources.java:630)
	at android.content.Context.getString(Context.java:782)
	at gu.l(SourceFile:4)
	at jv.m(SourceFile:2)
	at Yq.c(SourceFile:4)
	at E7.l(SourceFile:2)
	at Yq.m(Unknown Source:0)
	at Yq.c(SourceFile:4)
	at mr.j(SourceFile:91)
	at wk.c(SourceFile:3)
	at androidx.recyclerview.widget.LinearLayoutManager.g1(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.T0(SourceFile:2)
	at androidx.recyclerview.widget.LinearLayoutManager.j0(SourceFile:19)
	at androidx.recyclerview.widget.RecyclerView.w(Unknown Source:66)
	at androidx.recyclerview.widget.RecyclerView.u(SourceFile:6)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:2)
	at android.view.View.layout(View.java:24958)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(Unknown Source:58)
	at android.view.View.layout(View.java:24958)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24958)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at Ch.t(SourceFile:8)
	at gB.h(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:4)
	at android.view.View.layout(View.java:24958)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24958)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24958)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(Unknown Source:61)
	at android.view.View.layout(View.java:24958)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.s(SourceFile:15)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:4)
	at android.view.View.layout(View.java:24958)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24958)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24958)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24958)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24958)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1418)
	at android.view.View.layout(View.java:24958)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4787)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4115)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2991)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10665)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:852)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Bug

**Comment by xerta555** [comment]
You closed as not planned but what have you do so in https://github.com/LSPosed/LSPosed/pull/2633 ?
