### ISSUE TITLE
[Bug] in android API Level 31 and above, is Lsposed support android 12 ?

### ISSUE THREAD

**Issue by MML-Pro** [LSPosed/LSPosed#2165]
### Steps to reproduce/复现步骤

I just upgraded my phone from android 11 to android 12 and I got this error after I installed LSPosed when I tried to enable any module

https://i.imgur.com/vGghbuX.jpg

### Expected behaviour/预期行为

Enabled the Module normally!

### Actual behaviour/实际行为

Build version: v1.5.3 (5984) 
Current date: 2022-10-08T20:17:19.880 
Device: Xiaomi MI 8 Lite 
Fingerprint: Xiaomi/aosp_platina/platina:12/SQ3A.220705.004/1661790196:user/release-keys 
 
SDK: 32 
 
Stack trace:  
java.util.UnknownFormatConversionException: Conversion = 'End of String'
 at java.util.Formatter$FormatSpecifierParser.peek(Formatter.java:2642)
 at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2603)
 at java.util.Formatter.parse(Formatter.java:2558)
 at java.util.Formatter.format(Formatter.java:2505)
 at java.util.Formatter.format(Formatter.java:2459)
 at java.lang.String.format(String.java:2911)
 at android.content.res.Resources.getString(Resources.java:562)
 at android.content.Context.getString(Context.java:721)
 at gu.l(SourceFile:4)
 at jv.m(SourceFile:2)
 at Yq.c(SourceFile:4)
 at E7.l(SourceFile:2)
 at Yq.m(Unknown Source:0)
 at Yq.c(SourceFile:4)
 at mr.j(SourceFile:91)
 at wk.c(SourceFile:3)
 at androidx.recyclerview.widget.LinearLayoutManager.g1(Unknown Source:0)
 at androidx.recyclerview.widget.LinearLayoutManager.T0(SourceFile:2)
 at androidx.recyclerview.widget.LinearLayoutManager.j0(SourceFile:19)
 at androidx.recyclerview.widget.RecyclerView.w(Unknown Source:66)
 at androidx.recyclerview.widget.RecyclerView.u(SourceFile:6)
 at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:2)
 at android.view.View.layout(View.java:23203)
 at android.view.ViewGroup.layout(ViewGroup.java:6412)
 at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(Unknown Source:58)
 at android.view.View.layout(View.java:23203)
 at android.view.ViewGroup.layout(ViewGroup.java:6412)
 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
 at android.view.View.layout(View.java:23203)
 at android.view.ViewGroup.layout(ViewGroup.java:6412)
 at Ch.t(SourceFile:8)
 at gB.h(Unknown Source:0)
 at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:4)
 at android.view.View.layout(View.java:23203)
 at android.view.ViewGroup.layout(ViewGroup.java:6412)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
 at android.view.View.layout(View.java:23203)
 at android.view.ViewGroup.layout(ViewGroup.java:6412)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
 at android.view.View.layout(View.java:23203)
 at android.view.ViewGroup.layout(ViewGroup.java:6412)
 at androidx.constraintlayout.widget.ConstraintLayout.onLayout(Unknown Source:61)
 at android.view.View.layout(View.java:23203)
 at android.view.ViewGroup.layout(ViewGroup.java:6412)
 at androidx.coordinatorlayout.widget.CoordinatorLayout.s(SourceFile:15)
 at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:4)
 at android.view.View.layout(View.java:23203)
 at android.view.ViewGroup.layout(ViewGroup.java:6412)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
 at android.view.View.layout(View.java:23203)
 at android.view.ViewGroup.layout(ViewGroup.java:6412)
 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
 at android.view.View.layout(View.java:23203)
 at android.view.ViewGroup.layout(ViewGroup.java:6412)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
 at android.view.View.layout(View.java:23203)
 at android.view.ViewGroup.layout(ViewGroup.java:6412)

### Xposed Module List/Xposed 模块列表

```shell
N/A any Module
```

### Magisk Module List/Magisk 模块列表

```shell
Just Zygisk - LSPosed 1.8.4
```

### LSPosed version/LSPosed 版本

1.8.4

### Android version/Android 版本

Android 12

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-10-08T23_31_36.201.zip](https://github.com/LSPosed/LSPosed/files/9740301/LSPosed_2022-10-08T23_31_36.201.zip)

**Comment by yujincheng08** [comment]
Supports. This is a translation issue, so temporarily change your system language to English, open LSPosed manager, and forcibly set the language to English in the app.
