### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by SYREB** [LSPosed/LSPosed#2174]
### Steps to reproduce/复现步骤

1,手机没电关机
2,刚充电开机，充电器松动导致关机
3,（怀疑）救砖模块生效
4，在重新开机后无法正常打开LSPosed

### Expected behaviour/预期行为

正常情况下应该正常打开LSPosed

### Actual behaviour/实际行为

LSPosed无法正常进入，显示了一个黄色卡片，上面有一个类似于“⚠”图样和“MANAGER CRASHED”的字样

### Xposed Module List/Xposed 模块列表

```shell
打不开看不见了（悲）
```

### Magisk Module List/Magisk 模块列表

```shell
Move Certificates v1.9 
-by yochananmarqos

Scene的附加模块 v1 
-by 嘟嘟ski

Shamiko v0.5.2(120) 
-by LSPosed Developers

Systenless Hosts v1.0 
-by Magisk Manager

Universal SafetyNet Fix v2.2.0
-by kdrag0n

Zygisk - LSPoed v1.8.4(6609) 
-by LSPosed Developers

Zygisk - Sui v12.5.0
-by Rikka

淦MIUI温控（扩展模块） v1.3
-by Sy

自动神仙救砖 支持OTA稳定版 v210701
-by 奋斗的小青年(原作者Han|情非得已c)
```

### LSPosed version/LSPosed 版本

5551

### Android version/Android 版本

12

### Magisk version/Magisk 版本

555a54ec-alpha(25203)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Build version: v1.3.5 (5551) 
Current date: 2022-10-15 13:41:53 
Device: Xiaomi M2002J9E 
 
SDK: 31 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.lsposed.manager/org.lsposed.manager.ui.activity.MainActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x7f10002b
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3761)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3935)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2286)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8292)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f10002b
	at android.content.res.Resources.getText(Resources.java:463)
	at android.content.res.MiuiResources.getText(MiuiResources.java:106)
	at android.content.Context.getText(Context.java:702)
	at android.app.Activity.setTitle(Activity.java:7067)
	at by.onCreate(SourceFile:6)
	at Ll.onCreate(SourceFile:6)
	at g4.onCreate(Unknown Source:0)
	at org.lsposed.manager.ui.activity.MainActivity.onCreate(Unknown Source:12)
	at android.app.Activity.performCreate(Activity.java:8241)
	at android.app.Activity.performCreate(Activity.java:8207)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3734)
	... 12 more

**Comment by canyie** [comment]
```
Zygisk - LSPoed v1.8.4(6609) 
Build version: v1.3.5 (5551)
```
进入 magisk app 打开 LSPosed 模块，卸载旧版本管理器然后重启。

**Comment by SYREB** [comment]
> ```
> Zygisk - LSPoed v1.8.4(6609) 
> Build version: v1.3.5 (5551)
> ```
> 
> 进入 magisk app 启用 LSPosed 模块，卸载旧版本管理器然后重启。

无效，还是那样
