### ISSUE TITLE
LSPosed open app and direct crush

### ISSUE THREAD

**Issue by Bilalalichaki** [LSPosed/LSPosed#2175]
### Steps to reproduce/复现步骤

Please resolve bugs and new updatation

### Expected behaviour/预期行为

Open app direct close and crush

### Actual behaviour/实际行为

Open app direct close and crush error

### Xposed Module List/Xposed 模块列表

```shell
1st
```

### Magisk Module List/Magisk 模块列表

```shell
1st
```

### LSPosed version/LSPosed 版本

1.8.4

### Android version/Android 版本

12

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/a

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Build version: 1.8.4 (6609) 
Current date: 2022-10-15T11:31:07.839824 
Device: Xiaomi M2103K19G 
Fingerprint: Redmi/camellian_global/camellian:12/SP1A.210812.016/V13.0.2.0.SKSMIXM:user/release-keys 
 
SDK: 31 
 
Stack trace:  
de.robv.android.xposed.XposedHelpers$InvocationTargetError: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
	at de.robv.android.xposed.XposedHelpers.callStaticMethod(Unknown Source:17)
	at d0.replaceHookedMethod(SourceFile:2)
	at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(Unknown Source:0)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.getProvider(Unknown Source:5)
	at android.webkit.WebView.getFactory(WebView.java:2594)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2588)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2656)
	at android.view.View.<init>(View.java:5611)
	at android.view.View.<init>(View.java:5757)
	at android.view.ViewGroup.<init>(ViewGroup.java:710)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
	at android.webkit.WebView.<init>(WebView.java:421)
	at android.webkit.WebView.<init>(WebView.java:363)
	at android.webkit.WebView.<init>(WebView.java:345)
	at android.webkit.WebView.<init>(WebView.java:332)
	at android.webkit.WebView.<init>(WebView.java:322)
	at u7.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8298)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:532)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callStaticMethod(Unknown Source:5)
	... 25 more
Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:428)
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:493)
	... 27 more

**Comment by yujincheng08** [comment]
> No WebView installed
