### ISSUE TITLE
Lsposed crach not work android 12

### ISSUE THREAD

**Issue by xvpx5544** [LSPosed/LSPosed#2199]
### Steps to reproduce/复现步骤

error code : 
Build version: 1.8.4 (6609) 
Current date: 2022-10-29T21:43:24.885159 
Device: Nubia NX669J 
Fingerprint: nubia/NX669J-UN/NX669J-UN:12/SKQ1.211113.001/eng.nubia.20220823.195323:user/release-keys 
 
SDK: 31 
 
Stack trace:  
java.util.UnknownFormatConversionException: Conversion = 'End of String'
	at java.util.Formatter$FormatSpecifierParser.peek(Formatter.java:2647)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2608)
	at java.util.Formatter.parse(Formatter.java:2563)
	at java.util.Formatter.format(Formatter.java:2510)
	at java.util.Formatter.format(Formatter.java:2464)
	at java.lang.String.format(String.java:3644)
	at android.content.res.Resources.getString(Resources.java:597)
	at android.content.Context.getString(Context.java:721)
	at gu.l(SourceFile:4)
	at jv.m(SourceFile:2)
	at Yq.c(SourceFile:4)
	at E7.l(SourceFile:2)
	at Yq.m(Unknown Source:0)
	at Yq.c(SourceFile:4)
	at mr.j(SourceFile:91)
	at wk.c(SourceFile:3)
	at androidx.recyclerview.widget.LinearLayoutManager.g1(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.T0(SourceFile:2)
	at androidx.recyclerview.widget.LinearLayoutManager.j0(SourceFile:19)
	at androidx.recyclerview.widget.RecyclerView.w(Unknown Source:66)
	at androidx.recyclerview.widget.RecyclerView.u(SourceFile:6)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:2)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(Unknown Source:58)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1848)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at Ch.t(SourceFile:8)
	at gB.h(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:4)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(Unknown Source:61)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.s(SourceFile:15)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:4)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1848)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1848)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:899)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4098)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3540)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2464)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9777)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1120)
	at android.view.Choreographer.doCallbacks(Choreographer.java:926)
	at android.view.Choreographer.doFrame(Choreographer.java:859)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1105)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:379)
	at android.app.ActivityThread.main(ActivityThread.java:9271)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1018)
![Screenshot_2022-10-29-21-43-06-420](https://user-images.githubusercontent.com/57259689/198847834-562f1783-0f27-42e8-9ccd-e619dc9f1ca7.jpg)

### Expected behaviour/预期行为

fixed New update 

### Actual behaviour/实际行为

I don't what's the error 

### Xposed Module List/Xposed 模块列表

```shell
no
```

### Magisk Module List/Magisk 模块列表

```shell
no
```

### LSPosed version/LSPosed 版本

1.8.4

### Android version/Android 版本

12

### Magisk version/Magisk 版本

delta

### Riru version/Riru 版本

26

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Build version: 1.8.4 (6609) 
Current date: 2022-10-29T21:43:24.885159 
Device: Nubia NX669J 
Fingerprint: nubia/NX669J-UN/NX669J-UN:12/SKQ1.211113.001/eng.nubia.20220823.195323:user/release-keys 
 
SDK: 31 
 
Stack trace:  
java.util.UnknownFormatConversionException: Conversion = 'End of String'
	at java.util.Formatter$FormatSpecifierParser.peek(Formatter.java:2647)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2608)
	at java.util.Formatter.parse(Formatter.java:2563)
	at java.util.Formatter.format(Formatter.java:2510)
	at java.util.Formatter.format(Formatter.java:2464)
	at java.lang.String.format(String.java:3644)
	at android.content.res.Resources.getString(Resources.java:597)
	at android.content.Context.getString(Context.java:721)
	at gu.l(SourceFile:4)
	at jv.m(SourceFile:2)
	at Yq.c(SourceFile:4)
	at E7.l(SourceFile:2)
	at Yq.m(Unknown Source:0)
	at Yq.c(SourceFile:4)
	at mr.j(SourceFile:91)
	at wk.c(SourceFile:3)
	at androidx.recyclerview.widget.LinearLayoutManager.g1(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.T0(SourceFile:2)
	at androidx.recyclerview.widget.LinearLayoutManager.j0(SourceFile:19)
	at androidx.recyclerview.widget.RecyclerView.w(Unknown Source:66)
	at androidx.recyclerview.widget.RecyclerView.u(SourceFile:6)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:2)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(Unknown Source:58)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1848)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at Ch.t(SourceFile:8)
	at gB.h(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:4)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(Unknown Source:61)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.s(SourceFile:15)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:4)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1848)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1848)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:899)
	at android.view.View.layout(View.java:23236)
	at android.view.ViewGroup.layout(ViewGroup.java:6437)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4098)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3540)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2464)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9777)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1120)
	at android.view.Choreographer.doCallbacks(Choreographer.java:926)
	at android.view.Choreographer.doFrame(Choreographer.java:859)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1105)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:379)
	at android.app.ActivityThread.main(ActivityThread.java:9271)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1018)

**Comment by Howard20181** [comment]
Try latest CI version
