### ISSUE TITLE
[Bug] hook app  which using Retrofit2  will crash

### ISSUE THREAD

**Issue by ndl1302732** [LSPosed/LSPosed#2206]
### Steps to reproduce/复现步骤

I had written an Retrofit2 demo app,in which I invoke some method (with Annotation param) to request data from server.
and Then use LSP hook the method (with Annotation param) , the demo app will crash. 

Here is error msg:

2022-11-01 11:55:39.936 26061-26113/com.android.retrofit2 E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.android.retrofit2, PID: 26061
    java.lang.IllegalArgumentException: Wrong number of arguments; expected 2, got 0
        at java.lang.reflect.Method.invoke(Native Method)
        at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
        at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
        at LSPHooker_.getJsonData(Unknown Source:8)
        at com.android.retrofit2.MainActivity.getJsonData(MainActivity.java:95)
        at com.android.retrofit2.MainActivity.access$000(MainActivity.java:30)
        at com.android.retrofit2.MainActivity$1$1.run(MainActivity.java:64)
        at java.lang.Thread.run(Thread.java:923)

Here is the method:
public interface Api {
    //get请求
    @GET("api/rand.music")
    Call<Data<Info>> getJsonData(@Query("sort") String sort, @Query("format") String format);
}

retrofit2 will gen a proxy class , which implement getJsonData method. I hook the proxy class's getJsonData

here is attach file with demo app , and hook code 

[lsp.zip](https://github.com/LSPosed/LSPosed/files/9906684/lsp.zip)

lsp info: api 93 version 1.8.4（6609）, android 11 , Vivo V2115A

### Expected behaviour/预期行为

not crash

### Actual behaviour/实际行为

app crash

### Xposed Module List/Xposed 模块列表

```shell
only my hook module
```

### Magisk Module List/Magisk 模块列表

```shell
zygisk only
```

### LSPosed version/LSPosed 版本

1.8.4

### Android version/Android 版本

11

### Magisk version/Magisk 版本

25

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

2022-11-01 11:55:39.936 26061-26113/com.android.retrofit2 E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.android.retrofit2, PID: 26061
    java.lang.IllegalArgumentException: Wrong number of arguments; expected 2, got 0
        at java.lang.reflect.Method.invoke(Native Method)
        at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
        at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
        at LSPHooker_.getJsonData(Unknown Source:8)
        at com.android.retrofit2.MainActivity.getJsonData(MainActivity.java:95)
        at com.android.retrofit2.MainActivity.access$000(MainActivity.java:30)
        at com.android.retrofit2.MainActivity$1$1.run(MainActivity.java:64)
        at java.lang.Thread.run(Thread.java:923)

**Comment by ndl1302732** [comment]
my pool english, 我还是用中文描述一下：附件里面有demo app和hook代码。 最新的lsp框架，android11 vivo手机。

**Comment by vvb2060** [comment]
日志呢？

**Comment by ndl1302732** [comment]
> 日志呢？
lsp里面的模块日志吗？ 稍等一下

**Comment by ndl1302732** [comment]
> 日志呢？

[LSPosed_2022-11-01T12_23_48.638.zip](https://github.com/LSPosed/LSPosed/files/9906816/LSPosed_2022-11-01T12_23_48.638.zip)
是这个文件么？

**Comment by vvb2060** [comment]
I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志 ？

**Comment by ndl1302732** [comment]
> 

抱歉，这个我是顺手勾选的。我用的是LSP发布版1.8.4

**Comment by yujincheng08** [comment]
你猜我们为什么加了这个选项并且强制要求选择？

**Comment by ndl1302732** [comment]
> 你猜我们为什么加了这个选项并且强制要求选择？

提醒使用者，提交bug时，记得打包日志文件？我看了日志文件，和logcat输出的日志，好像没多大差别。(多一些lsp框架的日志)

**Comment by ndl1302732** [comment]
这是使用方法不当导致的，还是lsp本身的bug? 能简单说两句么？

**Comment by yujincheng08** [comment]
因为缺少日志所以无法判断。

**Comment by ndl1302732** [comment]
> 因为缺少日志所以无法判断。

是我提供的日志文件不对吗？还是需要使用这个版本"I am using latest debug CI version of LSPosed and enable verbose log" 才能提取到详细的日志，如果是的话，这个版本在哪里下载？我可以试试

**Comment by canyie** [comment]
> For canary build, please check [Github Actions](https://github.com/LSPosed/LSPosed/actions) Note: debug builds are only available in Github Actions.
