### ISSUE TITLE
[Bug] Unable to Launch LSPosed

### ISSUE THREAD

**Issue by qounik** [LSPosed/LSPosed#2384]
### Steps to reproduce/复现步骤

After activation of any module and rebooting system, sometimes module doesn't get activated, sometimes activated modules gets disabled, sometimes can't open the manage from anywhere (Shell Crash), Sometimes after activating module and rebooting; reboots automatically after unlocking the devices. After installing manage apk from /data/adb/lspd/manager.apk Notification says LSPosed loaded but Manager says Not Installed.

### Expected behaviour/预期行为

Opening Manager from notification or apk shouldn't crash shell, rebooting after activating any module should active one or more module and not disable other modules.

### Actual behaviour/实际行为

Manager doesn't open, modules gets disabled on reboot. Tried disabling all the magisk modules. Tried Turn on only and single single xposed modules with system framework.

### Xposed Module List/Xposed 模块列表

```shell
Disable-Flag_SECURE v2.0.0
GravityBox [P] v9.2.1
Hide My Applist v3.0.6
LuckyPatcher v10.6.6
Mock Mock Locations v1.4
NSFW GBoard v1.4.4
UpdateLocker v1.2.2
Youtube AdAway v5.0.3
CorePatch v2.2
[Disabled] Greenify v4.7.5
[Disabled] Scoop v2.4.2
```

### Magisk Module List/Magisk 模块列表

```shell
.core
[Disabled] AppDataIsolation Legacy Support v1.2
BusyBox for Android NDK v1.34.1
DalvikHyperthreading v2
find v2021.12.16
Hide UserDebug v1.0
Ice Box System Plugin Module v2.1
Magisk manager for Recovery Mode (mm) v2022.6.26
Magisk RAM Swapper v1.2
Process Monitor Tool v2.2
Shamiko v0.6
[Disabled] Smali Patcher v0.0.7.4
Systemless Hosts v1.0
UnityFix v5.0
Universal SafetyNet Fix v2.4.0
xmlpak - a road to vendor apps v4.5
Zygisk - LSPosed v1.8.6 (6719)
Zygisk - Sui v12.7.2
```

### LSPosed version/LSPosed 版本

Zygisk - LSPosed v1.8.6 (6719)

### Android version/Android 版本

Android 9 Pie

### Magisk version/Magisk 版本

Magisk v25.2 (25200)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Shell Crash log
`FATAL EXCEPTION: main
Process: com.android.shell, PID: 734
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.shell/com.android.shell.BugreportWarningActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7078)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
	at com.android.shell.BugreportWarningActivity.onCreate(BugreportWarningActivity.java:54)
	at android.app.Activity.performCreate(Activity.java:7327)
	at android.app.Activity.performCreate(Activity.java:7318)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101)
	... 11 more`
[lspd_NotLoaded.zip](https://github.com/LSPosed/LSPosed/files/10735155/lspd_NotLoaded.zip)
[lspd_Loaded.zip](https://github.com/LSPosed/LSPosed/files/10735151/lspd_Loaded.zip)

**Comment by yujincheng08** [comment]
what rom are u using?

**Comment by qounik** [comment]
Yes, I am on a Custom ROM. You are suggesting if i change my rom things will be better?

**Comment by yujincheng08** [comment]
yes

**Comment by jiashie** [comment]
same issue here。
phone: OnePlus 6T
system: android 9
os: Hydrogen OS 9.0.4

**Comment by LeeBinder** [comment]
see [here](https://github.com/orgs/LSPosed/discussions/2602) for a possible work-around
