### ISSUE TITLE
[Bug] 通知栏没有任何有关lsposed的信息，且在配置中打开通知栏会崩溃

### ISSUE THREAD

**Issue by xoomp** [LSPosed/LSPosed#2405]
### Steps to reproduce/复现步骤

1.  安装完lsposed并打开后有弹窗提升通知栏打开寄生管理器
2. 并不懂什么是寄生管理器，因为一直没见过通知栏有什么
3. 后来找到配置项有已经开启的通知栏，并尝试关闭，再打开的时候就会稳定复现bug，每次都直接崩溃

谢谢

### Expected behaviour/预期行为

通知栏没有任何有关lsposed的信息，且在配置中打开通知栏会崩溃

### Actual behaviour/实际行为

通知栏没有任何有关lsposed的信息，且在配置中打开通知栏会崩溃

### Xposed Module List/Xposed 模块列表

```shell
lsposed
```

### Magisk Module List/Magisk 模块列表

```shell
lsposed
```

### LSPosed version/LSPosed 版本

1.8.6-6712-zigisk

### Android version/Android 版本

10

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [ ] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Build version: 1.8.5 (6649) 
Current date: 2023-02-27T01:07:18.679 
Device: Samsung SM-G965F 
Fingerprint: samsung/star2ltexx/star2lte:10/QP1A.190711.020/G965FXXUHFVG4:user/release-keys 
 
SDK: 29 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.createPackageContext(java.lang.String, int)' on a null object reference
	at android.os.Parcel.createException(Parcel.java:2094)
	at android.os.Parcel.readException(Parcel.java:2056)
	at android.os.Parcel.readException(Parcel.java:2004)
	at qw.c(Unknown Source:54)
	at androidx.preference.Preference.b(Unknown Source:4)
	at androidx.preference.TwoStatePreference.n(Unknown Source:8)
	at androidx.preference.Preference.t(Unknown Source:12)
	at androidx.preference.SwitchPreferenceCompat.t(Unknown Source:0)
	at S0.onClick(Unknown Source:28)
	at android.view.View.performClick(View.java:7862)
	at android.view.View.performClickInternal(View.java:7831)
	at android.view.View.access$3600(View.java:879)
	at android.view.View$PerformClick.run(View.java:29359)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by xoomp** [comment]
bug  直接关

**Comment by Howard20181** [comment]
> ### Version requirement/版本要求
>  I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
