### ISSUE TITLE
[Bug] This class doesn't implement any sub-interface of XposedModule, skipping it

### ISSUE THREAD

**Issue by captain-miao** [LSPosed/LSPosed#2413]
### Steps to reproduce/复现步骤

1. install Module -> LSPModuleExample
2. reboot device

### Expected behaviour/预期行为

1. The application can be hooked.

### Actual behaviour/实际行为

1. Module skipped.

### Xposed Module List/Xposed 模块列表

```shell
1. LSPModuleExample
```

### Magisk Module List/Magisk 模块列表

```shell
1. LSPosed
2. Riru
```

### LSPosed version/LSPosed 版本

1.8.6 (6838)

### Android version/Android 版本

11 & 13

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

v26.1.7.r530

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Attempting to use Using Modern Xposed API, logs show XposedModule not implemented.

I don't know where it went wrong.

#### LSPosed info
> API 版本
100
Xposed API 调用保护
未启用
Dex 优化器包装
支持
框架版本
1.8.6 (6838)
管理器版本
1.8.6 (6838)
系统版本
13 (API 33)
设备
Google Google sdk_gphone64_arm64 
系统架构
arm64-v8a

#### LOG:
[verbose_2023-03-01T18:32:47.135268.log](https://github.com/LSPosed/LSPosed/files/10860072/verbose_2023-03-01T18.32.47.135268.log)

#### hook class
```java
public class MainHook extends XposedModule {
    private static final String TAG = "MainHook";
    public MainHook(@NonNull XposedContext base, @NonNull ModuleLoadedParam param) {
        super(base, param);
    }

    @Override
    public void onPackageLoaded(@NonNull PackageLoadedParam param) {
        super.onPackageLoaded(param);
        final String targetPackage = param.getPackageName();

        if (targetPackage.equals(getAppPackage())) {
//            de.robv.android.xposed.XposedHelpers.findAndHookMethod(getMainActName(), param.getClassLoader(),
//                    "isModuleActive", de.robv.android.xposed.XC_MethodReplacement.returnConstant(true));

            log(TAG + " isModuleActive()");

            return;
        }

        // other app
    }

    @Override
    public void onSystemServerLoaded(@NonNull SystemServerLoadedParam param) {
        super.onSystemServerLoaded(param);
        log(TAG + "on system server loaded.");
    }

    private String getAppPackage() {
        return BuildConfig.APPLICATION_ID;
    }

    public String getMainActName() {
        return "com.example.lspmoduleexample.MainActivity";
    }
}

```

#### LSPosed-debug log on OnePlus
> API 版本
100
Xposed API 调用保护
未启用
Dex 优化器包装
支持
框架版本
1.8.6 (6838)
管理器版本
1.8.6 (6838)
系统版本
11 (API 30)
设备
OnePlus GM1900 
系统架构
arm64-v8a

```java
[ 2023-03-01T19:03:22.402     1000:  1678:  1678 D/LSPosedContext  ] Loading module com.example.lspmoduleexample
[ 2023-03-01T19:03:22.507     1000:  1678:  1678 E/LSPosedContext  ]   Cannot load module: com.example.lspmoduleexample
[ 2023-03-01T19:03:22.507     1000:  1678:  1678 E/LSPosedContext  ]   The Xposed API classes are compiled into the module's APK.
[ 2023-03-01T19:03:22.507     1000:  1678:  1678 E/LSPosedContext  ]   This may cause strange issues and must be fixed by the module developer.
```
[verbose_2023-03-01T19:03:19.491.log](https://github.com/LSPosed/LSPosed/files/10860224/verbose_2023-03-01T19.03.19.491.log)

#### LSPModuleExample 
[https://github.com/jdlingyu/LSPModuleExample](https://github.com/jdlingyu/LSPModuleExample)

**Comment by yujincheng08** [comment]
use compileOnly to import api

**Comment by yujincheng08** [comment]
added this info to wiki now.

**Comment by captain-miao** [comment]
> use compileOnly to import api

The test is fine now. Currently, it is found that the activation status of the module is not displayed as activated. Additionally, hooking the Android system framework is not working.


#### error when hooking LoadedApk#getClassLoader: pkg=android, prc=android
```shell
error when hooking LoadedApk#getClassLoader: pkg=android, prc=android
java.lang.NullPointerException
	at java.io.File.<init>(File.java:288)
	at org.lsposed.lspd.hooker.LoadedApkGetCLHooker.hookNewXSP(LoadedApkGetCLHooker.java:162)
	at org.lsposed.lspd.hooker.LoadedApkGetCLHooker.afterHookedMethod(LoadedApkGetCLHooker.java:112
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:494)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.ContextImpl.getClassLoader(ContextImpl.java:412)
	at org.lsposed.lspd.impl.LSPosedContext.getClassLoader(LSPosedContext.java:246)
	at org.lsposed.lspd.impl.LSPosedContext.loadModule(LSPosedContext.java:164)
	at org.lsposed.lspd.hooker.AttachHooker.lambda$afterHookedMethod$0(AttachHooker.java:16)
	at org.lsposed.lspd.hooker.AttachHooker$$ExternalSyntheticLambda0.accept(Unknown Source:4)
	at java.util.ArrayList.forEach(ArrayList.java:1262)
	at org.lsposed.lspd.hooker.AttachHooker.afterHookedMethod(AttachHooker.java:15)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:494)
	at LSPHooker_.attach(Unknown Source:22)
	at android.app.ActivityThread.main(ActivityThread.java:7997)

                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

**Comment by yujincheng08** [comment]
new modules are not hooking themselves are known issue.

provided logs are raised when hooking system framework?
