### ISSUE TITLE
Chash[6871]

### ISSUE THREAD

**Issue by Kostamn** [LSPosed/LSPosed#2476]
### Steps to reproduce/复现步骤

Open and cut into the background and crash after a while

### Expected behaviour/预期行为

Just normal

### Actual behaviour/实际行为

Crash

### Xposed Module List/Xposed 模块列表

```shell
com.fuckhome.xiaowine
UNLOCK CN GMS
```

### Magisk Module List/Magisk 模块列表

```shell
MIUI-MONET
MONETALL
ZYGISK-LSP
```

### LSPosed version/LSPosed 版本

6871

### Android version/Android 版本

12

### Magisk version/Magisk 版本

fdac22ba-delta

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Build version: 1.8.6 (6871) 
Current date: 2023-04-06T10:52:47.185 
Device: Xiaomi Redmi K30 Pro Zoom Edition 
Fingerprint: Redmi/lmipro/lmipro:12/SKQ1.211006.001/V13.0.6.0.SJKCNXM:user/release-keys 
 
SDK: 31 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.lsposed.manager/org.lsposed.manager.ui.activity.MainActivity}: android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class zf
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3763)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3937)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2288)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8293)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class zf
	at android.os.Parcel.readParcelableCreator(Parcel.java:3420)
	at android.os.Parcel.readParcelable(Parcel.java:3325)
	at android.os.Parcel.readValue(Parcel.java:3227)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3624)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
	at android.os.BaseBundle.keySet(BaseBundle.java:569)
	at yf.V(Unknown Source:2)
	at yf.b(Unknown Source:165)
	at G7.a(Unknown Source:155)
	at androidx.activity.a.onCreate(Unknown Source:29)
	at ff.onCreate(Unknown Source:0)
	at jy.onCreate(Unknown Source:140)
	at Nl.onCreate(Unknown Source:46)
	at r4.onCreate(Unknown Source:6)
	at org.lsposed.manager.ui.activity.MainActivity.onCreate(Unknown Source:12)
	at android.app.Activity.performCreate(Activity.java:8241)
	at android.app.Activity.performCreate(Activity.java:8207)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3736)
	... 12 more
Caused by: java.lang.NoSuchFieldException: CREATOR
	at java.lang.Class.getField(Class.java:1635)
	at android.os.Parcel.readParcelableCreator(Parcel.java:3397)
	... 31 more

**Comment by yujincheng08** [comment]
>  I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
