### ISSUE TITLE
[Bug] Lsposed Manager Crashing always

### ISSUE THREAD

**Issue by atharva80** [LSPosed/LSPosed#2535]
### Steps to reproduce/复现步骤

I installed Lsposed module and manager and rebooted the device 

### Expected behaviour/预期行为

Lsposed manager should have run properly

### Actual behaviour/实际行为

Lsposed manager is crashing always

### Xposed Module List/Xposed 模块列表

```shell
N/A
```

### Magisk Module List/Magisk 模块列表

```shell
Pixelify 
Yt Revanced
Adaway
```

### LSPosed version/LSPosed 版本

1.8.6-6712

### Android version/Android 版本

12

### Magisk version/Magisk 版本

26.1

### Riru version/Riru 版本

26.1.7

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Build version: 1.8.6 (6712) 
Current date: 2023-05-14T12:32:53.923 
Device: Unknown Phh-Treble with GApps 
Fingerprint: /phhgsi_arm64_ab/phhgsi_arm64_ab:12/SQ3A.220705.004/eng.crossg.20230508.180904:userdebug/test-keys 
 
SDK: 32 
 
Stack trace:  
java.lang.StringIndexOutOfBoundsException: length=0; index=0
	at java.lang.String.charAt(Native Method)
	at org.lsposed.manager.ui.fragment.HomeFragment.F(Unknown Source:1274)
	at he.V(Unknown Source:19)
	at androidx.fragment.app.a.f(Unknown Source:161)
	at androidx.fragment.app.a.k(Unknown Source:117)
	at De.O(Unknown Source:62)
	at De.t(Unknown Source:35)
	at androidx.fragment.app.a.f(Unknown Source:232)
	at androidx.fragment.app.a.k(Unknown Source:117)
	at De.O(Unknown Source:62)
	at De.t(Unknown Source:35)
	at ke.onStart(Unknown Source:34)
	at L1.onStart(Unknown Source:0)
	at X3.onStart(Unknown Source:0)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1471)
	at android.app.Activity.performStart(Activity.java:8082)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3732)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by atharva80** [comment]
Why did you close the issue it's not fixed?

**Comment by yujincheng08** [comment]
maybe its fixed. who knows?

**Comment by atharva80** [comment]
Help me brother please 🥺
