### ISSUE TITLE
[Bug] Parasitic Manager doesn't work with Android 10 One UI Samsung

### ISSUE THREAD

**Issue by addas** [LSPosed/LSPosed#2582]
### Steps to reproduce/复现步骤

1. Own a Samsung device running One UI Android 10
2. Install LSPosed using Magisk
3. Parasitic Notification doesn't show, forcing Enabling showing Parasitic Status crashes LSPosed Play Store APK

### Expected behaviour/预期行为

We shouldn't install LSPosed Play Store because Parastic notification will show after installation

### Actual behaviour/实际行为

No notification, when enabling notification app crashes

### Xposed Module List/Xposed 模块列表

```shell
• Alltrans
• Android Faker
• App Setting Reborn
• Bluetooth Toolkit
• Core Patch
• DevOptsHide
• Firefds Kit [Q]
• GPS Setter
• Greenify
• Hide My Applist
• Maps Tweak
• SIM Number Setter
• UpdateLocker
• XDowngrader
• Xposed Edge Pro
• XPrivacyLua
```

### Magisk Module List/Magisk 模块列表

```shell
• Busybox NDK
• KnoxPatcher Enhancer
• liboemcrypto disabler
• MagiskHide Props Config
• Shamiko
• Universal SafetyNet Fix by kdrag0n & Displex
• Zygisk - LSPosed
• Zygisk - Sui
```

### LSPosed version/LSPosed 版本

1.8.6 (6712)

### Android version/Android 版本

10

### Magisk version/Magisk 版本

26.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Build version: 1.8.6 (6712) 
Current date: 2023-06-26T21:21:44.719 
Device: Samsung SM-N960F 
Fingerprint: samsung/crownltexx/crownlte:10/QP1A.190711.020/N960FXXU9FVK1:user/release-keys 
 
SDK: 29 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.createPackageContext(java.lang.String, int)' on a null object reference
	at android.os.Parcel.createException(Parcel.java:2094)
	at android.os.Parcel.readException(Parcel.java:2056)
	at android.os.Parcel.readException(Parcel.java:2004)
	at qw.c(Unknown Source:54)
	at androidx.preference.Preference.b(Unknown Source:4)
	at androidx.preference.TwoStatePreference.n(Unknown Source:8)
	at androidx.preference.Preference.t(Unknown Source:12)
	at androidx.preference.SwitchPreferenceCompat.t(Unknown Source:0)
	at S0.onClick(Unknown Source:28)
	at android.view.View.performClick(View.java:7862)
	at android.view.View.performClickInternal(View.java:7831)
	at android.view.View.access$3600(View.java:879)
	at android.view.View$PerformClick.run(View.java:29359)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by rwdsji** [comment]
I'm having the exact same problem. Why are you closing this without any further information?

**Comment by yujincheng08** [comment]
because he didnt not use debug ver
