### ISSUE TITLE
[Bug] Getting resources fails with IllegalArgumentException if module has system_server in scope

### ISSUE THREAD

**Issue by anonymix007** [LSPosed/LSPosed#2620]
### Steps to reproduce/复现步骤

1. Create a module which injects into some app (Settings in my case) and into system_server, there are separate classes for that
2. Class for injection into Settings app calls to getResources.
3. Open Settings app

### Expected behaviour/预期行为

App should work without crashes, module should get all necessary resources.

### Actual behaviour/实际行为

App crashes:
```java
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: java.lang.IllegalArgumentException: path must not be null
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at DxS.EPH.xY.Rnx.ubv.hoKiQhJ.Resources.createInstance(XModuleResources.java:54)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at org.lsposed.lspd.impl.LSPosedContext.getResources(LSPosedContext.java:233)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at android.content.ContextWrapper.getResources(ContextWrapper.java:121)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at ru.kirddos.exta2dp.modules.SettingsUIModule.lambda$onPackageLoaded$6$ru-kirddos-exta2dp-modules-SettingsUIModule(SettingsUIModule.java:352)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at ru.kirddos.exta2dp.modules.SettingsUIModule$$ExternalSyntheticLambda8.before(Unknown Source:8)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at AICOI.UsIseuSP.lOLHlcB.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:458)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at LSPHooker_.initialize(Unknown Source:11)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at com.android.settings.development.bluetooth.BluetoothCodecDialogPreference.<init>(BluetoothCodecDialogPreference.java:42)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at cn.nubia.commonui.androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:242)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at cn.nubia.commonui.androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:277)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at cn.nubia.commonui.androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:344)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at cn.nubia.commonui.androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:346)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at cn.nubia.commonui.androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:157)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at cn.nubia.commonui.androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:109)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at cn.nubia.commonui.androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:216)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at cn.nubia.commonui.androidx.preference.PreferenceFragmentCompat.addPreferencesFromResource(PreferenceFragmentCompat.java:364)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at com.android.settings.core.InstrumentedPreferenceFragment.addPreferencesFromResource(InstrumentedPreferenceFragment.java:88)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at com.android.settings.SettingsPreferenceFragment.addPreferencesFromResource(SettingsPreferenceFragment.java:171)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at com.android.settings.dashboard.DashboardFragment.displayResourceTiles(DashboardFragment.java:388)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at com.android.settings.dashboard.DashboardFragment.refreshAllPreferences(DashboardFragment.java:466)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at com.android.settings.dashboard.DashboardFragment.onCreatePreferences(DashboardFragment.java:200)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at cn.nubia.commonui.androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:163)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at com.android.settingslib.core.lifecycle.ObservablePreferenceFragment.onCreate(ObservablePreferenceFragment.java:61)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at com.android.settings.SettingsPreferenceFragment.onCreate(SettingsPreferenceFragment.java:146)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at com.android.settings.dashboard.DashboardFragment.onCreate(DashboardFragment.java:168)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at com.android.settings.dashboard.RestrictedDashboardFragment.onCreate(RestrictedDashboardFragment.java:104)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at com.android.settings.development.DevelopmentSettingsDashboardFragment.onCreate(DevelopmentSettingsDashboardFragment.java:211)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2947)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:455)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:255)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1797)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1715)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1658)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:564)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at com.android.settings.SettingsActivity.switchToFragment(SettingsActivity.java:892)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at com.android.settings.SettingsActivity.launchSettingFragment(SettingsActivity.java:642)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at com.android.settings.SettingsActivity.onCreate(SettingsActivity.java:394)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at android.app.Activity.performCreate(Activity.java:8440)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at android.app.Activity.performCreate(Activity.java:8419)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1410)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4072)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4237)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at android.os.Looper.loopOnce(Looper.java:242)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at android.os.Looper.loop(Looper.java:374)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:8911)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:671)
07-12 17:09:21.421 17049 17049 E LSPosed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:951)
```
The actual crash reason is different, but it is caused by this one indirectly.

### Xposed Module List/Xposed 模块列表

```shell
Module with issue
App Settings Reborn
Killergram
```

### Magisk Module List/Magisk 模块列表

```shell
LSPosed
Universal SafetyNet Fix
```

### LSPosed version/LSPosed 版本

1.8.6 (6931)

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-07-12T17_36_58.248533.zip](https://github.com/LSPosed/LSPosed/files/12029076/LSPosed_2023-07-12T17_36_58.248533.zip)

**Comment by yujincheng08** [comment]
Try #2621
