### ISSUE TITLE
[Bug]Update 1.9.1 caused the wx module and Yangtze River 9 module to be unavailable

### ISSUE THREAD

**Issue by linlu06** [LSPosed/LSPosed#2741]
### Steps to reproduce/复现步骤

[ 2023-09-04T01:22:30.385        0:   995:  1080 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/verbose_2023-09-04T01:22:30.38528.log
[ 2023-09-04T01:22:37.861        0:   995:  6875 I/LSPosedLogcat   ] !!refresh_modules!!
[ 2023-09-04T01:22:37.862        0:   995:  1080 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/modules_2023-09-04T01:22:37.862722.log
[ 2023-09-04T01:23:11.696    10260:  5392:  5392 I/LSPosed         ] Loading xposed for com.tencent.mm/10260
[ 2023-09-04T01:23:11.701    10260:  5392:  5392 I/LSPosed-Bridge  ] Loading legacy module com.fkzhang.wechatxposed from /data/app/~~CmIH1fVA4EWKsxXR-R1gfA==/com.fkzhang.wechatxposed-Mxjg-pSq5omizcL_Wnzfaw==/base.apk
[ 2023-09-04T01:23:11.712    10260:  5392:  5392 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2023-09-04T01:23:12.148    10260:  5392:  5392 I/LSPosed-Bridge  ] WeXposed: com.tencent.mm loading com.fkzhang.wechatxposed
[ 2023-09-04T01:23:12.262    10260:  5392:  5392 E/LSPosed-Bridge  ] com.fkzhang.wechatxposedhooks.XposedTools.InvocationTargetError: java.lang.NoSuchMethodError: com.tencent.mm.plugin.normsg.f#Gj0(boolean)#exact
	at c.ﾞˆ.ﹶʽ.ˋʼ(Unknown Source:26)
	at c.ﾞˆ.ˏـ.ˏـ(Unknown Source:26)
	at c.ﾞˆ.ᵎᵎ.ˉᴵ(Unknown Source:36)
	at c.ﾞˆ.ᵎᵎ.ˏᵢ(Unknown Source:21)
	at c.ﾞˆ.ᵎᵎ.ᵔˏ(Unknown Source:1)
	at c.ﹳˏ.ﹶᵎ.ᐧˏ(Unknown Source:114)
	at c.ﹳˏ.ﹶᵎ.ʾי(Unknown Source:25)
	at c.ﹳˏ.ﹶᵎ.hook(Unknown Source:201)
	at c.ﹳˏ.ﾞˆ.hook(Unknown Source:0)
	at c.ﹳˏ.ᐧʼ.ˆʿ(Unknown Source:62)
	at c.ﹳˏ.ᐧʼ.hook(Unknown Source:20)
	at java.lang.reflect.Method.invoke(Native Method)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.callMethod(SourceFile:2)
	at x.ᴵˊ.ᵔ.ʻʻ(Unknown Source:271)
	at x.ᴵˊ.ᵔ.ⁱᴵ(Unknown Source:1)
	at x.ᴵˊ.ﹳﹶ.ˊ(Unknown Source:0)
	at x.ᴵˊ.ﹳﹶ.ʾʻ(Unknown Source:48)
	at x.ⁱᵎ.ᵎˉ.ˊ(Unknown Source:2)
	at x.ᴵˊ.ˊ.ᵔ(Unknown Source:607)
	at x.ᴵˊ.ˊ.ﹳˏ(Unknown Source:0)
	at x.ᴵˊ.ˊ$ˑʾ.afterHookedMethod(Unknown Source:61)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.attachBaseContext(Unknown Source:11)
	at android.app.Application.attach(Application.java:361)
	at java.lang.reflect.Method.invoke(Native Method)
	at WcpRaMXvm.ZoLvGqzTBqyNaI.R.vn.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1252)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1512)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1444)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7195)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8399)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.NoSuchMethodError: com.tencent.mm.plugin.normsg.f#Gj0(boolean)#exact
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.lambda$findMethodExact$3(Unknown Source:6)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.h(Unknown Source:0)
	at MDIQsCx.kNJI.YEROBMoRJ.c.get(Unknown Source:13)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.findMethodExact(SourceFile:1)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.findAndHookMethod(SourceFile:1)
	at java.lang.reflect.Method.invoke(Native Method)
	at c.ﾞˆ.ﹶʽ.ˋʼ(Unknown Source:14)
	... 41 more
[ 2023-09-04T01:23:12.262    10260:  5392:  5392 I/LSPosed-Bridge  ] WeXposed: hook failed: class com.tencent.mm.plugin.normsg.f
[ 2023-09-04T01:23:12.262    10260:  5392:  5392 I/LSPosed-Bridge  ] WeXposed: class com.tencent.mm.plugin.normsg.f.Gj0.boolean
[ 2023-09-04T01:23:12.263    10260:  5392:  5392 E/LSPosed-Bridge  ] com.fkzhang.wechatxposedhooks.XposedTools.InvocationTargetError: java.lang.NoSuchMethodError: com.tencent.mm.plugin.normsg.f#ND0(java.lang.String)#exact
	at c.ﾞˆ.ﹶʽ.ˋʼ(Unknown Source:26)
	at c.ﾞˆ.ˏـ.ˏـ(Unknown Source:26)
	at c.ﾞˆ.ᵎᵎ.ˉᴵ(Unknown Source:36)
	at c.ﾞˆ.ᵎᵎ.ˏᵢ(Unknown Source:21)
	at c.ﾞˆ.ᵎᵎ.ᵔˏ(Unknown Source:1)
	at c.ﹳˏ.ﹶᵎ.ᐧˏ(Unknown Source:228)
	at c.ﹳˏ.ﹶᵎ.ʾי(Unknown Source:25)
	at c.ﹳˏ.ﹶᵎ.hook(Unknown Source:201)
	at c.ﹳˏ.ﾞˆ.hook(Unknown Source:0)
	at c.ﹳˏ.ᐧʼ.ˆʿ(Unknown Source:62)
	at c.ﹳˏ.ᐧʼ.hook(Unknown Source:20)
	at java.lang.reflect.Method.invoke(Native Method)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.callMethod(SourceFile:2)
	at x.ᴵˊ.ᵔ.ʻʻ(Unknown Source:271)
	at x.ᴵˊ.ᵔ.ⁱᴵ(Unknown Source:1)
	at x.ᴵˊ.ﹳﹶ.ˊ(Unknown Source:0)
	at x.ᴵˊ.ﹳﹶ.ʾʻ(Unknown Source:48)
	at x.ⁱᵎ.ᵎˉ.ˊ(Unknown Source:2)
	at x.ᴵˊ.ˊ.ᵔ(Unknown Source:607)
	at x.ᴵˊ.ˊ.ﹳˏ(Unknown Source:0)
	at x.ᴵˊ.ˊ$ˑʾ.afterHookedMethod(Unknown Source:61)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.attachBaseContext(Unknown Source:11)
	at android.app.Application.attach(Application.java:361)
	at java.lang.reflect.Method.invoke(Native Method)
	at WcpRaMXvm.ZoLvGqzTBqyNaI.R.vn.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1252)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1512)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1444)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7195)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8399)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.NoSuchMethodError: com.tencent.mm.plugin.normsg.f#ND0(java.lang.String)#exact
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.lambda$findMethodExact$3(Unknown Source:6)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.h(Unknown Source:0)
	at MDIQsCx.kNJI.YEROBMoRJ.c.get(Unknown Source:13)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.findMethodExact(SourceFile:1)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.findAndHookMethod(SourceFile:1)
	at java.lang.reflect.Method.invoke(Native Method)
	at c.ﾞˆ.ﹶʽ.ˋʼ(Unknown Source:14)
	... 41 more
[ 2023-09-04T01:23:12.263    10260:  5392:  5392 I/LSPosed-Bridge  ] WeXposed: hook failed: class com.tencent.mm.plugin.normsg.f
[ 2023-09-04T01:23:12.263    10260:  5392:  5392 I/LSPosed-Bridge  ] WeXposed: class com.tencent.mm.plugin.normsg.f.ND0.java.lang.String
[ 2023-09-04T01:23:12.264    10260:  5392:  5392 E/LSPosed-Bridge  ] com.fkzhang.wechatxposedhooks.XposedTools.InvocationTargetError: java.lang.NoSuchMethodError: com.tencent.mm.app.g1#a(java.lang.StackTraceElement[])#exact
	at c.ﾞˆ.ﹶʽ.ˋʼ(Unknown Source:26)
	at c.ﾞˆ.ˏـ.ˏـ(Unknown Source:26)
	at c.ﾞˆ.ᵎᵎ.ˉᴵ(Unknown Source:36)
	at c.ﾞˆ.ᵎᵎ.ˏᵢ(Unknown Source:21)
	at c.ﾞˆ.ᵎᵎ.ᵔˏ(Unknown Source:1)
	at c.ﹳˏ.ﹶᵎ.ᐧˏ(Unknown Source:414)
	at c.ﹳˏ.ﹶᵎ.ʾי(Unknown Source:25)
	at c.ﹳˏ.ﹶᵎ.hook(Unknown Source:201)
	at c.ﹳˏ.ﾞˆ.hook(Unknown Source:0)
	at c.ﹳˏ.ᐧʼ.ˆʿ(Unknown Source:62)
	at c.ﹳˏ.ᐧʼ.hook(Unknown Source:20)
	at java.lang.reflect.Method.invoke(Native Method)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.callMethod(SourceFile:2)
	at x.ᴵˊ.ᵔ.ʻʻ(Unknown Source:271)
	at x.ᴵˊ.ᵔ.ⁱᴵ(Unknown Source:1)
	at x.ᴵˊ.ﹳﹶ.ˊ(Unknown Source:0)
	at x.ᴵˊ.ﹳﹶ.ʾʻ(Unknown Source:48)
	at x.ⁱᵎ.ᵎˉ.ˊ(Unknown Source:2)
	at x.ᴵˊ.ˊ.ᵔ(Unknown Source:607)
	at x.ᴵˊ.ˊ.ﹳˏ(Unknown Source:0)
	at x.ᴵˊ.ˊ$ˑʾ.afterHookedMethod(Unknown Source:61)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.attachBaseContext(Unknown Source:11)
	at android.app.Application.attach(Application.java:361)
	at java.lang.reflect.Method.invoke(Native Method)
	at WcpRaMXvm.ZoLvGqzTBqyNaI.R.vn.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1252)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1512)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1444)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7195)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8399)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.NoSuchMethodError: com.tencent.mm.app.g1#a(java.lang.StackTraceElement[])#exact
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.lambda$findMethodExact$3(Unknown Source:6)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.h(Unknown Source:0)
	at MDIQsCx.kNJI.YEROBMoRJ.c.get(Unknown Source:13)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.findMethodExact(SourceFile:1)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.findAndHookMethod(SourceFile:1)
	at java.lang.reflect.Method.invoke(Native Method)
	at c.ﾞˆ.ﹶʽ.ˋʼ(Unknown Source:14)
	... 41 more
[ 2023-09-04T01:23:12.264    10260:  5392:  5392 I/LSPosed-Bridge  ] WeXposed: hook failed: class com.tencent.mm.app.g1
[ 2023-09-04T01:23:12.264    10260:  5392:  5392 I/LSPosed-Bridge  ] WeXposed: class com.tencent.mm.app.g1.a.[Ljava.lang.StackTraceElement;
[ 2023-09-04T01:23:12.268    10260:  5392:  5392 E/LSPosed-Bridge  ] com.fkzhang.wechatxposedhooks.XposedTools.InvocationTargetError: java.lang.NoSuchMethodError: qn3.a#onGYNetEnd(int,int,int,java.lang.String,com.tencent.mm.network.u,byte[])#exact
	at c.ﾞˆ.ﹶʽ.ˋʼ(Unknown Source:26)
	at c.ﾞˆ.ˏـ.ˏـ(Unknown Source:26)
	at c.ﾞˆ.ᵎᵎ.ˉᴵ(Unknown Source:36)
	at c.ﾞˆ.ᵎᵎ.ˏᵢ(Unknown Source:21)
	at c.ﾞˆ.ᵎᵎ.ᵔˏ(Unknown Source:1)
	at c.ﹳˏ.ﹶᵎ.ﹶʼ(Unknown Source:846)
	at c.ﹳˏ.ﹶᵎ.ʾי(Unknown Source:33)
	at c.ﹳˏ.ﹶᵎ.hook(Unknown Source:201)
	at c.ﹳˏ.ﾞˆ.hook(Unknown Source:0)
	at c.ﹳˏ.ᐧʼ.ˆʿ(Unknown Source:62)
	at c.ﹳˏ.ᐧʼ.hook(Unknown Source:20)
	at java.lang.reflect.Method.invoke(Native Method)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.callMethod(SourceFile:2)
	at x.ᴵˊ.ᵔ.ʻʻ(Unknown Source:271)
	at x.ᴵˊ.ᵔ.ⁱᴵ(Unknown Source:1)
	at x.ᴵˊ.ﹳﹶ.ˊ(Unknown Source:0)
	at x.ᴵˊ.ﹳﹶ.ʾʻ(Unknown Source:48)
	at x.ⁱᵎ.ᵎˉ.ˊ(Unknown Source:2)
	at x.ᴵˊ.ˊ.ᵔ(Unknown Source:607)
	at x.ᴵˊ.ˊ.ﹳˏ(Unknown Source:0)
	at x.ᴵˊ.ˊ$ˑʾ.afterHookedMethod(Unknown Source:61)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.attachBaseContext(Unknown Source:11)
	at android.app.Application.attach(Application.java:361)
	at java.lang.reflect.Method.invoke(Native Method)
	at WcpRaMXvm.ZoLvGqzTBqyNaI.R.vn.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1252)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1512)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1444)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7195)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8399)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.NoSuchMethodError: qn3.a#onGYNetEnd(int,int,int,java.lang.String,com.tencent.mm.network.u,byte[])#exact
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.lambda$findMethodExact$3(Unknown Source:6)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.h(Unknown Source:0)
	at MDIQsCx.kNJI.YEROBMoRJ.c.get(Unknown Source:13)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.findMethodExact(SourceFile:1)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.findAndHookMethod(SourceFile:1)
	at java.lang.reflect.Method.invoke(Native Method)
	at c.ﾞˆ.ﹶʽ.ˋʼ(Unknown Source:14)
	... 41 more
[ 2023-09-04T01:23:12.268    10260:  5392:  5392 I/LSPosed-Bridge  ] WeXposed: hook failed: class qn3.a
[ 2023-09-04T01:23:12.268    10260:  5392:  5392 I/LSPosed-Bridge  ] WeXposed: class qn3.a.onGYNetEnd.int.int.int.java.lang.String.com.tencent.mm.network.u.[B
[ 2023-09-04T01:23:12.271    10260:  5392:  5392 E/LSPosed-Bridge  ] com.fkzhang.wechatxposedhooks.XposedTools.InvocationTargetError: java.lang.NoSuchMethodError: wc1.d#g(java.lang.String,java.lang.String,boolean,boolean)#exact
	at c.ﾞˆ.ﹶʽ.ˋʼ(Unknown Source:26)
	at c.ﾞˆ.ˏـ.ˏـ(Unknown Source:26)
	at c.ﾞˆ.ᵎᵎ.ˉᴵ(Unknown Source:36)
	at c.ﾞˆ.ᵎᵎ.ˏᵢ(Unknown Source:21)
	at c.ﾞˆ.ᵎᵎ.ᵔˏ(Unknown Source:1)
	at c.ﹳˏ.ﹶᵎ.ٴˆ(Unknown Source:229)
	at c.ﹳˏ.ﹶᵎ.ʾי(Unknown Source:41)
	at c.ﹳˏ.ﹶᵎ.hook(Unknown Source:201)
	at c.ﹳˏ.ﾞˆ.hook(Unknown Source:0)
	at c.ﹳˏ.ᐧʼ.ˆʿ(Unknown Source:62)
	at c.ﹳˏ.ᐧʼ.hook(Unknown Source:20)
	at java.lang.reflect.Method.invoke(Native Method)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.callMethod(SourceFile:2)
	at x.ᴵˊ.ᵔ.ʻʻ(Unknown Source:271)
	at x.ᴵˊ.ᵔ.ⁱᴵ(Unknown Source:1)
	at x.ᴵˊ.ﹳﹶ.ˊ(Unknown Source:0)
	at x.ᴵˊ.ﹳﹶ.ʾʻ(Unknown Source:48)
	at x.ⁱᵎ.ᵎˉ.ˊ(Unknown Source:2)
	at x.ᴵˊ.ˊ.ᵔ(Unknown Source:607)
	at x.ᴵˊ.ˊ.ﹳˏ(Unknown Source:0)
	at x.ᴵˊ.ˊ$ˑʾ.afterHookedMethod(Unknown Source:61)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.attachBaseContext(Unknown Source:11)
	at android.app.Application.attach(Application.java:361)
	at java.lang.reflect.Method.invoke(Native Method)
	at WcpRaMXvm.ZoLvGqzTBqyNaI.R.vn.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1252)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1512)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1444)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7195)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8399)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.NoSuchMethodError: wc1.d#g(java.lang.String,java.lang.String,boolean,boolean)#exact
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.lambda$findMethodExact$3(Unknown Source:6)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.h(Unknown Source:0)
	at MDIQsCx.kNJI.YEROBMoRJ.c.get(Unknown Source:13)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.findMethodExact(SourceFile:1)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.findAndHookMethod(SourceFile:1)
	at java.lang.reflect.Method.invoke(Native Method)
	at c.ﾞˆ.ﹶʽ.ˋʼ(Unknown Source:14)
	... 41 more
[ 2023-09-04T01:23:12.271    10260:  5392:  5392 I/LSPosed-Bridge  ] WeXposed: hook failed: class wc1.d
[ 2023-09-04T01:23:12.271    10260:  5392:  5392 I/LSPosed-Bridge  ] WeXposed: class wc1.d.g.java.lang.String.java.lang.String.boolean.boolean
[ 2023-09-04T01:23:12.275    10260:  5392:  5392 E/LSPosed-Bridge  ] com.fkzhang.wechatxposedhooks.XposedTools.InvocationTargetError: java.lang.NoSuchMethodError: com.tencent.mm.storage.u1#e(int,java.lang.Object)#exact
	at c.ﾞˆ.ﹶʽ.ˋʼ(Unknown Source:26)
	at c.ﾞˆ.ˏـ.ˏـ(Unknown Source:26)
	at c.ﾞˆ.ᵎᵎ.ˉᴵ(Unknown Source:36)
	at c.ﾞˆ.ᵎᵎ.ˏᵢ(Unknown Source:21)
	at c.יʼ.ʾﹳ.ﹳˏ(Unknown Source:933)
	at c.יʼ.ʾﹳ.ʾﹳ(Unknown Source:30)
	at c.ﹳˏ.ﹶᵎ.ʾי(Unknown Source:59)
	at c.ﹳˏ.ﹶᵎ.hook(Unknown Source:201)
	at c.ﹳˏ.ﾞˆ.hook(Unknown Source:0)
	at c.ﹳˏ.ᐧʼ.ˆʿ(Unknown Source:62)
	at c.ﹳˏ.ᐧʼ.hook(Unknown Source:20)
	at java.lang.reflect.Method.invoke(Native Method)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.callMethod(SourceFile:2)
	at x.ᴵˊ.ᵔ.ʻʻ(Unknown Source:271)
	at x.ᴵˊ.ᵔ.ⁱᴵ(Unknown Source:1)
	at x.ᴵˊ.ﹳﹶ.ˊ(Unknown Source:0)
	at x.ᴵˊ.ﹳﹶ.ʾʻ(Unknown Source:48)
	at x.ⁱᵎ.ᵎˉ.ˊ(Unknown Source:2)
	at x.ᴵˊ.ˊ.ᵔ(Unknown Source:607)
	at x.ᴵˊ.ˊ.ﹳˏ(Unknown Source:0)
	at x.ᴵˊ.ˊ$ˑʾ.afterHookedMethod(Unknown Source:61)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.attachBaseContext(Unknown Source:11)
	at android.app.Application.attach(Application.java:361)
	at java.lang.reflect.Method.invoke(Native Method)
	at WcpRaMXvm.ZoLvGqzTBqyNaI.R.vn.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1252)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1512)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1444)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7195)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8399)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.NoSuchMethodError: com.tencent.mm.storage.u1#e(int,java.lang.Object)#exact
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.lambda$findMethodExact$3(Unknown Source:6)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.h(Unknown Source:0)
	at MDIQsCx.kNJI.YEROBMoRJ.c.get(Unknown Source:13)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.findMethodExact(SourceFile:1)
	at MDIQsCx.kNJI.YEROBMoRJ.XposedHelpers.findAndHookMethod(SourceFile:1)
	at java.lang.reflect.Method.invoke(Native Method)
	at c.ﾞˆ.ﹶʽ.ˋʼ(Unknown Source:14)
	... 41 more
[ 2023-09-04T01:23:12.275    10260:  5392:  5392 I/LSPosed-Bridge  ] WeXposed: hook failed: class com.tencent.mm.storage.u1
[ 2023-09-04T01:23:12.275    10260:  5392:  5392 I/LSPosed-Bridge  ] WeXposed: class com.tencent.mm.storage.u1.e.int.java.lang.Object

### Expected behaviour/预期行为

Update 1.9.1 caused the wx module and Yangtze River 9 module to be unavailable, resulting in douyin and WeChat stuck and unable to open the program normally

### Actual behaviour/实际行为

douyin and WeChat stuck and unable to open the program normally

### Xposed Module List/Xposed 模块列表

```shell
com.fkzhang.wechatxposed
com.plus.tim.mainactivity
```

### Magisk Module List/Magisk 模块列表

```shell
zygisk-lsposed
shamiko
```

### LSPosed version/LSPosed 版本

1.9.1(6990)

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26.1(26100)

### Riru version/Riru 版本

Zygisk

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-09-04T01_23_54.982113.zip](https://github.com/LSPosed/LSPosed/files/12508724/LSPosed_2023-09-04T01_23_54.982113.zip)

**Comment by yujincheng08** [comment]
Modules' issue

**Comment by Howard20181** [comment]
![Screenshot_2023-09-04-10-43-23-372_com.android.shell.jpg](https://github.com/LSPosed/LSPosed/assets/40033067/250e2b24-fbe4-47a4-9a46-af8667c271b9)

**Comment by nasheep** [comment]
There does seem to be a problem with the latest version 1.9.1. If the module fails after the upgrade, you can find the directory /data/apex/active, delete the files in the folder, reinstall the framework and restart.

**Comment by amakuramio** [comment]
> There does seem to be a problem with the latest version 1.9.1. If the module fails after the upgrade, you can find the directory /data/apex/active, delete the files in the folder, reinstall the framework and restart.

OH MY! ALL MY MODULES INCLUDING XPL WORK AGAIN! THANK YOU!
