### ISSUE TITLE
[Bug] Resource hooks not available on Android 14

### ISSUE THREAD

**Issue by alroy214** [LSPosed/LSPosed#2752]
### Steps to reproduce/复现步骤

1. Install the latest version of Pixel 7 Pro Android 14 (Beta 4).
2. Install a module that uses resource hooks (i.e. Xposed Edge/self made modules).
3. The module will run but the resource hooks never load.
4. :( ask for help cause the fix will help with a lot of programs I use.

### Expected behaviour/预期行为

The modules should run with the resource hooks enabled.

### Actual behaviour/实际行为

Resource hooks aren't available during loading the app/module.

### Xposed Module List/Xposed 模块列表

```shell
Xposed Egdge Pro.
```

### Magisk Module List/Magisk 模块列表

```shell
Zygisk-LSPosed
substratum like overlay helper
```

### LSPosed version/LSPosed 版本

6990

### Android version/Android 版本

14 (API 34)

### Magisk version/Magisk 版本

26.3

### Riru version/Riru 版本

NA

### Version requirement/版本要求

- [x] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-09-11T17_45_13.767918.zip](https://github.com/LSPosed/LSPosed/files/12577619/LSPosed_2023-09-11T17_45_13.767918.zip)
[LSPosed_2023-09-11T17_45_16.992710.zip](https://github.com/LSPosed/LSPosed/files/12577622/LSPosed_2023-09-11T17_45_16.992710.zip)

**Comment by alroy214** [comment]
[LSPosed_2023-09-12T09_46_10.426644.zip](https://github.com/LSPosed/LSPosed/files/12583240/LSPosed_2023-09-12T09_46_10.426644.zip)
[LSPosed_2023-09-12T09_45_57.483557.zip](https://github.com/LSPosed/LSPosed/files/12583257/LSPosed_2023-09-12T09_45_57.483557.zip)

@Howard20181 
Updated to latest beta and uploaded logs again.

**Comment by BlueCat300** [comment]
Сonfirm the problem. Appeared even on Android 13 after firmware update with security patch from **August 1, 2023**.

**Comment by yujincheng08** [comment]
> The module will run but the resource hooks never load.

```
[ 2023-09-12T09:43:28.302    10225: 10854: 10854 E/LSPosed-Bridge  ] android.content.res.Resources$NotFoundException: com.android.systemui:layout/quick_qs_status_icons
	at android.content.res.XResources.hookLayout(XResources.java:1699)
	at com.drsants.eggproject.po.Node.handleInitPackageResources(Unknown Source:64)
	at de.robv.android.xposed.IXposedHookInitPackageResources$Wrapper.handleInitPackageResources(IXposedHookInitPackageResources.java:33)
	at de.robv.android.xposed.callbacks.XC_InitPackageResources.call(XC_InitPackageResources.java:88)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:148)
	at de.robv.android.xposed.XposedInit.cloneToXResources(XposedInit.java:212)
	at de.robv.android.xposed.XposedInit.-$$Nest$smcloneToXResources(Unknown Source:0)
	at de.robv.android.xposed.XposedInit$2.afterHookedMethod(XposedInit.java:133)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(XposedBridge.java:430)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:192)
	at LSPHooker_.createResources(Unknown Source:17)
	at android.app.ResourcesManager.getResources(ResourcesManager.java:1138)
	at android.app.LoadedApk.getResources(LoadedApk.java:1371)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3324)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3316)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6879)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

From the log, it shows resource hook actually loads, but the module is not compatible with new OS.

**Comment by alroy214** [comment]
[Uploading LSPosed_2023-09-19T09_26_32.893978.zip…]()
I'm wondering how themer gets to "hook" cause non of my other apps including the ones I program manager to hook resources, can you cheek if any resource hooks works on your device? 
This problem has been confirmed by more people and a lot of apps including my code that works on A13 doesn't even load resources hooks now, I think it only loads system hooks
