### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Dimon-015** [LSPosed/LSPosed#2767]
### Steps to reproduce/复现步骤

Select Chrome's webview and try to open any module in the LSPosed repository.

### Expected behaviour/预期行为

The page with the module in the repository should load.

### Actual behaviour/实际行为

LSPosed crashes.

### Xposed Module List/Xposed 模块列表

```shell
AnyWebview
```

### Magisk Module List/Magisk 模块列表

```shell
Zygisk- LSPosed
```

### LSPosed version/LSPosed 版本

6997

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26301

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-09-23T16_19_43.524336.zip](https://github.com/LSPosed/LSPosed/files/12706525/LSPosed_2023-09-23T16_19_43.524336.zip)
Generated by AppErrorsTracking
Project Url: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Xiaomi
[Device Model]: M2007J3SY
[Display]: TQ2A.230505.002
[Android Version]: 13
[Android API Level]: 33
[System Locale]: ru_RU
[Process ID]: 9269
[CPU ABI]: none
[Package Name]: com.android.shell
[Version Name]: 13
[Version Code]: 33
[Error Type]: JVM
[Crash Time]: 2023-09-23T16:06:01.851
[Stack Trace]:
Tb.bxquDS.DMfyDIuV.l.l.XposedHelpers$InvocationTargetError: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Tried to load an invalid WebView provider: com.android.chrome
 at Tb.bxquDS.DMfyDIuV.l.l.XposedHelpers.callStaticMethod(SourceFile:2)
 at B0.replaceHookedMethod(Unknown Source:47)
 at Tb.bxquDS.DMfyDIuV.l.l.XC_MethodReplacement.beforeHookedMethod(Unknown Source:0)
 at Tb.bxquDS.DMfyDIuV.l.l.XposedBridge$LegacyApiSupport.handleBefore(Unknown Source:24)
 at J.callback(Unknown Source:179)
 at LSPHooker_.getProvider(Unknown Source:5)
 at android.webkit.WebView.getFactory(WebView.java:2594)
 at android.webkit.WebView.ensureProviderCreated(WebView.java:2588)
 at android.webkit.WebView.setOverScrollMode(WebView.java:2656)
 at android.view.View.<init>(View.java:5370)
 at android.view.View.<init>(View.java:5511)
 at android.view.ViewGroup.<init>(ViewGroup.java:703)
 at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
 at android.webkit.WebView.<init>(WebView.java:421)
 at android.webkit.WebView.<init>(WebView.java:363)
 at android.webkit.WebView.<init>(WebView.java:345)
 at android.webkit.WebView.<init>(WebView.java:332)
 at android.webkit.WebView.<init>(WebView.java:322)
 at V7.run(Unknown Source:33)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7925)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Tried to load an invalid WebView provider: com.android.chrome
 at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:532)
 at java.lang.reflect.Method.invoke(Native Method)
 ... 27 more
Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Tried to load an invalid WebView provider: com.android.chrome
 at android.webkit.WebViewFactory.verifyPackageInfo(WebViewFactory.java:404)
 at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:461)
 at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:493)
 ... 28 more

**Comment by Dimon-015** [comment]
Full, new logs from the debug version, if you insist.

Generated by AppErrorsTracking
Project Url: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Xiaomi
[Device Model]: M2007J3SY
[Display]: TQ2A.230505.002
[Android Version]: 13
[Android API Level]: 33
[System Locale]: ru_RU
[Process ID]: 1824
[CPU ABI]: none
[Package Name]: com.android.shell
[Version Name]: 13
[Version Code]: 33
[Error Type]: JVM
[Crash Time]: 2023-09-23T16:43:32.724
[Stack Trace]:
NtF.k.e.LXPwbSEf.KC.kB.XposedHelpers$InvocationTargetError: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Tried to load an invalid WebView provider: com.android.chrome
	at NtF.k.e.LXPwbSEf.KC.kB.XposedHelpers.callStaticMethod(XposedHelpers.java:1507)
	at org.lsposed.lspd.util.ParasiticManagerHooker$7.replaceHookedMethod(ParasiticManagerHooker.java:266)
	at NtF.k.e.LXPwbSEf.KC.kB.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:51)
	at NtF.k.e.LXPwbSEf.KC.kB.XposedBridge$LegacyApiSupport.handleBefore(XposedBridge.java:404)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:152)
	at LSPHooker_.getProvider(Unknown Source:5)
	at android.webkit.WebView.getFactory(WebView.java:2594)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2588)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2656)
	at android.view.View.<init>(View.java:5370)
	at android.view.View.<init>(View.java:5511)
	at android.view.ViewGroup.<init>(ViewGroup.java:703)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
	at android.webkit.WebView.<init>(WebView.java:421)
	at android.webkit.WebView.<init>(WebView.java:363)
	at android.webkit.WebView.<init>(WebView.java:345)
	at android.webkit.WebView.<init>(WebView.java:332)
	at android.webkit.WebView.<init>(WebView.java:322)
	at org.lsposed.manager.ui.fragment.RepoFragment.lambda$onResume$4(RepoFragment.java:225)
	at org.lsposed.manager.ui.fragment.RepoFragment.$r8$lambda$0b9aVhLZ32sqPsrbw9-NdYmP_pQ(Unknown Source:0)
	at org.lsposed.manager.ui.fragment.RepoFragment$$ExternalSyntheticLambda5.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7925)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Tried to load an invalid WebView provider: com.android.chrome
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:532)
	at java.lang.reflect.Method.invoke(Native Method)
	at NtF.k.e.LXPwbSEf.KC.kB.XposedHelpers.callStaticMethod(XposedHelpers.java:1499)
	... 28 more
Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Tried to load an invalid WebView provider: com.android.chrome
	at android.webkit.WebViewFactory.verifyPackageInfo(WebViewFactory.java:404)
	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:461)
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:493)
	... 30 more
[LSPosed_2023-09-23T16_31_33.560085.zip](https://github.com/LSPosed/LSPosed/files/12706577/LSPosed_2023-09-23T16_31_33.560085.zip)

**Comment by Dimon-015** [comment]
[Device Brand]: Xiaomi
[Device Model]: M2007J3SY
[Display]: TQ2A.230505.002
[Android Version]: 13
[Android API Level]: 33
[System Locale]: ru_RU
[Process ID]: 8106
[CPU ABI]: none
[Package Name]: com.android.shell
[Version Name]: 13
[Version Code]: 33
[Error Type]: JVM
[Crash Time]: 2023-09-23T16:45:12.693
[Stack Trace]:
NtF.k.e.LXPwbSEf.KC.kB.XposedHelpers$InvocationTargetError: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Tried to load an invalid WebView provider: com.android.chrome
	at NtF.k.e.LXPwbSEf.KC.kB.XposedHelpers.callStaticMethod(XposedHelpers.java:1507)
	at org.lsposed.lspd.util.ParasiticManagerHooker$7.replaceHookedMethod(ParasiticManagerHooker.java:266)
	at NtF.k.e.LXPwbSEf.KC.kB.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:51)
	at NtF.k.e.LXPwbSEf.KC.kB.XposedBridge$LegacyApiSupport.handleBefore(XposedBridge.java:404)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:152)
	at LSPHooker_.getProvider(Unknown Source:5)
	at android.webkit.WebView.getFactory(WebView.java:2594)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2588)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2656)
	at android.view.View.<init>(View.java:5370)
	at android.view.View.<init>(View.java:5511)
	at android.view.ViewGroup.<init>(ViewGroup.java:703)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
	at android.webkit.WebView.<init>(WebView.java:421)
	at android.webkit.WebView.<init>(WebView.java:363)
	at android.webkit.WebView.<init>(WebView.java:345)
	at android.webkit.WebView.<init>(WebView.java:332)
	at android.webkit.WebView.<init>(WebView.java:322)
	at org.lsposed.manager.ui.fragment.RepoFragment.lambda$onResume$4(RepoFragment.java:225)
	at org.lsposed.manager.ui.fragment.RepoFragment.$r8$lambda$0b9aVhLZ32sqPsrbw9-NdYmP_pQ(Unknown Source:0)
	at org.lsposed.manager.ui.fragment.RepoFragment$$ExternalSyntheticLambda5.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7925)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Tried to load an invalid WebView provider: com.android.chrome
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:532)
	at java.lang.reflect.Method.invoke(Native Method)
	at NtF.k.e.LXPwbSEf.KC.kB.XposedHelpers.callStaticMethod(XposedHelpers.java:1499)
	... 28 more
Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Tried to load an invalid WebView provider: com.android.chrome
	at android.webkit.WebViewFactory.verifyPackageInfo(WebViewFactory.java:404)
	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:461)
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:493)
	... 30 more

**Comment by yujincheng08** [comment]
I dont thing there's something to do with LSPosed.

https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/webkit/WebViewFactory.java;drc=0643c022edb3d6e5a8f0a32e1344a13d39ec8adb;l=403

**Comment by Dimon-015** [comment]
![Screenshot_20230923-164726_Настройки](https://github.com/LSPosed/LSPosed/assets/114181146/58dd980c-88a7-4b0e-a323-9a370150a3ca)
LSPosed crashes specifically when selecting Chrome's webview.

**Comment by vvb2060** [comment]
I believe chrome is not a webview

**Comment by Dimon-015** [comment]
> I believe chrome is not a webview

As you can see, Chrome can be used as a webview and it is much more efficient and faster than Android System WebView. LSPosed simply does not support it, which is why it crashes. It should not be like this...

**Comment by vvb2060** [comment]
Give us a supporting app

**Comment by Howard20181** [comment]
@Dimon-015 download via browser which use system webview you selected as core to check if it work

**Comment by Howard20181** [comment]
@Dimon-015 https://play.google.com/store/apps/details?id=mark.via.gp

**Comment by Dimon-015** [comment]
> Give us an app that supports Chrome as webview

EzMod, vk mp3 For example.

**Comment by yujincheng08** [comment]
[Google Chrome app is no longer the WebView provider in Android 10](https://www.xda-developers.com/google-chrome-no-longer-webview-provider-android-10/)

**Comment by Dimon-015** [comment]
> [Google Chrome app is no longer the WebView provider in Android 10](https://www.xda-developers.com/google-chrome-no-longer-webview-provider-android-10/)

You need to install version 1.1. AnyWebView

**Comment by vvb2060** [comment]
The crash log has clearly shown that the system found that chrome cannot be used as a webview. Please stop.

**Comment by yujincheng08** [comment]
> You need to install version 1.1. AnyWebView

AnyWebView allows you to select Chrome as Webview, but it does not ensure Chrome will work as Webview.

**Comment by vvb2060** [comment]
This issue is locked, if you want to continue, please go to https://github.com/neoblackxt/AnyWebView/issues/12
