### ISSUE TITLE
Modules not working

### ISSUE THREAD

**Issue by bVidDa** [LSPosed/LSPosed#2776]
### Steps to reproduce/复现步骤

Just install latest Stable Release, or Canary Build,
Install latest CorePatch, activate and reboot.

### Expected behaviour/预期行为

Should be able to install modified APKs

### Actual behaviour/实际行为

I'm getting an error when trying to install a modified apk.
Also, in LuckyPatcher indicates the module is not active.

### Xposed Module List/Xposed 模块列表

```shell
LuckyPatcher
CorePatch
```

### Magisk Module List/Magisk 模块列表

```shell
Zygisk
LSposed
```

### LSPosed version/LSPosed 版本

6990/6999

### Android version/Android 版本

11

### Magisk version/Magisk 版本

26.3

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [ ] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[ 2023-10-03T04:26:09.984     1000:  1200:  1200 I/LSPosed-Bridge  ]   Loading class com.chelpus.XSupport
[ 2023-10-03T04:26:14.464     1000:  1200:  1200 E/LSPosed-Bridge  ] java.lang.ClassCastException: com.android.server.pm.PackageManagerService$Injector cannot be cast to android.content.Context
	at com.chelpus.XSupport$8.afterHookedMethod(XSupport.java:342)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.constructor(Unknown Source:25)
	at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:2702)
	at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:970)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.startBootstrapServices(Unknown Source:11)
	at com.android.server.SystemServer.run(SystemServer.java:703)
	at com.android.server.SystemServer.main(SystemServer.java:439)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

Logd maybe crashed (err=Socket operation on non-socket), retrying in 1s...

Logd maybe crashed (err=Socket operation on non-socket), retrying in 1s...

**Comment by bVidDa** [comment]
Is there something I can do to make it work ?
Why does this only happen to me ?
Am I missing something ?

**Comment by amakuramio** [comment]
For all people having problems with module: try to delete /root/data/apex/active, reinstall lsposed, then after ''optimizing'' all will work. It worked for me. Thanks Nasheep.
