### ISSUE TITLE
Clash royale doesn't work🤡

### ISSUE THREAD

**Issue by YurKa336** [LSPosed/LSPosed#2792]
### Steps to reproduce/复现步骤

After the last update the game stopped launching.  If I remove lsposed or disable zygisk in magisk, the game starts and works.  I don’t know what’s wrong, but it’s definitely not a matter of lsposed modules, since it doesn’t work without them.
![Screenshot_2023-10-06-23-11-16-836_com miui bugreport](https://github.com/LSPosed/LSPosed/assets/107347313/65c889fd-04b8-430c-b218-9a38eddd8e16)
![Screenshot_2023-10-06-23-11-19-747_com miui bugreport](https://github.com/LSPosed/LSPosed/assets/107347313/8fec9ad3-e139-494d-9760-7b86b5dceb6d)

gwioaeelm.ab: 16
	at gwioaeelm.al.b(Unknown Source:75)
	at gwioaeelm.al.a(Unknown Source:0)
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.nativeLoad(Runtime.java:1126)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1080)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at gwioaeelm.as.c(Unknown Source:166)
	at gwioaeelm.as.b(Unknown Source:3)
	at gwioaeelm.as.a(Unknown Source:24)
	at gwioaeelm.as.a(Unknown Source:6)
	at gwioaeelm.as.<clinit>(Unknown Source:0)
	at androidx.core.app.CoreComponentFactory.<clinit>(Unknown Source:0)
	at java.lang.Class.newInstance(Native Method)
	at android.app.LoadedApk.createAppFactory(LoadedApk.java:282)
	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1052)
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1139)
	at android.app.LoadedApk.getResources(LoadedApk.java:1398)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3100)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3092)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6996)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8296)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

### Expected behaviour/预期行为

.

### Actual behaviour/实际行为

.

### Xposed Module List/Xposed 模块列表

```shell
Cistomiuizer14
Cemiuiler
```

### Magisk Module List/Magisk 模块列表

```shell
Bcr
Drc remover
Ios emoji font
Shamiko
Universal safetynet fix
Viper4android fx repackagedhoch
Zygisk - lsposed
```

### LSPosed version/LSPosed 版本

6990

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26.3

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-10-06T23_31_43.349041.zip](https://github.com/LSPosed/LSPosed/files/12835298/LSPosed_2023-10-06T23_31_43.349041.zip)

**Comment by yujincheng08** [comment]
![Screenshot_2023-10-07-04-37-46-277_com miui home](https://github.com/LSPosed/LSPosed/assets/5022927/a9da288f-5fa8-456a-beb5-24d89a734e0e)

**Comment by LeanderGlanda** [comment]
I have the same issue, why was this closed? Is there any way I could help with solving this?

**Comment by LeanderGlanda** [comment]
Never mind, if anyone else has this issue: install the latest build of LSPosed, it fixes the issue.

**Comment by pokemaster974** [comment]
My CR is also crashing since about 5 days.
It's very weird, because it's also happpens on prior versions like 1.8.6.

But yeah, using a more recent version than 1.9.1 seems to fix the issue.
Thanks @LeanderGlanda !

For information, 2 apps (at least) were affected by the same issue : Clash Royale but also Lawnchair.

**Comment by akano12** [comment]
> My CR is also crashing since about 5 days.
> It's very weird, because it's also happpens on prior versions like 1.8.6.
> 
> But yeah, using a more recent version than 1.9.1 seems to fix the issue.
> Thanks @LeanderGlanda !
> 
> For information, 2 apps (at least) were affected by the same issue : Clash Royale but also Lawnchair.

Is it still working? Just tried latest nighty build of lsposed and clash royale crashed

**Comment by akano12** [comment]
> Never mind, if anyone else has this issue: install the latest build of LSPosed, it fixes the issue. You get the built binary from the CI

Same question as above

**Comment by LeanderGlanda** [comment]
> > Never mind, if anyone else has this issue: install the latest build of LSPosed, it fixes the issue. You get the built binary from the CI
> 
> Same question as above

Yes, Clash Royale still works for me, but I haven't updated LSPosed since I wrote my reply in here.
The version says v1.9.1 (7011) for me, maybe try that specific version.
