### ISSUE TITLE
enabling any module for system framework now results in system errors across the entire OxygenOS on OnePlus 7 Pro after updating LSPosed 

### ISSUE THREAD

**Issue by LoganDark** [LSPosed/LSPosed#2796]
### Steps to reproduce/复现步骤

enable any module for system framework

### Expected behaviour/预期行为

no crash 

### Actual behaviour/实际行为

system update crashes
```
FATAL EXCEPTION: Thread-8
Process: com.oneplus.opbackup, PID: 9601
android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:197)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:930)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:910)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:774)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:763)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:374)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)
	at com.oneplus.opbackup.a.c.a(OperatorDao.java:109)
	at com.oneplus.opbackup.receiver.SIMCardStateReceiver.a(SIMCardStateReceiver.java:83)
	at com.oneplus.opbackup.receiver.SIMCardStateReceiver.a(SIMCardStateReceiver.java:28)
	at com.oneplus.opbackup.receiver.SIMCardStateReceiver$1.a(SIMCardStateReceiver.java:42)
	at com.oneplus.opbackup.receiver.a.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:919)
```

opconfig crashes
```
FATAL EXCEPTION: ConfigDatabaseWorker
Process: com.oneplus.config, PID: 2254
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.database.sqlite.SQLiteDatabase.endTransaction()' on a null object reference
	at com.oneplus.config.ConfigProvider.delete(Unknown Source:36)
	at android.content.ContentProvider$Transport.delete(ContentProvider.java:438)
	at android.content.ContentResolver.delete(ContentResolver.java:1989)
	at com.oneplus.config.server.b.handleMessage(Unknown Source:42)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

dolby atmos crashes
```
FATAL EXCEPTION: main
Process: com.oneplus.sound.tuner, PID: 11759
android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:197)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:930)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:910)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:774)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:763)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:384)
	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:341)
	at com.oneplus.sound.tuner.HeadphoneManager.getOnlineConfigEarphoneInfo(HeadphoneManager.java:311)
	at com.oneplus.sound.tuner.BluetoothDeviceManager.updateDevicesOnlineConfig(BluetoothDeviceManager.java:165)
	at com.oneplus.sound.tuner.BluetoothDeviceManager.<init>(BluetoothDeviceManager.java:44)
	at com.oneplus.sound.tuner.BluetoothDeviceManager.getInstance(BluetoothDeviceManager.java:51)
	at com.oneplus.sound.tuner.SoundTunerService.saveCurrentDeviceInfo(SoundTunerService.java:516)
	at com.oneplus.sound.tuner.SoundTunerService.findMediaOutputDevice(SoundTunerService.java:450)
	at com.oneplus.sound.tuner.SoundTunerService.access$1500(SoundTunerService.java:55)
	at com.oneplus.sound.tuner.SoundTunerService$2.run(SoundTunerService.java:385)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

even Bluetooth crashes
```
FATAL EXCEPTION: BluetoothDatabaseManager
Process: com.android.bluetooth, PID: 9759
android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:197)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:930)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:910)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:774)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:763)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:374)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:452)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:275)
	at androidx.room.RoomDatabase.query(RoomDatabase.java:304)
	at com.android.bluetooth.btservice.storage.MetadataDao_Impl.load(MetadataDao_Impl.java:244)
	at com.android.bluetooth.btservice.storage.MetadataDatabase.load(MetadataDatabase.java:84)
	at com.android.bluetooth.btservice.storage.DatabaseManager$DatabaseHandler.handleMessage(DatabaseManager.java:102)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Xposed Module List/Xposed 模块列表

```shell
XPrivacyLua 0.35
```

### Magisk Module List/Magisk 模块列表

```shell
advanced charging controller ACC
shamiko v0.7.3 174
substratum
lsposed v1.9.1 6990
```

### LSPosed version/LSPosed 版本

1.9.1 6990

### Android version/Android 版本

10

### Magisk version/Magisk 版本

26.3 26300

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

i will in one moment

**Comment by qs-lll** [comment]
三星s8 oneplus   安装LSPosed-v1.9.2-7024-riru-release    进不去系统

**Comment by Karanveer7921** [comment]
I had similar issues, the app was crashing on startup. I am using HMA module, that requires system framework hook. I added that specific app into the deny list in magisk and it worked. 

using zygisk lsposed version
using shamiko

**Comment by thetzinaung135-coder** [comment]
FATAL EXCEPTION: ConfigDatabaseWorker
Process: com.oneplus.config, PID: 2254
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.database.sqlite.SQLiteDatabase.endTransaction()' on a null object reference
	at com.oneplus.config.ConfigProvider.delete(Unknown Source:36)
	at android.content.ContentProvider$Transport.delete(ContentProvider.java:438)
	at android.content.ContentResolver.delete(ContentResolver.java:1989)
	at com.oneplus.config.server.b.handleMessage(Unknown Source:42)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by thetzinaung135-coder** [comment]
https://github.com/KiminonawaResa/HyperLight/issues/275
