### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by JJ-Coffee** [LSPosed/LSPosed#2798]
### Steps to reproduce/复现步骤

Can not open clash of clans

### Expected behaviour/预期行为

Can not open clash of clans

### Actual behaviour/实际行为

COC always FC

### Xposed Module List/Xposed 模块列表

```shell
N/a
```

### Magisk Module List/Magisk 模块列表

```shell
Lsposed
```

### LSPosed version/LSPosed 版本

1.9.1(6990)

### Android version/Android 版本

11

### Magisk version/Magisk 版本

26.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

----part 2 start----
[ 2023-10-10T03:44:34.240        0:   520:  1089 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/verbose_2023-10-10T03:44:34.24.log
[ 2023-10-10T03:44:43.502        0: 16020: 16020 I/Magisk          ] zygisk64: [com.supercell.clashofclans] is on the hidelist
[ 2023-10-10T03:44:43.840     1000:  1369:  3352 W/LSPosed Bridge  ] on transact
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2382)
	at android.os.Parcel.createException(Parcel.java:2360)
	at android.os.Parcel.readException(Parcel.java:2343)
	at android.os.Parcel.readException(Parcel.java:2285)
	at C.g(Unknown Source:32)
	at Ngr.RdihGSDxBXmSwsI.jRrG.BridgeService.a(Unknown Source:69)
	at Ngr.RdihGSDxBXmSwsI.jRrG.BridgeService.execTransact(Unknown Source:22)
[ 2023-10-10T03:44:43.842    10260: 16020: 16020 E/AndroidRuntime  ] FATAL EXCEPTION: main
Process: com.supercell.clashofclans, PID: 16020
irzjrny.k: 16
	at irzjrny.W.a(Unknown Source:75)
	at irzjrny.W.b(Unknown Source:0)
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.nativeLoad(Runtime.java:1131)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1085)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
	at java.lang.System.loadLibrary(System.java:1664)
	at irzjrny.n.a(Unknown Source:166)
	at irzjrny.n.b(Unknown Source:3)
	at irzjrny.n.d(Unknown Source:24)
	at irzjrny.n.c(Unknown Source:6)
	at irzjrny.n.<clinit>(Unknown Source:0)
	at irzjrny.n.c(Unknown Source:0)
	at androidx.core.app.CoreComponentFactory.<clinit>(Unknown Source:0)
	at java.lang.Class.newInstance(Native Method)
	at android.app.LoadedApk.createAppFactory(LoadedApk.java:266)
	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:911)
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:964)
	at android.app.LoadedApk.getResources(LoadedApk.java:1196)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2672)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2664)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6878)
	at android.app.ActivityThread.access$1600(ActivityThread.java:263)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2034)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8057)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
[ 2023-10-10T03:45:51.433        0: 16829: 16829 I/Magisk          ] zygisk64: [org.telegram.messenger] is on the hidelist
[ 2023-10-10T03:45:51.965        0: 16915: 16915 I/Magisk          ] zygisk64: [com.android.vending] is on the hidelist
[ 2023-10-10T03:45:52.452        0: 17055: 17055 I/Magisk          ] zygisk64: [com.android.vending:background] is on the hidelist

**Comment by cptmacp** [comment]
can confirm this

**Comment by pokemaster974** [comment]
Dupe as #2792 
Using a debug version in Github Actions fixes the conflict in my case and for Clash Royale.
