### ISSUE TITLE
[BUG][32Bit][Bootloop] connect rirud failed with 111: Connection refused

### ISSUE THREAD

**Issue by BlueMax** [LSPosed/LSPosed#284]
I get the errors below on bootloop. Last version tested is LSPosed-v1.2.1-5416-release.zip. The log below is from v1.1.0 but its the same on 1.2.0.

Anything i can do?

Samsung I9506
LOS18.1 (03/2021)
Magisk v22
Riru v23.9
```
03-02 17:19:15.184  6711  6711 E Riru    : connect rirud failed with 111: Connection refused
03-02 17:19:16.110  4896  4896 E iorapd  : Cannot get package manager service!
03-02 17:19:16.184  6711  6711 E Riru    : connect rirud failed with 111: Connection refused
03-02 17:19:17.184  6711  6711 E Riru    : connect rirud failed with 111: Connection refused
03-02 17:19:18.184  6711  6711 E Riru    : connect rirud failed with 111: Connection refused
03-02 17:19:19.185  6711  6711 E Riru    : connect rirud failed with 111: Connection refused
03-02 17:19:20.185  6711  6711 E Riru    : connect rirud failed with 111: Connection refused
03-02 17:19:21.185  6711  6711 E Riru    : connect rirud failed with 111: Connection refused
03-02 17:19:22.128  4896  4896 E iorapd  : Cannot get package manager service!
03-02 17:19:22.185  6711  6711 E Riru    : connect rirud failed with 111: Connection refused
03-02 17:19:23.185  6711  6711 E Riru    : connect rirud failed with 111: Connection refused
03-02 17:19:24.186  6711  6711 E Riru    : connect rirud failed with 111: Connection refused
03-02 17:19:25.198  6711  6711 E Riru    : connect rirud failed with 111: Connection refused
03-02 17:19:25.199  6711  6711 E linker  : "/system/lib/libriru_c3c7.so": ignoring DT_PREINIT_ARRAY in shared library!
03-02 17:19:25.201  6711  6711 E Riru    : access /system/lib/libriru_cbe7.so failed with 2: No such file or directory
03-02 17:19:25.201  6711  6711 E LSPosed : Connection refused
03-02 17:19:25.244  6711  6711 E Riru    : connect rirud failed with 111: Connection refused
03-02 17:19:25.319  6711  6711 E Riru    : connect rirud failed with 111: Connection refused
03-02 17:19:25.319  6711  6711 E Riru    : connect rirud failed with 111: Connection refused
03-02 17:19:25.320  6711  6711 E Riru    : connect rirud failed with 111: Connection refused
03-02 17:19:25.928  6711  6711 E ActivityRecognitionHardware: activity_recognition HAL is deprecated. class_init is effectively a no-op
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #03 pc 00425027  /apex/com.android.art/lib/libart.so (art::SignalCatcher::Run(void*)+194)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #04 pc 000ab97b  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+40)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #05 pc 00063b5d  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   (no managed stack frames)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655] "perfetto_hprof_listener" prio=10 tid=3 Native (still starting up)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   | group="" sCount=1 dsCount=0 flags=1 obj=0x0 self=0xaea90a00
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   | sysTid=6837 nice=-20 cgrp=default sched=0/0 handle=0x833961c0
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   | state=S schedstat=( 367969 0 7 ) utm=0 stm=0 core=0 HZ=100
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   | stack=0x8329b000-0x8329d000 stackSize=1008KB
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   | held mutexes=
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #00 pc 0009b7d8  /apex/com.android.runtime/lib/bionic/libc.so (read+8)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #01 pc 0000dc01  /apex/com.android.art/lib/libperfetto_hprof.so (void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ArtPlugin_Initialize::$_29> >(void*)+208)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #02 pc 000ab97b  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+40)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #03 pc 00063b5d  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   (no managed stack frames)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655] "ADB-JDWP Connection Control Thread" prio=10 tid=4 WaitingInMainDebuggerLoop
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   | group="" sCount=1 dsCount=0 flags=1 obj=0x12c00168 self=0xaea91800
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   | sysTid=6838 nice=-20 cgrp=default sched=0/0 handle=0x8328e1c0
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   | state=S schedstat=( 422293 0 7 ) utm=0 stm=0 core=0 HZ=100
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   | stack=0x83193000-0x83195000 stackSize=1008KB
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   | held mutexes=
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #00 pc 0009cc6c  /apex/com.android.runtime/lib/bionic/libc.so (__ppoll+20)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #01 pc 0006a8eb  /apex/com.android.runtime/lib/bionic/libc.so (poll+54)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #02 pc 000080b1  /apex/com.android.art/lib/libadbconnection.so (adbconnection::AdbConnectionState::RunPollLoop(art::Thread*)+604)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #03 pc 00006d63  /apex/com.android.art/lib/libadbconnection.so (adbconnection::CallbackFunction(void*)+1214)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #04 pc 000ab97b  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+40)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #05 pc 00063b5d  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   (no managed stack frames)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655] Aborting thread:
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655] "main" prio=5 tid=1 Native
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   | group="" sCount=0 dsCount=0 flags=0 obj=0x728ea100 self=0xaea8ee00
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   | sysTid=6830 nice=0 cgrp=default sched=0/0 handle=0xaef20470
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   | state=R schedstat=( 127971251 2837658 58 ) utm=6 stm=6 core=3 HZ=100
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   | stack=0xbe6d2000-0xbe6d4000 stackSize=8192KB
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   | held mutexes= "abort lock"
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #00 pc 00379f4d  /apex/com.android.art/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+76)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #01 pc 0044ba21  /apex/com.android.art/lib/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+388)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #02 pc 00447167  /apex/com.android.art/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+34)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #03 pc 004189ff  /apex/com.android.art/lib/libart.so (art::AbortState::DumpThread(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, art::Thread*) const+30)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #04 pc 00409289  /apex/com.android.art/lib/libart.so (art::Runtime::Abort(char const*)+1952)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #05 pc 0000d989  /system/lib/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+48)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #06 pc 0000d295  /system/lib/libbase.so (android::base::LogMessage::~LogMessage()+224)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #07 pc 002963db  /apex/com.android.art/lib/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1962)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #08 pc 002c8c63  /apex/com.android.art/lib/libart.so (art::JNI<false>::GetStaticMethodID(_JNIEnv*, _jclass*, char const*, char const*)+1326)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #09 pc 0001bdd9  /system/lib/libriru_c3c7.so (???)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #10 pc 00018255  /system/lib/libriru_c3c7.so (???)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #11 pc 0000ada7  /system/lib/libriru.so (???)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #12 pc 0000ad01  /system/lib/libriru.so (nativeForkSystemServer(_JNIEnv*, _jclass*, unsigned int, unsigned int, _jintArray*, int, _jobjectArray*, long long, long long)+140)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #13 pc 00213b87  /system/framework/arm/boot-framework.oat (art_jni_trampoline+198)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #14 pc 00743e63  /system/framework/arm/boot-framework.oat (com.android.internal.os.ZygoteInit.forkSystemServer+1130)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #15 pc 00744cef  /system/framework/arm/boot-framework.oat (com.android.internal.os.ZygoteInit.main+1718)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #16 pc 000d37d5  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub_internal+68)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #17 pc 004f71d1  /apex/com.android.art/lib/libart.so (art_quick_invoke_static_stub+276)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #18 pc 0012beb1  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+160)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #19 pc 00402625  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+348)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #20 pc 004028d7  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+42)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #21 pc 00329753  /apex/com.android.art/lib/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+530)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #22 pc 0006688d  /system/lib/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+28)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #23 pc 0006c50b  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+514)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #24 pc 00002e19  /system/bin/app_process32 (main+992)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   native: #25 pc 0005cecb  /apex/com.android.runtime/lib/bionic/libc.so (__libc_init+66)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   at com.android.internal.os.Zygote.nativeForkSystemServer(Native method)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   at com.android.internal.os.Zygote.forkSystemServer(Zygote.java:465)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   at com.android.internal.os.ZygoteInit.forkSystemServer(ZygoteInit.java:781)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:920)
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:655]
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:663] JNI DETECTED ERROR IN APPLICATION: java_class == null
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:663]     in call to GetStaticMethodID
03-02 17:19:28.065  6830  6830 F system_server: runtime.cc:663]     from int com.android.internal.os.Zygote.nativeForkSystemServer(int, int, int[], int, int[][], long, long)
03-02 17:19:28.066  6830  6830 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 6830 (system_server), pid 6830 (system_server)
03-02 17:19:28.133  6841  6841 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-02 17:19:28.133  6841  6841 F DEBUG   : LineageOS Version: '18.1-20210206-UNOFFICIAL-ks01ltexx'
03-02 17:19:28.133  6841  6841 F DEBUG   : Build fingerprint: 'samsung/ks01ltexx/ks01lte:5.0.1/LRX22C/I9506XXSDPL2:user/release-keys'
03-02 17:19:28.133  6841  6841 F DEBUG   : Revision: '0'
03-02 17:19:28.133  6841  6841 F DEBUG   : ABI: 'arm'
03-02 17:19:28.135  6841  6841 F DEBUG   : Timestamp: 2021-03-02 17:19:28+0100
03-02 17:19:28.135  6841  6841 F DEBUG   : pid: 6830, tid: 6830, name: system_server  >>> zygote <<<
03-02 17:19:28.135  6841  6841 F DEBUG   : uid: 1000
03-02 17:19:28.135  6841  6841 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
03-02 17:19:28.135  6841  6841 F DEBUG   : Abort message: 'JNI DETECTED ERROR IN APPLICATION: java_class == null
03-02 17:19:28.135  6841  6841 F DEBUG   :     in call to GetStaticMethodID
03-02 17:19:28.135  6841  6841 F DEBUG   :     from int com.android.internal.os.Zygote.nativeForkSystemServer(int, int, int[], int, int[][], long, long)'
03-02 17:19:28.135  6841  6841 F DEBUG   :     r0  00000000  r1  00001aae  r2  00000006  r3  beecec18
03-02 17:19:28.135  6841  6841 F DEBUG   :     r4  beecec2c  r5  beecec10  r6  00001aae  r7  0000016b
03-02 17:19:28.135  6841  6841 F DEBUG   :     r8  beecec18  r9  beecec28  r10 beecec48  r11 beecec38
03-02 17:19:28.136  6841  6841 F DEBUG   :     ip  00001aae  sp  beecebe8  lr  ab076631  pc  ab076644
03-02 17:19:28.149  4896  4896 E iorapd  : Cannot get package manager service!
03-02 17:19:28.331  6841  6841 F DEBUG   : backtrace:
03-02 17:19:28.331  6841  6841 F DEBUG   :       #00 pc 00062644  /apex/com.android.runtime/lib/bionic/libc.so (abort+172) (BuildId: 310183375f23e99e40c9ab529416d05f)
03-02 17:19:28.331  6841  6841 F DEBUG   :       #01 pc 00409189  /apex/com.android.art/lib/libart.so (art::Runtime::Abort(char const*)+1696) (BuildId: 0a902c3faf12314cc2e96d1ceb898f83)
03-02 17:19:28.331  6841  6841 F DEBUG   :       #02 pc 0000d989  /system/lib/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+48) (BuildId: 7ccbe65446774e9451e73051613c2ecb)
03-02 17:19:28.331  6841  6841 F DEBUG   :       #03 pc 0000d295  /system/lib/libbase.so (android::base::LogMessage::~LogMessage()+224) (BuildId: 7ccbe65446774e9451e73051613c2ecb)
03-02 17:19:28.332  6841  6841 F DEBUG   :       #04 pc 002963db  /apex/com.android.art/lib/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1962) (BuildId: 0a902c3faf12314cc2e96d1ceb898f83)
03-02 17:19:28.332  6841  6841 F DEBUG   :       #05 pc 002c8c63  /apex/com.android.art/lib/libart.so (art::JNI<false>::GetStaticMethodID(_JNIEnv*, _jclass*, char const*, char const*)+1326) (BuildId: 0a902c3faf12314cc2e96d1ceb898f83)
03-02 17:19:28.332  6841  6841 F DEBUG   :       #06 pc 0001bdd9  /system/lib/libriru_c3c7.so (BuildId: 905307a6fb1987af276928913f76adc885bb10a2)
03-02 17:19:28.332  6841  6841 F DEBUG   :       #07 pc 00018255  /system/lib/libriru_c3c7.so (BuildId: 905307a6fb1987af276928913f76adc885bb10a2)
03-02 17:19:28.332  6841  6841 F DEBUG   :       #08 pc 0000ada7  /system/lib/libriru.so (BuildId: 79996481344be5670952992bf11ec6efc9480e2f)
03-02 17:19:28.332  6841  6841 F DEBUG   :       #09 pc 0000ad01  /system/lib/libriru.so (nativeForkSystemServer(_JNIEnv*, _jclass*, unsigned int, unsigned int, _jintArray*, int, _jobjectArray*, long long, long long)+140) (BuildId: 79996481344be5670952992bf11ec6efc9480e2f)
03-02 17:19:28.332  6841  6841 F DEBUG   :       #10 pc 00213b87  /system/framework/arm/boot-framework.oat (art_jni_trampoline+198) (BuildId: 9d0bed2c715fc6bbe9d643eb58214402c75493bc)
03-02 17:19:28.333  6841  6841 F DEBUG   :       #11 pc 00743e63  /system/framework/arm/boot-framework.oat (com.android.internal.os.ZygoteInit.forkSystemServer+1130) (BuildId: 9d0bed2c715fc6bbe9d643eb58214402c75493bc)
03-02 17:19:28.333  6841  6841 F DEBUG   :       #12 pc 00744cef  /system/framework/arm/boot-framework.oat (com.android.internal.os.ZygoteInit.main+1718) (BuildId: 9d0bed2c715fc6bbe9d643eb58214402c75493bc)
03-02 17:19:28.333  6841  6841 F DEBUG   :       #13 pc 000d37d5  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 0a902c3faf12314cc2e96d1ceb898f83)
03-02 17:19:28.333  6841  6841 F DEBUG   :       #14 pc 004f71d1  /apex/com.android.art/lib/libart.so (art_quick_invoke_static_stub+276) (BuildId: 0a902c3faf12314cc2e96d1ceb898f83)
03-02 17:19:28.333  6841  6841 F DEBUG   :       #15 pc 0012beb1  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+160) (BuildId: 0a902c3faf12314cc2e96d1ceb898f83)
03-02 17:19:28.333  6841  6841 F DEBUG   :       #16 pc 00402625  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+348) (BuildId: 0a902c3faf12314cc2e96d1ceb898f83)
03-02 17:19:28.333  6841  6841 F DEBUG   :       #17 pc 004028d7  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+42) (BuildId: 0a902c3faf12314cc2e96d1ceb898f83)
03-02 17:19:28.334  6841  6841 F DEBUG   :       #18 pc 00329753  /apex/com.android.art/lib/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+530) (BuildId: 0a902c3faf12314cc2e96d1ceb898f83)
03-02 17:19:28.334  6841  6841 F DEBUG   :       #19 pc 0006688d  /system/lib/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+28) (BuildId: 9258326c2cd45b0013e2d37278618ca0)
03-02 17:19:28.334  6841  6841 F DEBUG   :       #20 pc 0006c50b  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+514) (BuildId: 9258326c2cd45b0013e2d37278618ca0)
03-02 17:19:28.334  6841  6841 F DEBUG   :       #21 pc 00002e19  /system/bin/app_process32 (main+992) (BuildId: f3c5ce4a2d9e56c1e42631df920731f1)
03-02 17:19:28.334  6841  6841 F DEBUG   :       #22 pc 0005cecb  /apex/com.android.runtime/lib/bionic/libc.so (__libc_init+66) (BuildId: 310183375f23e99e40c9ab529416d05f)

03-02 17:19:28.711  6711  6711 E Zygote  : Zygote failed to write to system_server FD: Connection refused
03-02 17:19:28.712  6711  6711 E Zygote  : Exit zygote because system server (pid 6830) has terminated
```

**Comment by tehcneko** [comment]
DO NOT REMOVE MODULE TEMPLATE
