### ISSUE TITLE
[BUG][32Bit][Bootloop] Riru: Connection refused

### ISSUE THREAD

**Issue by BlueMax** [LSPosed/LSPosed#285]
**什么情况/What happened?**
bootloop

**Xposed模块列表/Xposed Module List**

lsposed manager not installed

**Magisk模块列表/Magisk Module List**
Riru v23.9
LSPosed-v1.2.1-5416-debug.zip

**版本信息/Versions**

Android: LOS18.1 (03/2021) 32Bit

Magisk: v22

Riru: v23.9

LSPosed: v1.2.1-5416-debug

**相关日志/Related Logs**

```
03-07 17:06:25.739  2318  2318 I Riru    : Riru v23.9 (59) in zygote
03-07 17:06:25.739  2318  2318 I Riru    : config dir is /data/adb/riru
03-07 17:06:25.739  2318  2318 I Riru    : system version 11 (api 30, preview_sdk 0)
03-07 17:06:25.749  2318  2318 I Riru    : hook installed
03-07 17:06:25.749  2318  2318 V Riru    : try read status via socket
03-07 17:06:25.749  2318  2318 E Riru    : connect rirud failed with 111: Connection refused
03-07 17:06:25.749  2318  2318 W Riru    : read from socket failed, try file
03-07 17:06:25.753  2318  2318 E linker  : "/system/lib/libriru_c0d4.so": ignoring DT_PREINIT_ARRAY in shared library!
03-07 17:06:25.756  2318  2318 I Riru    : module loaded: c0d4 (api 10)
03-07 17:06:25.756  2318  2318 E Riru    : access /system/lib/libriru_cbe7.so failed with 2: No such file or directory
03-07 17:06:25.756  2318  2318 I Riru    : hide is not enabled
03-07 17:06:25.756  2318  2318 V Riru    : c0d4: onModuleLoaded
03-07 17:06:25.756  2318  2318 I LSPosed : onModuleLoaded: welcome to LSPosed!
03-07 17:06:25.756  2318  2318 E LSPosed : Connection refused
03-07 17:06:25.756  2318  2318 D LSPosed : InitSymbolCache
03-07 17:06:25.804  2318  2318 V Riru    : try write status via socket
03-07 17:06:25.804  2318  2318 E Riru    : connect rirud failed with 111: Connection refused
03-07 17:06:25.804  2318  2318 W Riru    : write to socket failed, try file
03-07 17:06:25.827  2318  2318 D zygote  : Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
03-07 17:06:25.827  2318  2318 D zygote  : I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt66l.dat
03-07 17:06:25.840  2318  2318 I zygote  : fcntl(F_ADD_SEALS) failed: Invalid argument, no memfd support.
03-07 17:06:25.841  2318  2318 I zygote  : Falling back to ashmem implementation for JIT zygote mapping
03-07 17:06:25.849  2318  2318 I Riru    : replaced android.os.SystemProperties#native_set
03-07 17:06:25.876  2318  2318 I Riru    : replaced com.android.internal.os.Zygote#nativeForkAndSpecialize
03-07 17:06:25.876  2318  2318 V Riru    : try write status via socket
03-07 17:06:25.876  2318  2318 E Riru    : connect rirud failed with 111: Connection refused
03-07 17:06:25.877  2318  2318 W Riru    : write to socket failed, try file
03-07 17:06:25.877  2318  2318 I Riru    : replaced com.android.internal.os.Zygote#nativeForkSystemServer
03-07 17:06:25.877  2318  2318 V Riru    : try write status via socket
03-07 17:06:25.877  2318  2318 E Riru    : connect rirud failed with 111: Connection refused
03-07 17:06:25.877  2318  2318 W Riru    : write to socket failed, try file
03-07 17:06:25.877  2318  2318 I Riru    : replaced com.android.internal.os.Zygote#nativeSpecializeAppProcess
03-07 17:06:25.877  2318  2318 V Riru    : try write status via socket
03-07 17:06:25.877  2318  2318 E Riru    : connect rirud failed with 111: Connection refused
03-07 17:06:25.877  2318  2318 W Riru    : write to socket failed, try file
03-07 17:06:25.882  2318  2318 W zygote  : JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
03-07 17:06:25.897  2318  2318 D Zygote  : begin preload
03-07 17:06:25.897  2318  2318 I Zygote  : Calling ZygoteHooks.beginPreload()
03-07 17:06:25.922  2318  2318 D Zygote32Timing: BeginPreload took to complete: 25ms
03-07 17:06:25.922  2318  2318 I Zygote  : Preloading classes...
03-07 17:06:25.928  2318  2318 W Zygote  : Class not found for preloading: android.app.-$$Lambda$ResourcesManager$QJ7UiVk_XS90KuXAsIjIEym1DnM
03-07 17:06:26.466  2318  2453 I zygote  : Verified 1363 classes from mainline modules in 584.018ms
03-07 17:06:26.572   637   637 I rirud_java: Service activity not found, wait 1s...
03-07 17:06:26.573   428   428 I LSPosedService: service package is not started, wait 1s.
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #01 pc 0006c573  /apex/com.android.runtime/lib/bionic/libc.so (sigwait+42)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #02 pc 004271a1  /apex/com.android.art/lib/libart.so (art::SignalCatcher::WaitForSignal(art::Thread*, art::SignalSet&)+224)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #03 pc 004262b7  /apex/com.android.art/lib/libart.so (art::SignalCatcher::Run(void*)+194)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #04 pc 000ab93b  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+40)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #05 pc 00063b1d  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   (no managed stack frames)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655] 
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655] "perfetto_hprof_listener" prio=10 tid=3 Native (still starting up)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   | group="" sCount=1 dsCount=0 flags=1 obj=0x0 self=0xb673ba00
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   | sysTid=2469 nice=-20 cgrp=default sched=0/0 handle=0x8b0201c0
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   | state=S schedstat=( 361978 0 8 ) utm=0 stm=0 core=2 HZ=100
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   | stack=0x8af25000-0x8af27000 stackSize=1008KB
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   | held mutexes=
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #00 pc 0009b798  /apex/com.android.runtime/lib/bionic/libc.so (read+8)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #01 pc 0000dc01  /apex/com.android.art/lib/libperfetto_hprof.so (void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ArtPlugin_Initialize::$_29> >(void*)+208)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #02 pc 000ab93b  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+40)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #03 pc 00063b1d  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   (no managed stack frames)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655] 
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655] Aborting thread:
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655] "main" prio=5 tid=1 Native
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   | group="" sCount=0 dsCount=0 flags=0 obj=0x71b092f0 self=0xb6739e00
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   | sysTid=2462 nice=0 cgrp=default sched=0/0 handle=0xb6bcb470
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   | state=R schedstat=( 129995990 10867033 47 ) utm=5 stm=6 core=2 HZ=100
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   | stack=0xbe338000-0xbe33a000 stackSize=8192KB
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   | held mutexes= "abort lock"
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #00 pc 0037b1dd  /apex/com.android.art/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+76)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #01 pc 0044ccb1  /apex/com.android.art/lib/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+388)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #02 pc 004483f7  /apex/com.android.art/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+34)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #03 pc 00419c8f  /apex/com.android.art/lib/libart.so (art::AbortState::DumpThread(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, art::Thread*) const+30)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #04 pc 0040a519  /apex/com.android.art/lib/libart.so (art::Runtime::Abort(char const*)+1952)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #05 pc 0000d989  /system/lib/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+48)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #06 pc 0000d295  /system/lib/libbase.so (android::base::LogMessage::~LogMessage()+224)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #07 pc 002965db  /apex/com.android.art/lib/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1962)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #08 pc 002c8e67  /apex/com.android.art/lib/libart.so (art::JNI<false>::GetStaticMethodID(_JNIEnv*, _jclass*, char const*, char const*)+1326)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #09 pc 00021121  /system/lib/libriru_c0d4.so (_JNIEnv::GetStaticMethodID(_jclass*, char const*, char const*)+40)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #10 pc 0002afe9  /system/lib/libriru_c0d4.so (lspd::Service::RequestBinderForSystemServer(_JNIEnv*)+164)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #11 pc 0002180b  /system/lib/libriru_c0d4.so (lspd::Context::OnNativeForkSystemServerPost(_JNIEnv*, int)+50)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #12 pc 00023f33  /system/lib/libriru_c0d4.so (lspd::nativeForkSystemServerPost(_JNIEnv*, _jclass*, int)+18)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #13 pc 00003c4b  /system/lib/libriru.so (???)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #14 pc 00003ba3  /system/lib/libriru.so (???)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #15 pc 00213b8f  /system/framework/arm/boot-framework.oat (art_jni_trampoline+198)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #16 pc 0074412b  /system/framework/arm/boot-framework.oat (com.android.internal.os.ZygoteInit.forkSystemServer+1130)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #17 pc 00744fb7  /system/framework/arm/boot-framework.oat (com.android.internal.os.ZygoteInit.main+1718)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #18 pc 000d39d5  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub_internal+68)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #19 pc 004f8461  /apex/com.android.art/lib/libart.so (art_quick_invoke_static_stub+276)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #20 pc 0012c0b1  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+160)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #21 pc 004038b5  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+348)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #22 pc 00403b67  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+42)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #23 pc 0032a19f  /apex/com.android.art/lib/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+530)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #24 pc 000668dd  /system/lib/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+28)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #25 pc 0006c55b  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+514)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #26 pc 00002e19  /system/bin/app_process32 (main+992)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   native: #27 pc 0005ce8b  /apex/com.android.runtime/lib/bionic/libc.so (__libc_init+66)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   at com.android.internal.os.Zygote.nativeForkSystemServer(Native method)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   at com.android.internal.os.Zygote.forkSystemServer(Zygote.java:465)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   at com.android.internal.os.ZygoteInit.forkSystemServer(ZygoteInit.java:781)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:920)
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:655] 
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:663] JNI DETECTED ERROR IN APPLICATION: java_class == null
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:663]     in call to GetStaticMethodID
03-07 17:06:28.623  2462  2462 F system_server: runtime.cc:663]     from int com.android.internal.os.Zygote.nativeForkSystemServer(int, int, int[], int, int[][], long, long)
03-07 17:06:28.624  2462  2462 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 2462 (system_server), pid 2462 (system_server)
03-07 17:06:28.655  2472  2472 W crash_dump32: failed to fetch registers for thread 2468: I/O error
03-07 17:06:28.656  2472  2472 W crash_dump32: failed to fetch registers for thread 2469: I/O error
03-07 17:06:28.666  2472  2472 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
03-07 17:06:28.667   364   364 I tombstoned: received crash request for pid 2462
03-07 17:06:28.667  2472  2472 I crash_dump32: performing dump of process 2462 (target tid = 2462)
03-07 17:06:28.691  2472  2472 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-07 17:06:28.691  2472  2472 F DEBUG   : LineageOS Version: '18.1-20210305-UNOFFICIAL-ks01ltexx'
03-07 17:06:28.691  2472  2472 F DEBUG   : Build fingerprint: 'samsung/ks01ltexx/ks01lte:5.0.1/LRX22C/I9506XXSDPL2:user/release-keys'
03-07 17:06:28.691  2472  2472 F DEBUG   : Revision: '0'
03-07 17:06:28.691  2472  2472 F DEBUG   : ABI: 'arm'
03-07 17:06:28.692  2472  2472 F DEBUG   : Timestamp: 2021-03-07 17:06:28+0100
03-07 17:06:28.692  2472  2472 F DEBUG   : pid: 2462, tid: 2462, name: system_server  >>> zygote <<<
03-07 17:06:28.692  2472  2472 F DEBUG   : uid: 1000
03-07 17:06:28.692  2472  2472 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
03-07 17:06:28.692  2472  2472 F DEBUG   : Abort message: 'JNI DETECTED ERROR IN APPLICATION: java_class == null
03-07 17:06:28.692  2472  2472 F DEBUG   :     in call to GetStaticMethodID
03-07 17:06:28.692  2472  2472 F DEBUG   :     from int com.android.internal.os.Zygote.nativeForkSystemServer(int, int, int[], int, int[][], long, long)'
03-07 17:06:28.692  2472  2472 F DEBUG   :     r0  00000000  r1  0000099e  r2  00000006  r3  beb34bb8
03-07 17:06:28.692  2472  2472 F DEBUG   :     r4  beb34bcc  r5  beb34bb0  r6  0000099e  r7  0000016b
03-07 17:06:28.693  2472  2472 F DEBUG   :     r8  beb34bb8  r9  beb34bc8  r10 beb34be8  r11 beb34bd8
03-07 17:06:28.693  2472  2472 F DEBUG   :     ip  0000099e  sp  beb34b88  lr  b49335f1  pc  b4933604
03-07 17:06:28.894  2472  2472 F DEBUG   : backtrace:
03-07 17:06:28.894  2472  2472 F DEBUG   :       #00 pc 00062604  /apex/com.android.runtime/lib/bionic/libc.so (abort+172) (BuildId: f0a551fd133f598a5b550ac7bb032d29)
03-07 17:06:28.894  2472  2472 F DEBUG   :       #01 pc 0040a419  /apex/com.android.art/lib/libart.so (art::Runtime::Abort(char const*)+1696) (BuildId: a300af774b3f04f431ac5e72592a86a3)
03-07 17:06:28.894  2472  2472 F DEBUG   :       #02 pc 0000d989  /system/lib/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+48) (BuildId: f99c201f0141a2823db6b1ee0c0bdae6)
03-07 17:06:28.894  2472  2472 F DEBUG   :       #03 pc 0000d295  /system/lib/libbase.so (android::base::LogMessage::~LogMessage()+224) (BuildId: f99c201f0141a2823db6b1ee0c0bdae6)
03-07 17:06:28.895  2472  2472 F DEBUG   :       #04 pc 002965db  /apex/com.android.art/lib/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1962) (BuildId: a300af774b3f04f431ac5e72592a86a3)
03-07 17:06:28.895  2472  2472 F DEBUG   :       #05 pc 002c8e67  /apex/com.android.art/lib/libart.so (art::JNI<false>::GetStaticMethodID(_JNIEnv*, _jclass*, char const*, char const*)+1326) (BuildId: a300af774b3f04f431ac5e72592a86a3)
03-07 17:06:28.895  2472  2472 F DEBUG   :       #06 pc 00021121  /system/lib/libriru_c0d4.so (_JNIEnv::GetStaticMethodID(_jclass*, char const*, char const*)+40) (BuildId: 88fc32e256eefbd2d80c79c12bd3a6c3e561a65a)
03-07 17:06:28.895  2472  2472 F DEBUG   :       #07 pc 0002afe9  /system/lib/libriru_c0d4.so (lspd::Service::RequestBinderForSystemServer(_JNIEnv*)+164) (BuildId: 88fc32e256eefbd2d80c79c12bd3a6c3e561a65a)
03-07 17:06:28.895  2472  2472 F DEBUG   :       #08 pc 0002180b  /system/lib/libriru_c0d4.so (lspd::Context::OnNativeForkSystemServerPost(_JNIEnv*, int)+50) (BuildId: 88fc32e256eefbd2d80c79c12bd3a6c3e561a65a)
03-07 17:06:28.895  2472  2472 F DEBUG   :       #09 pc 00023f33  /system/lib/libriru_c0d4.so (lspd::nativeForkSystemServerPost(_JNIEnv*, _jclass*, int)+18) (BuildId: 88fc32e256eefbd2d80c79c12bd3a6c3e561a65a)
03-07 17:06:28.895  2472  2472 F DEBUG   :       #10 pc 00003c4b  /system/lib/libriru.so (BuildId: 50a438cab71727da6ceb9c09e1e8bb54e14608af)
03-07 17:06:28.896  2472  2472 F DEBUG   :       #11 pc 00003ba3  /system/lib/libriru.so (BuildId: 50a438cab71727da6ceb9c09e1e8bb54e14608af)
03-07 17:06:28.896  2472  2472 F DEBUG   :       #12 pc 00213b8f  /system/framework/arm/boot-framework.oat (art_jni_trampoline+198) (BuildId: 5dac1def14bdc1ca33b8b3023bba4223025ec540)
03-07 17:06:28.896  2472  2472 F DEBUG   :       #13 pc 0074412b  /system/framework/arm/boot-framework.oat (com.android.internal.os.ZygoteInit.forkSystemServer+1130) (BuildId: 5dac1def14bdc1ca33b8b3023bba4223025ec540)
03-07 17:06:28.896  2472  2472 F DEBUG   :       #14 pc 00744fb7  /system/framework/arm/boot-framework.oat (com.android.internal.os.ZygoteInit.main+1718) (BuildId: 5dac1def14bdc1ca33b8b3023bba4223025ec540)
03-07 17:06:28.896  2472  2472 F DEBUG   :       #15 pc 000d39d5  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: a300af774b3f04f431ac5e72592a86a3)
03-07 17:06:28.896  2472  2472 F DEBUG   :       #16 pc 004f8461  /apex/com.android.art/lib/libart.so (art_quick_invoke_static_stub+276) (BuildId: a300af774b3f04f431ac5e72592a86a3)
03-07 17:06:28.897  2472  2472 F DEBUG   :       #17 pc 0012c0b1  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+160) (BuildId: a300af774b3f04f431ac5e72592a86a3)
03-07 17:06:28.897  2472  2472 F DEBUG   :       #18 pc 004038b5  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+348) (BuildId: a300af774b3f04f431ac5e72592a86a3)
03-07 17:06:28.897  2472  2472 F DEBUG   :       #19 pc 00403b67  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+42) (BuildId: a300af774b3f04f431ac5e72592a86a3)
03-07 17:06:28.897  2472  2472 F DEBUG   :       #20 pc 0032a19f  /apex/com.android.art/lib/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+530) (BuildId: a300af774b3f04f431ac5e72592a86a3)
03-07 17:06:28.897  2472  2472 F DEBUG   :       #21 pc 000668dd  /system/lib/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+28) (BuildId: 8166fae3211dde3d40d60b02c2fe852b)
03-07 17:06:28.898  2472  2472 F DEBUG   :       #22 pc 0006c55b  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+514) (BuildId: 8166fae3211dde3d40d60b02c2fe852b)
03-07 17:06:28.898  2472  2472 F DEBUG   :       #23 pc 00002e19  /system/bin/app_process32 (main+992) (BuildId: 15c444fb48ec924828287f1f108490e4)
03-07 17:06:28.898  2472  2472 F DEBUG   :       #24 pc 0005ce8b  /apex/com.android.runtime/lib/bionic/libc.so (__libc_init+66) (BuildId: f0a551fd133f598a5b550ac7bb032d29)
03-07 17:06:29.260  2462  2462 W system_server: type=1701 audit(0.0:745): auid=4294967295 uid=1000 gid=1000 ses=4294967295 subj=u:r:system_server:s0 reason="memory violation" sig=6
03-07 17:06:29.274  2318  2318 E Zygote  : Zygote failed to write to system_server FD: Connection refused
03-07 17:06:29.274  2318  2318 I Zygote  : Process 2462 exited due to signal 6 (Aborted)
03-07 17:06:29.274  2318  2318 E Zygote  : Exit zygote because system server (pid 2462) has terminated

```

**Comment by yujincheng08** [comment]
Please attach full bootlog

**Comment by yujincheng08** [comment]
I think you'd better submit FULL bootlog to Riru, though Rikka is also here so it's okay to submit here.

**Comment by BlueMax** [comment]
The bootloop is gone with the new patch but lsposed didn't run anyway. 
But it does work when i wipe the rom so i guess its generally ok now. Looks like i have still some leftovers or something.

Thanks!
