### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dimon-015** [LSPosed/LSPosed#2878]
### Steps to reproduce/复现步骤

Just tried to open it.

### Expected behaviour/预期行为

LSPosed was supposed to open.

### Actual behaviour/实际行为

It crashes. Closing.

### Xposed Module List/Xposed 模块列表

```shell
AppErrorsTracking, ColorBlendr, Hide My Applist, lconify, NoStorageRestrict.
```

### Magisk Module List/Magisk 模块列表

```shell
Magisk built-in Busybox, Play Integrity Fix, Zygisk - LSPosed, Zygisk - Sui.
```

### LSPosed version/LSPosed 版本

7045

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26401

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Generated by AppErrorsTracking 1.3-b7ffdf3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Xiaomi
[Device Model]: M2007J3SY
[Display]: TQ3A.230805.001
[Android Version]: 13
[Android API Level]: 33
[System Locale]: ru_RU
[Process ID]: 5666
[User ID]: 0
[CPU ABI]: none
[Package Name]: com.android.shell
[Version Name]: 13
[Version Code]: 33
[Target SDK]: 33
[Min SDK]: 33
[Error Type]: JVM
[Crash Time]: 2023-12-09T19:00:07.767
[Stack Trace]:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.shell/org.lsposed.manager.ui.activity.MainActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f0f0000
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7959)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f0f0000
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:230)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2509)
	at android.content.res.Resources.getXml(Resources.java:1312)
	at androidx.navigation.NavInflater.inflate(NavInflater.kt:52)
	at androidx.navigation.NavController.setGraph(NavController.kt:1148)
	at androidx.navigation.fragment.NavHostFragment$navHostController$2.invoke(NavHostFragment.kt:104)
	at androidx.navigation.fragment.NavHostFragment$navHostController$2.invoke(NavHostFragment.kt:78)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at androidx.navigation.fragment.NavHostFragment.getNavHostController$navigation_fragment_release(NavHostFragment.kt:78)
	at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.kt:150)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3094)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:504)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:268)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2941)
	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:252)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:219)
	at rikka.material.internal.ThemedAppCompatActivity.onCreate(ThemedAppCompatActivity.kt:29)
	at rikka.material.app.MaterialActivity.onCreate(MaterialActivity.kt:20)
	at org.lsposed.manager.ui.activity.base.BaseActivity.onCreate(BaseActivity.java:49)
	at org.lsposed.manager.ui.activity.MainActivity.onCreate(MainActivity.java:83)
	at android.app.Activity.performCreate(Activity.java:8348)
	at android.app.Activity.performCreate(Activity.java:8327)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1423)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
	... 12 more

[LSPosed_2023-12-09T19_01_05.198172.zip](https://github.com/LSPosed/LSPosed/files/13624905/LSPosed_2023-12-09T19_01_05.198172.zip)

**Comment by yujincheng08** [comment]
Cannot fix.
