### ISSUE TITLE
[BUG] Crash when selecting an app for module

### ISSUE THREAD

**Issue by aviraxp** [LSPosed/LSPosed#39]
Build version: v0.5.2.0 
Build date: 1981-01-01 01:01:02 
Current date: 2021-02-01 20:37:55 
Device: OnePlus KB2000 
 
Stack trace:  
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:899)
	at java.util.TimSort.mergeAt(TimSort.java:516)
	at java.util.TimSort.mergeForceCollapse(TimSort.java:457)
	at java.util.TimSort.sort(TimSort.java:254)
	at java.util.Arrays.sort(Arrays.java:1492)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at d.a.a.a.d.n.run(:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Comment by tehcneko** [comment]
是每次都会遇到吗，还是进行了什么操作？
我下次把混淆禁用了吧🤦‍♂️

**Comment by aviraxp** [comment]
大概二十次能复现一次

**Comment by tehcneko** [comment]
[LSPosedManager-v0.5.2.0-233-release.zip](https://github.com/LSPosed/LSPosed/files/5908371/LSPosedManager-v0.5.2.0-233-release.zip)
试试这个？版本号比 CI 的版本低，卸了再装就好

**Comment by aviraxp** [comment]
在这个版本上试了五十次，貌似修好了

**Comment by tehcneko** [comment]
@aviraxp 这就很诡异了，你可能有两个 android ？

**Comment by aviraxp** [comment]
没有呀，只有一个

**Comment by yujincheng08** [comment]
修了，你爽爽看？
