### ISSUE TITLE
[TODO] Bring `XSharedPereference` FULLY back to support old modules

### ISSUE THREAD

**Issue by yujincheng08** [LSPosed/LSPosed#402]
With binder, we can now bring XSharedPereference FULLY back without placing files to `/data/misc`.

**Comment by yujincheng08** [comment]
Never mind.

**Comment by etmatrix** [comment]
So this should resolve the issue #401?
Why is it already closed?

**Comment by canyie** [comment]
@etmatrix /data/data is encrypted, so it is unusable before the user unlocks the device. We don't want to provide an API that's not completely available, so we closed it.

**Comment by yujincheng08** [comment]
Oh, from what I know, Android 7 introduced FDE and at that time the original Xposed is still alive.
So I think for modules at least support Android 7 they can properly handle FDE? So this enhancement is actually meaningful?

**Comment by rxzcums** [comment]
any process? it's very needed.

**Comment by Mino260806** [comment]
> @etmatrix /data/data is encrypted, so it is unusable before the user unlocks the device. We don't want to provide an API that's not completely available, so we closed this issue.

What about creating a directory in internal storage (choosable by user or simply /sdcard/.lspd by default) and locking it like /data/adb/lspd or hiding it, then redirect XSharedPreferences to that folder ? That will also enable editing the preferences from within the hook.

That's what I do in my modules (using [Paper](https://github.com/pilgr/Paper))

**Comment by Mmbii8** [comment]
Build version: 1.8.0 (٦٤٨٢) 
Current date: 2022-09-30T14:44:10.341942 
Device: Samsung GM1917 
Fingerprint: samsung/a32xx/a32:12/SP1A.210812.016/A325FXXU2BVH1:user/release-keys 
 
SDK: 31 
 
Stack trace:  
java.util.UnknownFormatConversionException: Conversion = 'End of String'
	at java.util.Formatter$FormatSpecifierParser.peek(Formatter.java:2647)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2608)
	at java.util.Formatter.parse(Formatter.java:2563)
	at java.util.Formatter.format(Formatter.java:2510)
	at java.util.Formatter.format(Formatter.java:2464)
	at java.lang.String.format(String.java:3644)
	at android.content.res.Resources.getString(Resources.java:627)
	at android.content.Context.getString(Context.java:726)
	at gu.l(SourceFile:4)
	at jv.m(SourceFile:2)
	at Yq.c(SourceFile:4)
	at E7.l(SourceFile:2)
	at Yq.m(Unknown Source:0)
	at Yq.c(SourceFile:4)
	at mr.j(SourceFile:91)
	at wk.c(SourceFile:3)
	at androidx.recyclerview.widget.LinearLayoutManager.g1(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.T0(SourceFile:2)
	at androidx.recyclerview.widget.LinearLayoutManager.j0(SourceFile:19)
	at androidx.recyclerview.widget.RecyclerView.w(Unknown Source:66)
	at androidx.recyclerview.widget.RecyclerView.u(SourceFile:6)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:2)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(Unknown Source:58)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at Ch.t(SourceFile:8)
	at gB.h(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:4)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(Unknown Source:61)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.s(SourceFile:15)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:4)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1331)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4609)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4031)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2919)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10491)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Build version: 1.8.0 (٦٤٨٢) 
Current date: 2022-09-30T14:44:10.341942 
Device: Samsung GM1917 
Fingerprint: samsung/a32xx/a32:12/SP1A.210812.016/A325FXXU2BVH1:user/release-keys 
 
SDK: 31 
 
Stack trace:  
java.util.UnknownFormatConversionException: Conversion = 'End of String'
	at java.util.Formatter$FormatSpecifierParser.peek(Formatter.java:2647)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2608)
	at java.util.Formatter.parse(Formatter.java:2563)
	at java.util.Formatter.format(Formatter.java:2510)
	at java.util.Formatter.format(Formatter.java:2464)
	at java.lang.String.format(String.java:3644)
	at android.content.res.Resources.getString(Resources.java:627)
	at android.content.Context.getString(Context.java:726)
	at gu.l(SourceFile:4)
	at jv.m(SourceFile:2)
	at Yq.c(SourceFile:4)
	at E7.l(SourceFile:2)
	at Yq.m(Unknown Source:0)
	at Yq.c(SourceFile:4)
	at mr.j(SourceFile:91)
	at wk.c(SourceFile:3)
	at androidx.recyclerview.widget.LinearLayoutManager.g1(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.T0(SourceFile:2)
	at androidx.recyclerview.widget.LinearLayoutManager.j0(SourceFile:19)
	at androidx.recyclerview.widget.RecyclerView.w(Unknown Source:66)
	at androidx.recyclerview.widget.RecyclerView.u(SourceFile:6)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:2)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(Unknown Source:58)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at Ch.t(SourceFile:8)
	at gB.h(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:4)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(Unknown Source:61)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.s(SourceFile:15)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:4)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1331)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4609)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4031)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2919)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10491)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by alexandriux** [comment]
Build version: 1.8.4 (6609) 
Current date: 2022-10-29T21:15:15.032 
Device: Xiaomi M2103K19G 
Fingerprint: Redmi/camellian_global/camellian:11/RP1A.200720.011/V12.5.6.0.RKSMIXM:user/release-keys 
 
SDK: 30 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String up.g()' on a null object reference
	at org.lsposed.manager.ui.fragment.RepoItemFragment$c.J(SourceFile:5)
	at Te.Z(Unknown Source:19)
	at androidx.fragment.app.a.f(SourceFile:11)
	at androidx.fragment.app.a.k(SourceFile:8)
	at pf.S(SourceFile:2)
	at pf.v(SourceFile:4)
	at androidx.fragment.app.a.f(SourceFile:17)
	at androidx.fragment.app.a.k(SourceFile:8)
	at pf.D(SourceFile:24)
	at pf.Y(Unknown Source:91)
	at pf.B(SourceFile:5)
	at ia.run(SourceFile:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8051)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**Comment by alexandriux** [comment]
Build version: 1.8.4 (6609) 
Current date: 2022-10-29T21:15:15.032 
Device: Xiaomi M2103K19G 
Fingerprint: Redmi/camellian_global/camellian:11/RP1A.200720.011/V12.5.6.0.RKSMIXM:user/release-keys 
 
SDK: 30 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String up.g()' on a null object reference
	at org.lsposed.manager.ui.fragment.RepoItemFragment$c.J(SourceFile:5)
	at Te.Z(Unknown Source:19)
	at androidx.fragment.app.a.f(SourceFile:11)
	at androidx.fragment.app.a.k(SourceFile:8)
	at pf.S(SourceFile:2)
	at pf.v(SourceFile:4)
	at androidx.fragment.app.a.f(SourceFile:17)
	at androidx.fragment.app.a.k(SourceFile:8)
	at pf.D(SourceFile:24)
	at pf.Y(Unknown Source:91)
	at pf.B(SourceFile:5)
	at ia.run(SourceFile:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8051)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
