### ISSUE TITLE
[BUG] Module library cannot be opened

### ISSUE THREAD

**Issue by SikroYang** [LSPosed/LSPosed#417]
**版本信息/Versions**

Android:10

Magisk:22.0

Riru:25.3.3

LSPosed:1.3.4

**相关日志/Related Logs**

Build version: v1.3.4 (5501) 
Current date: 2021-03-26 22:36:42 
Device: OnePlus ONEPLUS A6000 
 
SDK: 29 
 
Stack trace:  
java.lang.RuntimeException: Unable to resume activity {org.lsposed.manager/org.lsposed.manager.ui.activity.RepoActivity}: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4322)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4354)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at Y0.apply(:5)
	at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469)
	at java.util.-$$Lambda$Comparator$SPB8K9Yj7Pw1mljm7LpasV7zxWw.compare(Unknown Source:2)
	at java.util.Collections$ReverseComparator2.compare(Collections.java:5235)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1492)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at org.lsposed.manager.ui.activity.RepoActivity$a.g(:2)
	at org.lsposed.manager.ui.activity.RepoActivity.onResume(:11)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1560)
	at android.app.Activity.performResume(Activity.java:7952)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4312)
	... 11 more

**Comment by yujincheng08** [comment]
Already fixed in ab26c5334d44e0e55e837549e0e2464def67dfc2
