### ISSUE TITLE
[BUG] ClassNotFoundException

### ISSUE THREAD

**Issue by Stillhard** [LSPosed/LSPosed#523]
Android version: 10
Android sdk: 29
LSPosed version: v1.3.5 (5574)
Riru version: v25.4.2.r415.f42e9c3 (415)
Riru api: 25
Magisk: fb8000b5 (22104)

Crashlog: https://del.dog/bingukiper.txt

```
time: 1619542814838
msg: java.lang.ClassNotFoundException: ëº£â®äé°à±íï ä°î¬©ë©¬ë¢³î´çìé¥á¼
stacktrace: java.lang.RuntimeException: Unable to create application com.bankmandiri.mandirionline.ProtectedMOApplication: com.bankmandiri.mandirionline.MessageGuardException_67qj4q6I5JOU6ZCw4LGe7YCV76CH5JCw7qyp66ms66Kz7rSA54OM7IWQ6aWM4bye: ëº£â®äé°à±íï ä°î¬©ë©¬ë¢³î´çìé¥á¼ë»©â¯RmluZ2VycHJpbnQgMjAyMDEyMDcgWysrKysuK10gYXJtNjQtdjhhOmFybTY0LXY4YSAyOS8yLjEuMC8tIFhpYW9taS9zYW50b25pL3NhbnRvbmk6Ni4wLjEvTU1CMjlNL1Y4LjUuNC4wLk1BTUNORUQ6dXNlci9yZWxlYXNlLWtleXM=ë» 
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6466)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
Caused by: com.bankmandiri.mandirionline.MessageGuardException_67qj4q6I5JOU6ZCw4LGe7YCV76CH5JCw7qyp66ms66Kz7rSA54OM7IWQ6aWM4bye: ëº£â®äé°à±íï ä°î¬©ë©¬ë¢³î´çìé¥á¼ë»©â¯RmluZ2VycHJpbnQgMjAyMDEyMDcgWysrKysuK10gYXJtNjQtdjhhOmFybTY0LXY4YSAyOS8yLjEuMC8tIFhpYW9taS9zYW50b25pL3NhbnRvbmk6Ni4wLjEvTU1CMjlNL1Y4LjUuNC4wLk1BTUNORUQ6dXNlci9yZWxlYXNlLWtleXM=ë» 
	at com.bankmandiri.mandirionline.ProtectedMOApplication.onCreate(Unknown Source:169)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6461)
	... 11 more
Caused by: java.lang.ClassNotFoundException: ëº£â®äé°à±íï ä°î¬©ë©¬ë¢³î´çìé¥á¼
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.forName(Unknown Source:18)
	at java.lang.Class.forName(Class.java:379)
	at com.bankmandiri.mandirionline.ProtectedMOApplication.onCreate(Unknown Source:53)
	... 13 more
Caused by: java.lang.ClassNotFoundException: ëº£â®äé°à±íï ä°î¬©ë©¬ë¢³î´çìé¥á¼
	... 20 more
```

**Comment by yujincheng08** [comment]
You hooked `LspHooker_.forName`, which causes this problem. It's not problem from framework.
