### ISSUE TITLE
[BUG] IllegalAccessError

### ISSUE THREAD

**Issue by Stillhard** [LSPosed/LSPosed#58]
```
java.lang.IllegalAccessError: Method 'java.lang.reflect.Field java.lang.Class.getDeclaredField(java.lang.String)' is inaccessible to class 'SandHooker_b04b111e9fa19f4f16a550471c543c100383963c' (declaration of 'SandHooker_b04b111e9fa19f4f16a550471c543c100383963c' appears in /data/misc/lspd_a4ZT76PDsagzdz6K/cache/SandHooker_b04b111e9fa19f4f16a550471c543c100383963c.jar)
 at SandHooker_b04b111e9fa19f4f16a550471c543c100383963c.hook(Unknown Source:123)
 at com.google.android.gms.dynamite.DynamiteModule.a(com.google.android.gms:play-services-basement@@17.3.0:42)
 at bje.a(com.google.android.gms:play-services-basement@@17.3.0:3)
 at bjk.a(com.google.android.gms:play-services-basement@@17.3.0:3)
 at com.google.android.gms.dynamite.DynamiteModule.a(com.google.android.gms:play-services-basement@@17.3.0:5)
 at cee.a(com.google.android.gms:play-services-measurement-sdk-api@@18.0.0:56)
 at ceh.b(com.google.android.gms:play-services-measurement-sdk-api@@18.0.0:11)
 at cee$a.run(com.google.android.gms:play-services-measurement-sdk-api@@18.0.0:11)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:764)
```

Android version: 9
Android sdk: 28
LSPosed version: v0.5.2.0
LSPosed api: 93
Riru version: v23.4 (54)
Riru api: 10
Magisk: 21.4 (21400)

**Comment by yujincheng08** [comment]
Does this issue appear when you use YAHFA?

**Comment by Stillhard** [comment]
> Does this issue appear when you use YAHFA?

Ok wait, testing... i'll get back with the result

**Comment by yujincheng08** [comment]
Oh that YAHFA's problem is useful.

And for Sandhook's problem, let me check it.

**Comment by yujincheng08** [comment]
Could you send us `/data/misc/lspd_xxx/cache/SandHooker_b04b111e9fa19f4f16a550471c543c100383963c.jar`?

**Comment by Stillhard** [comment]
> Could you send us `/data/misc/lspd_xxx/cache/SandHooker_b04b111e9fa19f4f16a550471c543c100383963c.jar`?

Ok, I'll get back to you later w/ the file

**Comment by Stillhard** [comment]
Test w/ diff device v0.5.3.0, hooked app crashed [ecylihosty](https://del.dog/ecylihosty.txt).txt

**Comment by yujincheng08** [comment]
[LSPosed-v0.5.3.0-233-debug.zip](https://github.com/LSPosed/LSPosed/files/5929714/LSPosed-v0.5.3.0-233-debug.zip)
@Stillhard try this

**Comment by Stillhard** [comment]
> [LSPosed-v0.5.3.0-233-debug.zip](https://github.com/LSPosed/LSPosed/files/5929714/LSPosed-v0.5.3.0-233-debug.zip)
> @Stillhard try this

Sorry for the late reply

Here's the result:
[LSPosed_Verbose_20210205_195332.log](https://github.com/LSPosed/LSPosed/files/5932585/LSPosed_Verbose_20210205_195332.log)
[LSPosed_Verbose_20210205_195344.log](https://github.com/LSPosed/LSPosed/files/5932590/LSPosed_Verbose_20210205_195344.log)

![photo_2021-02-05_20-06-37](https://user-images.githubusercontent.com/219005/107038053-8f5c4b80-67ee-11eb-938c-738f98780a6b.jpg)
```
Build version: v0.5.3.0 
Build date: 1981-01-01 01:01:02 
Current date: 2021-02-05 19:57:46 
Device: Xiaomi Redmi Note 4 
 
Stack trace:  
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@c3368bd is not valid; is your activity running?
 at android.view.ViewRootImpl.setView(ViewRootImpl.java:931)
 at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:96)
 at android.app.Dialog.show(Dialog.java:342)
 at io.github.lsposed.manager.ui.activity.LogsActivity$c$a.run(LogsActivity.java:3)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7356)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
```

**Comment by Stillhard** [comment]
Crash when opening rootbeerFresh
```
java.lang.IllegalAccessError: Method 'java.lang.reflect.Field java.lang.Class.getDeclaredField(java.lang.String)' is inaccessible to class 'SandHooker_b04b111e9fa19f4f16a550471c543c100383963c' (declaration of 'SandHooker_b04b111e9fa19f4f16a550471c543c100383963c' appears in /data/misc/lspd_a4ZT76PDsagzdz6K/cache/SandHooker_b04b111e9fa19f4f16a550471c543c100383963c.jar)
 at SandHooker_b04b111e9fa19f4f16a550471c543c100383963c.hook(Unknown Source:123)
 at miui.util.TypefaceHelper.getDefaultWithStyle(TypefaceHelper.java:35)
 at miui.util.TypefaceHelper.<clinit>(TypefaceHelper.java:31)
 at miui.util.TypefaceUtils.restoreTypefaceDefault(TypefaceUtils.java:479)
 at miui.util.TypefaceUtils.initSystemFont(TypefaceUtils.java:465)
 at miui.contentcatcher.InterceptorProxy.create(InterceptorProxy.java:62)
 at android.app.Activity.onCreate(Activity.java:1086)
 at android.support.v4.app.SupportActivity.onCreate(SupportActivity.java:66)
 at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:321)
 at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
 at com.kimchangyoun.rootbeerFresh.sample.MainActivity.onCreate(MainActivity.java:38)
 at android.app.Activity.performCreate(Activity.java:7224)
 at android.app.Activity.performCreate(Activity.java:7213)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:201)
 at android.app.ActivityThread.main(ActivityThread.java:6826)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by yujincheng08** [comment]
[LSPosed-v0.5.3.0-233-debug.zip](https://github.com/LSPosed/LSPosed/files/5933606/LSPosed-v0.5.3.0-233-debug.zip)
Try this

**Comment by Stillhard** [comment]
> [LSPosed-v0.5.3.0-233-debug.zip](https://github.com/LSPosed/LSPosed/files/5933606/LSPosed-v0.5.3.0-233-debug.zip)
> Try this

Sorry for the long delay.
Result: same crash
[SandHooker_b04b111e9fa19f4f16a550471c543c100383963c.jar.zip](https://github.com/LSPosed/LSPosed/files/5970222/SandHooker_b04b111e9fa19f4f16a550471c543c100383963c.jar.zip)

**Comment by yujincheng08** [comment]
Since we are deprecating SandHook (see #179), so this problem may not be fixed.
