### ISSUE TITLE
[BUG] What happened

### ISSUE THREAD

**Issue by liuxi378** [LSPosed/LSPosed#693]
**什么情况/What happened?**

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**

**版本信息/Versions**

Android:10

Magisk:23.0

Riru:25.4.4

LSPosed:1.4.3

**相关日志/Related Logs**

LSPosed Log
--------- beginning of information
Manufacturer: Xiaomi
Brand: Xiaomi
Device: equuleus
Product: equuleus
Model: MI 8 UD
Fingerprint: Xiaomi/equuleus/equuleus:10/QKQ1.190828.002/V11.0.3.0.QECCNXM:user/release-keys
ROM description: equuleus-user 10 QKQ1.190828.002 V11.0.3.0.QECCNXM release-keys
Architecture: arm64-v8a
Android build: QKQ1.190828.002
Android version: 10
Android sdk: 29
LSPosed version: v1.4.3 (5728)
Riru version: v25.4.4.r426.05efc94 (426)
Riru api: 25
Magisk: 23.0 (23000)
2021-05-30 01:48:13.013 I/com.android.systemui(4754-4754): ErrorHook: com.android.systemui.miui.statusbar.ControlCenter#addControlPanelWindow
2021-05-30 01:48:16.016 E/com.android.systemui(4754-4754): android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.content.res.ResourcesImpl.getValue(Unknown Source:33)
	at android.content.res.MiuiResourcesImpl.getValue(Unknown Source:0)
	at android.content.res.Resources.getDimensionPixelSize(Unknown Source:7)
	at java.lang.reflect
![Screenshot_2021-05-30-10-11-37-378_org lsposed manager](https://user-images.githubusercontent.com/60069157/120089784-0d42ba80-c130-11eb-9023-17a4f7258d22.jpg)
![Screenshot_2021-05-30-10-11-31-617_org lsposed manager](https://user-images.githubusercontent.com/60069157/120089789-116ed800-c130-11eb-9c60-eac0b0929802.jpg)

**Comment by liuxi378** [comment]
日志
LSPosed Log
--------- beginning of information
Manufacturer: Xiaomi
Brand: Xiaomi
Device: equuleus
Product: equuleus
Model: MI 8 UD
Fingerprint: Xiaomi/equuleus/equuleus:10/QKQ1.190828.002/V11.0.3.0.QECCNXM:user/release-keys
ROM description: equuleus-user 10 QKQ1.190828.002 V11.0.3.0.QECCNXM release-keys
Architecture: arm64-v8a
Android build: QKQ1.190828.002
Android version: 10
Android sdk: 29
LSPosed version: v1.4.3 (5728)
Riru version: v25.4.4.r426.05efc94 (426)
Riru api: 25
Magisk: 23.0 (23000)
2021-05-30 01:48:13.013 I/com.android.systemui(4754-4754): ErrorHook: com.android.systemui.miui.statusbar.ControlCenter#addControlPanelWindow
2021-05-30 01:48:16.016 E/com.android.systemui(4754-4754): android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.content.res.ResourcesImpl.getValue(Unknown Source:33)
	at android.content.res.MiuiResourcesImpl.getValue(Unknown Source:0)
	at android.content.res.Resources.getDimensionPixelSize(Unknown Source:7)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.getDimensionPixelSize(Unknown Source:15)
	at .afterHookedMethod(:302)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.onFinishInflate(Unknown Source:8)
	at android.view.LayoutInflater.rInflate(Unknown Source:125)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.rInflate(Unknown Source:103)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.parseInclude(Unknown Source:292)
	at android.view.LayoutInflater.rInflate(Unknown Source:71)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.rInflate(Unknown Source:103)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.inflate(Unknown Source:107)
	at android.view.LayoutInflater.inflate(Unknown Source:27)
	at com.android.systemui.qs.QSFragment.onCreateView(QSFragment.java:111)
	at android.app.Fragment.performCreateView(Unknown Source:10)
	at android.app.FragmentManagerImpl.moveToState(Unknown Source:566)
	at android.app.FragmentManagerImpl.addAddedFragments(Unknown Source:46)
	at android.app.FragmentManagerImpl.executeOpsTogether(Unknown Source:129)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(Unknown Source:99)
	at android.app.FragmentManagerImpl.execPendingActions(Unknown Source:21)
	at android.app.FragmentManagerImpl$1.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:249)
	at android.app.ActivityThread.main(Unknown Source:98)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:282)

2021-05-30 01:48:16.016 E/com.android.systemui(4754-4754): android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.content.res.ResourcesImpl.getValue(Unknown Source:33)
	at android.content.res.MiuiResourcesImpl.getValue(Unknown Source:0)
	at android.content.res.Resources.getDimensionPixelSize(Unknown Source:7)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.getDimensionPixelSize(Unknown Source:15)
	at .afterHookedMethod(:302)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.onFinishInflate(Unknown Source:8)
	at android.view.LayoutInflater.rInflate(Unknown Source:125)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.rInflate(Unknown Source:103)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.parseInclude(Unknown Source:292)
	at android.view.LayoutInflater.rInflate(Unknown Source:71)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.rInflate(Unknown Source:103)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.inflate(Unknown Source:107)
	at android.view.LayoutInflater.inflate(Unknown Source:27)
	at com.android.systemui.qs.QSFragment.onCreateView(QSFragment.java:111)
	at android.app.Fragment.performCreateView(Unknown Source:10)
	at android.app.FragmentManagerImpl.moveToState(Unknown Source:566)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source:38)
	at android.app.FragmentManagerImpl.moveToState(Unknown Source:46)
	at android.app.FragmentManagerImpl.dispatchMoveToState(Unknown Source:12)
	at android.app.FragmentManagerImpl.dispatchStart(Unknown Source:4)
	at android.app.FragmentController.dispatchStart(Unknown Source:4)
	at com.android.systemui.fragments.FragmentHostManager.createFragmentHost(FragmentHostManager.java:99)
	at com.android.systemui.fragments.FragmentHostManager.reloadFragment(FragmentHostManager.java:172)
	at com.android.systemui.fragments.FragmentHostManager.onConfigurationChanged(FragmentHostManager.java:162)
	at com.android.systemui.fragments.FragmentService$FragmentHostState.handleSendConfigurationChange(FragmentService.java:92)
	at com.android.systemui.fragments.FragmentService$FragmentHostState.access$200(FragmentService.java:68)
	at com.android.systemui.fragments.FragmentService$FragmentHostState$1.run(FragmentService.java:82)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:249)
	at android.app.ActivityThread.main(Unknown Source:98)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:282)

2021-05-30 01:48:31.031 I/com.tencent.mm(10383-10383): com.tencent.mm loading com.fkzhang.wechatxposed
2021-05-30 01:48:33.033 I/com.tencent.mm(10383-10383): com.fkzhang.wechatxposed [WechatXposed](2.22|85): wechat version 8.0.6(1900)
2021-05-30 01:48:33.033 I/com.tencent.mm(10383-10383): com.fkzhang.wechatxposed load time: 2250
2021-05-30 01:48:33.033 I/com.tencent.mm(10383-10559): 微X模块 2.22_3.18 (7,99) p
2021-05-30 01:48:34.034 I/com.tencent.mm(10383-10524): feature loaded: base 185
2021-05-30 01:48:34.034 I/com.tencent.mm(10383-10559): Wechat: 8.0.6_1900 {64bit} (0x28000635)[3dd9901]
2021-05-30 01:48:44.044 I/com.tencent.mobileqq(11258-11258): com.tencent.mobileqq loading com.fkzhang.qqxposed
2021-05-30 01:48:52.052 I/com.tencent.mobileqq(11258-11258): QX模块 2.8_1.15(49,1)
2021-05-30 01:48:52.052 I/com.tencent.mobileqq(11258-11258): com.fkzhang.qqxposed (2.8): QQ version 8.7.8(1758)
2021-05-30 01:48:52.052 I/com.tencent.mobileqq(11258-11258): com.fkzhang.qqxposed load time: 7762
2021-05-30 01:49:18.018 E/com.tencent.mobileqq(11258-12192): java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.fkzhang.qqxposedhooks.ˑʽ.ˆﹶ.ˉᵎ(Unknown Source:8)
	at com.fkzhang.qqxposedhooks.ˎˆ.ˎⁱ.ⁱˉ(Unknown Source:248)
	at com.fkzhang.qqxposedhooks.ˎˆ.ˎⁱ.ˉ(Unknown Source:2)
	at com.fkzhang.qqxposedhooks.ˎˆ.ˎⁱ.ˏˋ(Unknown Source:5)
	at com.fkzhang.qqxposedhooks.ˎˆ.ˎⁱ$ᵔ.ـˉ(Unknown Source:2)
	at com.fkzhang.qqxposedhooks.ˑʽ.ᵔ.ˎˆ(Unknown Source:28)
	at com.fkzhang.qqxposedhooks.ˑʽ.ᵔ.ᵢˈ(Unknown Source:16)
	at com.fkzhang.qqxposedhooks.ˑʽ.ᵔ.ʾˎ(Unknown Source:0)
	at com.fkzhang.qqxposedhooks.ˑʽ.ᵔ.ـˉ(Unknown Source:0)
	at com.fkzhang.qqxposedhooks.ˑʽ.ˑʽ.ـˉ(Unknown Source:10)
	at com.fkzhang.qqxposedhooks.ˑʽ.ˉᵎ.ˑـ(Unknown Source:710)
	at com.fkzhang.qqxposedhooks.ˑʽ.ˉᵎ.ـⁱ(Unknown Source:36)
	at com.fkzhang.qqxposedhooks.ˑʽ.ˉᵎ.ٴᐧ(Unknown Source:4)
	at com.fkzhang.qqxposedhooks.ˑʽ.ˉᵎ$ᴵˊ.run(Unknown Source:3)
	at com.fkzhang.qqxposedhooks.ᵢˈ.ʾˎ$ʾˎ.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:249)
	at android.os.HandlerThread.run(Unknown Source:28)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'mqq.manager.Manager mqq.app.AppRuntime.getManager(int)' on a null object reference
	at com.tencent.mobileqq.utils.ContactUtils.a(P:1875)
	... 20 more

2021-05-30 02:04:12.012 I/chili.xposed.chimi(21045-21045): ErrorHook: cc.binmt.signature.PmsHookApplication#hook
2021-05-30 02:11:31.031 I/com.android.systemui:screenshot(24473-24473): ErrorHook: com.android.systemui.miui.statusbar.ControlCenter#addControlPanelWindow
