### ISSUE TITLE
[BUG] app either can't locate lsposed, or lsposed not running

### ISSUE THREAD

**Issue by mr2013** [LSPosed/LSPosed#785]
**What happened?**

Installed lsposed, app does not get installed. Installed app manually, lsposed not detected by app.

**Xposed Module List**
Installed but not activated:
* BootManager 3.9.2
* Glitchify 6.1.0
* GravityBox [P] 9.2.1
* Hide Mock Location 1.3
* Native Clipboard 4.8.1
* Secure Settings 1.3.6u2
* XPrivacyLua 1.2.9
* Android Faker 1.3

**Magisk Module List**
* Log Catcher v22.5
* Riru v25.4.4.r426.05efc94
* Riru - LSposed v1.4.5 (5767)

**Versions**

Android: 9

Magisk: f822ca5b (23001)

Riru: v25.4.4.r426.05efc94 (426)

LSPosed: v1.4.5 (5767)

**Related Logs**

* [boot-2021-06-27-11-22-56.log](https://github.com/LSPosed/LSPosed/files/6721858/boot-2021-06-27-11-22-56.log)
* [all.log](https://github.com/LSPosed/LSPosed/files/6721859/all.log)

**Comment by yujincheng08** [comment]
Why is ur device fingerprint null?

**Comment by mr2013** [comment]
> Why is ur device fingerprint null?

No idea. It's stock Google firmware on a Google Fi device, modified only to have twrp and magisk.

**Comment by yujincheng08** [comment]
Even riru cannot run normally because of the null fingerprint:
```
06-27 11:17:01.911  1187  1187 W rirud_java: Landroid/os/Build; failed initialization: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
06-27 11:17:01.911  1187  1187 W rirud_java:   at java.lang.String android.os.Build.getBuildNumber() (Build.java:1207)
06-27 11:17:01.911  1187  1187 W rirud_java:   at java.lang.String android.os.Build.deriveFingerprint() (Build.java:959)
06-27 11:17:01.911  1187  1187 W rirud_java:   at void android.os.Build.<clinit>() (Build.java:945)
06-27 11:17:01.911  1187  1187 W rirud_java:   at java.lang.String android.os.Build.access$000(java.lang.String) (Build.java:42)
06-27 11:17:01.911  1187  1187 W rirud_java:   at void android.os.Build$VERSION.<clinit>() (Build.java:201)
06-27 11:17:01.911  1187  1187 W rirud_java:   at java.lang.String com.android.internal.os.RuntimeInit.getDefaultUserAgent() (RuntimeInit.java:258)
06-27 11:17:01.911  1187  1187 W rirud_java:   at void com.android.internal.os.RuntimeInit.commonInit() (RuntimeInit.java:225)
06-27 11:17:01.911  1187  1187 W rirud_java:   at void com.android.internal.os.RuntimeInit.main(java.lang.String[]) (RuntimeInit.java:334)
06-27 11:17:01.911  1187  1187 W rirud_java: 
06-27 11:17:01.911  1187  1187 W rirud_java: Landroid/os/Build$VERSION; failed initialization: java.lang.ExceptionInInitializerError: 
06-27 11:17:01.911  1187  1187 W rirud_java:   at java.lang.String android.os.Build.access$000(java.lang.String) (Build.java:42)
06-27 11:17:01.911  1187  1187 W rirud_java:   at void android.os.Build$VERSION.<clinit>() (Build.java:201)
06-27 11:17:01.911  1187  1187 W rirud_java:   at java.lang.String com.android.internal.os.RuntimeInit.getDefaultUserAgent() (RuntimeInit.java:258)
06-27 11:17:01.911  1187  1187 W rirud_java:   at void com.android.internal.os.RuntimeInit.commonInit() (RuntimeInit.java:225)
06-27 11:17:01.911  1187  1187 W rirud_java:   at void com.android.internal.os.RuntimeInit.main(java.lang.String[]) (RuntimeInit.java:334)
06-27 11:17:01.911  1187  1187 W rirud_java: 
06-27 11:17:01.911  1187  1187 D AndroidRuntime: Shutting down VM
06-27 11:17:01.912  1187  1187 E AndroidRuntime: FATAL EXCEPTION: main
06-27 11:17:01.912  1187  1187 E AndroidRuntime: PID: 1187
06-27 11:17:01.912  1187  1187 E AndroidRuntime: java.lang.ExceptionInInitializerError
06-27 11:17:01.912  1187  1187 E AndroidRuntime: 	at android.os.Build.access$000(Build.java:42)
06-27 11:17:01.912  1187  1187 E AndroidRuntime: 	at android.os.Build$VERSION.<clinit>(Build.java:201)
06-27 11:17:01.912  1187  1187 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.getDefaultUserAgent(RuntimeInit.java:258)
06-27 11:17:01.912  1187  1187 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.commonInit(RuntimeInit.java:225)
06-27 11:17:01.912  1187  1187 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:334)
06-27 11:17:01.912  1187  1187 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
06-27 11:17:01.912  1187  1187 E AndroidRuntime: 	at android.os.Build.getBuildNumber(Build.java:1207)
06-27 11:17:01.912  1187  1187 E AndroidRuntime: 	at android.os.Build.deriveFingerprint(Build.java:959)
06-27 11:17:01.912  1187  1187 E AndroidRuntime: 	at android.os.Build.<clinit>(Build.java:945)
06-27 11:17:01.912  1187  1187 E AndroidRuntime: 	... 5 more
06-27 11:17:01.913  1394  1394 E Diag_Lib:  Diag_LSM_Init: Failed to open handle to diag driver, error = 13
06-27 11:17:01.914  1187  1187 E AndroidRuntime: Error reporting crash
06-27 11:17:01.914  1187  1187 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.IActivityManager.handleApplicationCrash(android.os.IBinder, android.app.ApplicationErrorReport$ParcelableCrashInfo)' on a null object reference
06-27 11:17:01.914  1187  1187 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:143)
06-27 11:17:01.914  1187  1187 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
06-27 11:17:01.914  1187  1187 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
06-27 11:17:01.914  1187  1187 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
```

**Comment by yujincheng08** [comment]
```
[   70.574442,4] init: property 'ro.build.fingerprint' doesn't exist while expanding '${ro.build.fingerprint}'
[   70.574475,4] init: Command 'write /data/misc/recovery/ro.build.fingerprint ${ro.build.fingerprint}' action=post-fs-data (/init.rc:420) took 0ms and failed: cannot expand '${ro.build.fingerprint}'
```

**Comment by yujincheng08** [comment]
I think you should try to set `ro.build.fingerprint` manually for boot. Like adding
```
ro.build.fingerprint=motorola/river/river:9/PPOS29.114-134-14/0cccf:user/release-keys
```
to /data/adb/modules/riru_lsposed/system.prop

**Comment by mr2013** [comment]
That did not work, but adding the prop to /system/build.prop did allow lsposed to run successfully. This fixes the symptom. Without that, the prop is getting set, just later than when magisk/riru tries to access it. Any idea on what could cause this?

**Comment by yujincheng08** [comment]
No idea what's going on with ur ROM. Actually AOSP does not have `startsWith` within `deriveFingerprint` function.

**Comment by vvb2060** [comment]
Can you upload `/system/framework/framework.jar`?

**Comment by mr2013** [comment]
Attached, but renamed to framework.zip as gh doesn't support jar uploads.

[framework.zip](https://github.com/LSPosed/LSPosed/files/6723001/framework.zip)

**Comment by yujincheng08** [comment]
How about uploading `/system/lib64/libandroid_runtime.so` as well?

**Comment by mr2013** [comment]
Attached. gzipped this time.

[libandroid_runtime.so.gz](https://github.com/LSPosed/LSPosed/files/6723157/libandroid_runtime.so.gz)

**Comment by yujincheng08** [comment]
Okay, I think we found the core reason. We run `app_process` for a daemon service and in your device, all `app_process` will die because of a bug in your ROM. The bug is, in `RuntimeInit`, it initializes `android.os.Build.VERSION` before `android.os.Build` so when ART tries to initialize `Build.VERSION`, and it cascades to initialize `Build` but `Build` depends on `Build.VERSION.incremental` which does not finish its initialization and remains `null`. Then the `app_process` crashes.
Well, you may ask `zygote` is also an `app_process` and why it does not crash? It's because its entry is not `RuntimeInit` but `ZygoteInit`, where `Build` is initialized before `Build.VERSION` at some point.

We think it's an AOSP's bug. We will consider reporting it to Google.
