### ISSUE TITLE
[BUG] LSPosedBridge: FakeGApps: Adding the package name service failed.

### ISSUE THREAD

**Issue by srxr** [LSPosed/LSPosed#91]
**什么情况/What happened?**

**Xposed模块列表/Xposed Module List**

- FakeGApps
- Thanox

**Magisk模块列表/Magisk Module List**

**版本信息/Versions**

Architecture: arm64-v8a
Android build: QQ3A.200805.001
Android version: 10
Android sdk: 29
LSPosed version: v0.5.4.0
LSPosed api: 93
Riru version: v23.4 (54)
Riru api: 10
Magisk: 21.4 (21400)

**相关日志/Related Logs**

```
2021-02-07 00:53:21.021 1404-1404/? LSPosedBridge: Thanos stub: github.tornaco.android.thanos.services.ThanosServiceStub@aff3c15@thanos@tornaco:27227657-297d-313e-84f7-f1a5da19a30e
2021-02-07 00:53:21.021 1404-1404/? LSPosedBridge: Adding TV input service @java.lang.Throwable
	at github.tornaco.android.thanos.services.xposed.hooks.ServiceManagerRegistry$1.beforeHookedMethod(Unknown Source:53)
	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:361)
	at SandHookerNew_f49653c72f1b062c94d7e4371bc9516b3957bd10.hook(Unknown Source:69)
	at android.os.ServiceManager.addService(ServiceManager.java:175)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:173)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:380)
	at SandHookerNew_481a6ddfaf3f14f802a2df64f856b5412b2c70a9.hook(Unknown Source:62)
	at github.tornaco.android.thanos.services.ThanosService.publishBinderService(Unknown Source:0)
	at github.tornaco.android.thanos.services.ThanosService.publishBinderService(Unknown Source:1)
	at github.tornaco.android.thanos.services.ThanosService.onStart(Unknown Source:101)
	at github.tornaco.android.thanos.services.BootStrap.start(Unknown Source:12)
	at github.tornaco.android.thanos.services.xposed.hooks.AMSBasicRegistry$1.beforeHookedMethod(Unknown Source:13)
	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:361)
	at SandHookerNew_6ac60ac34871ada3fcd668eed9f337aa0316e059.hook(Unknown Source:46)
	at com.android.server.am.ActivityManagerService.access$1000(ActivityManagerService.java:402)
	at com.android.server.am.ActivityManagerService$Lifecycle.onStart(ActivityManagerService.java:2227)
	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:130)
	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:117)
	at com.android.server.am.ActivityManagerService$Lifecycle.startService(ActivityManagerService.java:2222)
	at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:677)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:183)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:380)
	at SandHookerNew_66d5ed2518d4ec0e52921ac79000e898b8a916f8.hook(Unknown Source:46)
	at com.android.server.SystemServer.run(SystemServer.java:527)
	at com.android.server.SystemServer.main(SystemServer.java:356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:918)

2021-02-07 00:53:21.021 1404-1404/? LSPosedBridge: Thanos stub: github.tornaco.android.thanos.services.ThanosServiceStub@aff3c15@thanos@tornaco:27227657-297d-313e-84f7-f1a5da19a30e
2021-02-07 00:53:22.022 1404-1404/? LSPosedBridge: FakeGApps: caught the NullPointerException
2021-02-07 00:53:22.022 1404-1404/? LSPosedBridge: FakeGApps: caught the NullPointerException
2021-02-07 00:53:22.022 1404-1404/? LSPosedBridge: FakeGApps: Adding the package name service failed.
2021-02-07 00:53:23.023 1404-1404/? LSPosedBridge: FakeGApps: caught the NullPointerException
2021-02-07 00:53:23.023 1404-1404/? LSPosedBridge: FakeGApps: caught the NullPointerException
2021-02-07 00:53:24.024 1404-2271/? LSPosedBridge: FakeGApps: caught the NullPointerException
2021-02-07 00:53:24.024 1404-2271/? LSPosedBridge: FakeGApps: caught the NullPointerException
2021-02-07 00:53:25.025 1404-1404/? LSPosedBridge: FakeGApps: caught the NullPointerException
2021-02-07 00:53:25.025 1404-1404/? LSPosedBridge: FakeGApps: caught the NullPointerException
2021-02-07 00:53:25.025 1404-1404/? LSPosedBridge: FakeGApps: caught the NullPointerException
2021-02-07 00:53:26.026 1404-1404/? LSPosedBridge: PluginBridge  Cannot load any plugins because /data/system/thanos/data/u/0/plugins/plugins_conf.xml was not found
2021-02-07 00:53:26.026 1404-1404/? LSPosedBridge: PluginBridge  boot: android.app.ContextImpl@4aec359, no Plugins active.
2021-02-07 00:53:26.026 1404-1404/? LSPosedBridge: FakeGApps: caught the NullPointerException
2021-02-07 00:53:26.026 1404-1404/? LSPosedBridge: FakeGApps: caught the NullPointerException
2021-02-07 00:53:26.026 1404-1404/? LSPosedBridge: FakeGApps: caught the NullPointerException
2021-02-07 00:53:26.026 1404-1404/? LSPosedBridge: FakeGApps: caught the NullPointerException
2021-02-07 00:53:26.026 1404-1694/? LSPosedBridge: FakeGApps: caught the NullPointerException
```

**Comment by tehcneko** [comment]
Ask module developer
