### ISSUE TITLE
[BUG] SystemUI repeated crash

### ISSUE THREAD

**Issue by techIndia-hacker** [LSPosed/LSPosed#963]
SystemUI repeated crash on Oneplus 7t for module gravitybox

**什么情况/What happened?** SystemUI is crashing often when I swipe down to pull quicksettings menu. A log is generated in the lzposed manager.

**Xposed模块列表/Xposed Module List**
<!-- GravityBox, LuckyPatcher

**Magisk模块列表/Magisk Module List** Riru core. Lsposed, busybox, Overlay mount fix, move certificates, One ui sounds, systemizer

**版本信息/Versions**

Android: 11

Magisk: 23.0

Riru: 26.1.1

LSPosed: 1.5.1

**相关日志/Related Logs**

2021-08-20 12:56:06.006 I/com.android.systemui(2962-3204): Crash unexpectedly: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9392)
	at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:4950)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:977)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:977)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:977)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:977)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:977)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:977)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:977)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:977)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:977)
	at android.view.View.setFlags(View.java:16246)
	at android.view.View.setEnabled(View.java:11823)
	at com.android.systemui.settings.ToggleSliderView.setEnforcedAdmin(ToggleSliderView.java:104)
	at com.android.systemui.settings.BrightnessController$11.run(BrightnessController.java:641)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.os.HandlerThread.run(HandlerThread.java:67

**Comment by techIndia-hacker** [comment]
Wait I wrote everything but it didn't came out

**Comment by yujincheng08** [comment]
You should report to the gravity box since it's caused by the module.

**Comment by techIndia-hacker** [comment]
Please see now

**Comment by yujincheng08** [comment]
report to the module

**Comment by techIndia-hacker** [comment]
But in edxposed this doesn't happen😇

**Comment by yujincheng08** [comment]
It does not prove the thing. Edxposed has problems hooking some methods.

**Comment by techIndia-hacker** [comment]
@C3C0 please comment

**Comment by aviraxp** [comment]
@techIndia-hacker 这是 aosp bug

**Comment by yujincheng08** [comment]
Fixed here: https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/315116
